export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  iconName: string;
  emojis: EmojiItem[];
}

export const EDUCATION_EMOJIS: EmojiItem[] = [
  { emoji: '📚', name: 'books', keywords: ['book', 'study', 'library', 'school', 'read', 'education'] },
  { emoji: '📖', name: 'open book', keywords: ['book', 'read', 'study', 'literature', 'learning'] },
  { emoji: '✏️', name: 'pencil', keywords: ['pencil', 'write', 'draw', 'homework', 'exam', 'notes'] },
  { emoji: '📝', name: 'memo', keywords: ['memo', 'note', 'document', 'assignment', 'paper', 'quiz'] },
  { emoji: '🎓', name: 'graduation cap', keywords: ['graduation', 'degree', 'university', 'college', 'school', 'student'] },
  { emoji: '🏫', name: 'school', keywords: ['school', 'academy', 'campus', 'building', 'classroom'] },
  { emoji: '📐', name: 'triangular ruler', keywords: ['ruler', 'math', 'geometry', 'triangle', 'science'] },
  { emoji: '📏', name: 'straight ruler', keywords: ['ruler', 'measure', 'length', 'math', 'drawing'] },
  { emoji: '🔬', name: 'microscope', keywords: ['microscope', 'science', 'biology', 'lab', 'research'] },
  { emoji: '🧪', name: 'test tube', keywords: ['chemistry', 'experiment', 'science', 'chemical', 'lab'] },
  { emoji: '📊', name: 'bar chart', keywords: ['chart', 'graph', 'data', 'statistics', 'analytics', 'grades'] },
  { emoji: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bright', 'smart', 'creativity', 'solution'] },
  { emoji: '✅', name: 'check mark', keywords: ['correct', 'done', 'passed', 'completed', 'approved', 'right'] },
  { emoji: '❌', name: 'cross mark', keywords: ['wrong', 'incorrect', 'failed', 'false', 'no', 'cancel'] },
  { emoji: '🙋', name: 'person raising hand', keywords: ['question', 'ask', 'answer', 'student', 'permission'] },
  { emoji: '🧑‍🏫', name: 'teacher', keywords: ['teacher', 'instructor', 'professor', 'faculty', 'mentor'] },
  { emoji: '👨‍🏫', name: 'man teacher', keywords: ['teacher', 'professor', 'sir', 'instructor'] },
  { emoji: '👩‍🏫', name: 'woman teacher', keywords: ['teacher', 'professor', 'maam', 'instructor'] },
  { emoji: '🏆', name: 'trophy', keywords: ['winner', 'first', 'award', 'contest', 'success', 'champion'] },
  { emoji: '📌', name: 'pushpin', keywords: ['pin', 'important', 'notice', 'announcement', 'board'] },
  { emoji: '🗓️', name: 'calendar', keywords: ['schedule', 'timetable', 'date', 'exam date', 'deadline'] },
  { emoji: '⏰', name: 'alarm clock', keywords: ['time', 'reminder', 'clock', 'deadline', 'late', 'class'] },
  { emoji: '🎒', name: 'school backpack', keywords: ['backpack', 'bag', 'school', 'supplies'] },
  { emoji: '💻', name: 'laptop', keywords: ['computer', 'class', 'online', 'code', 'typing'] },
  { emoji: '🖥️', name: 'desktop computer', keywords: ['pc', 'screen', 'monitor', 'lab', 'computer'] },
  { emoji: '📋', name: 'clipboard', keywords: ['tasks', 'checklist', 'test', 'rubric', 'syllabus'] },
  { emoji: '📁', name: 'file folder', keywords: ['folder', 'documents', 'archive', 'resources'] },
  { emoji: '📂', name: 'open folder', keywords: ['folder', 'notes', 'resources', 'files'] },
  { emoji: '📑', name: 'bookmark tabs', keywords: ['tabs', 'reading', 'chapter', 'index', 'pages'] },
  { emoji: '🗞️', name: 'newspaper', keywords: ['news', 'bulletin', 'updates', 'announcement'] },
  { emoji: '🔍', name: 'magnifying glass left', keywords: ['search', 'find', 'investigate', 'research'] },
  { emoji: '🔎', name: 'magnifying glass right', keywords: ['search', 'inspect', 'discover', 'seek'] },
  { emoji: '🧠', name: 'brain', keywords: ['mind', 'intellect', 'smart', 'thinking', 'cognition'] },
  { emoji: '🎯', name: 'direct hit', keywords: ['goal', 'target', 'objective', 'aim', 'focus', 'bullseye'] },
  { emoji: '📈', name: 'chart increasing', keywords: ['progress', 'growth', 'improvement', 'success', 'up'] },
  { emoji: '📉', name: 'chart decreasing', keywords: ['drop', 'decrease', 'trend'] },
  { emoji: '🥇', name: '1st place medal', keywords: ['gold', 'first', 'top', 'grade a', 'highest'] },
  { emoji: '🥈', name: '2nd place medal', keywords: ['silver', 'second', 'runner up'] },
  { emoji: '🥉', name: '3rd place medal', keywords: ['bronze', 'third'] },
  { emoji: '🏅', name: 'sports medal', keywords: ['medal', 'achievement', 'merit'] },
  { emoji: '🎖️', name: 'military medal', keywords: ['honor', 'distinction', 'award'] },
  { emoji: '🧮', name: 'abacus', keywords: ['math', 'calculation', 'arithmetic', 'counting'] },
  { emoji: '🖊️', name: 'pen', keywords: ['pen', 'ink', 'signature', 'write', 'paper'] },
  { emoji: '🖋️', name: 'fountain pen', keywords: ['pen', 'calligraphy', 'writing', 'formal'] },
  { emoji: '🖍️', name: 'crayon', keywords: ['color', 'art', 'drawing', 'kids'] },
  { emoji: '✂️', name: 'scissors', keywords: ['cut', 'craft', 'art', 'project'] },
  { emoji: '📎', name: 'paperclip', keywords: ['attach', 'file', 'attachment', 'clip'] },
  { emoji: '🖇️', name: 'linked paperclips', keywords: ['clips', 'attachments', 'connected'] },
  { emoji: '📕', name: 'closed book', keywords: ['textbook', 'red book', 'reading'] },
  { emoji: '📗', name: 'green book', keywords: ['textbook', 'science', 'reading'] },
  { emoji: '📘', name: 'blue book', keywords: ['textbook', 'math', 'reading'] },
  { emoji: '📙', name: 'orange book', keywords: ['textbook', 'history', 'reading'] },
  { emoji: '📜', name: 'scroll', keywords: ['diploma', 'certificate', 'history', 'ancient'] },
  { emoji: '📄', name: 'page facing up', keywords: ['paper', 'document', 'sheet', 'worksheet'] },
  { emoji: '📃', name: 'page with curl', keywords: ['document', 'curl', 'assignment'] },
  { emoji: '✍️', name: 'writing hand', keywords: ['write', 'homework', 'exam', 'sign'] },
  { emoji: '🗣️', name: 'speaking head', keywords: ['speech', 'oral exam', 'presentation', 'talk'] },
  { emoji: '📢', name: 'loudspeaker', keywords: ['announcement', 'notice', 'broadcast', 'important'] },
  { emoji: '🔔', name: 'bell', keywords: ['ring', 'period', 'class start', 'notification'] },
  { emoji: '❓', name: 'question mark', keywords: ['question', 'doubt', 'inquiry', 'help'] },
  { emoji: '❗', name: 'exclamation mark', keywords: ['urgent', 'warning', 'attention', 'notice'] },
  { emoji: '💯', name: 'hundred points', keywords: ['perfect', 'full marks', 'score', '100', 'a plus'] },
];

export const SMILEYS_PEOPLE_EMOJIS: EmojiItem[] = [
  { emoji: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'grin'] },
  { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'joy', 'smile'] },
  { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'laugh', 'smile'] },
  { emoji: '😁', name: 'beaming face with smiling eyes', keywords: ['grin', 'smile', 'cheerful'] },
  { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'lol', 'haha'] },
  { emoji: '😅', name: 'grinning face with sweat', keywords: ['sweat', 'nervous', 'relief', 'exam'] },
  { emoji: '🤣', name: 'rolling on floor laughing', keywords: ['rofl', 'laugh', 'funny'] },
  { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'happy', 'haha'] },
  { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile', 'calm', 'fine'] },
  { emoji: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm', 'irony'] },
  { emoji: '😉', name: 'winking face', keywords: ['wink', 'humor', 'joke'] },
  { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['smile', 'blush', 'warm', 'grateful'] },
  { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'good'] },
  { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore', 'grateful'] },
  { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush', 'adore'] },
  { emoji: '🤩', name: 'star-struck', keywords: ['stars', 'excited', 'amazed', 'wow'] },
  { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'affection'] },
  { emoji: '😗', name: 'kissing face', keywords: ['kiss'] },
  { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'blush'] },
  { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss', 'smile'] },
  { emoji: '😋', name: 'face savoring food', keywords: ['tasty', 'yum', 'delicious'] },
  { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'playful'] },
  { emoji: '😜', name: 'winking face with tongue', keywords: ['playful', 'crazy', 'joke'] },
  { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild', 'goofy'] },
  { emoji: '😝', name: 'squinting face with tongue', keywords: ['prank', 'tongue', 'laugh'] },
  { emoji: '🤑', name: 'money-mouth face', keywords: ['money', 'rich', 'cash'] },
  { emoji: '🤗', name: 'smiling face with open hands', keywords: ['hug', 'welcome', 'warm'] },
  { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle', 'secret'] },
  { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'silence', 'secret', 'library', 'exam'] },
  { emoji: '🤔', name: 'thinking face', keywords: ['think', 'wonder', 'ponder', 'question', 'math'] },
  { emoji: '🤐', name: 'zipper-mouth face', keywords: ['sealed', 'quiet', 'secret'] },
  { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'doubt', 'suspicious'] },
  { emoji: '😐', name: 'neutral face', keywords: ['neutral', 'okay', 'blank'] },
  { emoji: '😑', name: 'expressionless face', keywords: ['unimpressed', 'meh', 'blank'] },
  { emoji: '😶', name: 'face without mouth', keywords: ['mute', 'speechless', 'silent'] },
  { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'cool', 'flirt'] },
  { emoji: '😒', name: 'unamused face', keywords: ['bored', 'unimpressed', 'annoyed'] },
  { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'whatever', 'annoyed'] },
  { emoji: '😬', name: 'grimacing face', keywords: ['grimace', 'nervous', 'awkward'] },
  { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio'] },
  { emoji: '😌', name: 'relieved face', keywords: ['peace', 'relief', 'done', 'calm'] },
  { emoji: '😔', name: 'pensive face', keywords: ['sad', 'disappointed', 'thinking'] },
  { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep', 'rest'] },
  { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'food'] },
  { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'night', 'tired'] },
  { emoji: '😷', name: 'face with medical mask', keywords: ['sick', 'mask', 'covid', 'health'] },
  { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever', 'ill', 'leave'] },
  { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injury', 'pain'] },
  { emoji: '🤢', name: 'nauseated face', keywords: ['gross', 'disgust', 'sick'] },
  { emoji: '🤮', name: 'face vomiting', keywords: ['throw up', 'gross'] },
  { emoji: '🤧', name: 'sneezing face', keywords: ['sneeze', 'flu', 'sick'] },
  { emoji: '🥵', name: 'hot face', keywords: ['heat', 'summer', 'sweat'] },
  { emoji: '🥶', name: 'cold face', keywords: ['freeze', 'ice', 'winter'] },
  { emoji: '🥴', name: 'woozy face', keywords: ['dizzy', 'tired', 'confused'] },
  { emoji: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'passed out', 'exam'] },
  { emoji: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked', 'wow', 'hard'] },
  { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'country'] },
  { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'passed', 'congrats'] },
  { emoji: '🥸', name: 'disguised face', keywords: ['glasses', 'disguise', 'mustache'] },
  { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'confident', 'ace'] },
  { emoji: '🤓', name: 'nerd face', keywords: ['geek', 'studious', 'smart', 'books'] },
  { emoji: '🧐', name: 'face with monocle', keywords: ['inspect', 'curious', 'examine'] },
  { emoji: '😕', name: 'confused face', keywords: ['confused', 'puzzled', 'doubt'] },
  { emoji: '😟', name: 'worried face', keywords: ['worry', 'nervous', 'anxious'] },
  { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
  { emoji: '😮', name: 'face with open mouth', keywords: ['surprise', 'wow', 'gasp'] },
  { emoji: '😯', name: 'hushed face', keywords: ['quiet', 'surprise'] },
  { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'omg', 'amazed'] },
  { emoji: '😳', name: 'flushed face', keywords: ['blush', 'embarrassed', 'shy'] },
  { emoji: '🥺', name: 'pleading face', keywords: ['please', 'puppy eyes', 'beg'] },
  { emoji: '😦', name: 'frowning face with open mouth', keywords: ['shock', 'aww'] },
  { emoji: '😧', name: 'anguished face', keywords: ['pain', 'stress'] },
  { emoji: '😨', name: 'fearful face', keywords: ['scared', 'afraid', 'test'] },
  { emoji: '😰', name: 'anxious face with sweat', keywords: ['anxiety', 'worried', 'stress'] },
  { emoji: '😥', name: 'sad but relieved face', keywords: ['relief', 'whew'] },
  { emoji: '😢', name: 'crying face', keywords: ['sad', 'tear', 'cry'] },
  { emoji: '😭', name: 'loudly crying face', keywords: ['bawl', 'sobbing', 'tears', 'fail'] },
  { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'shock', 'omg', 'deadline'] },
  { emoji: '😖', name: 'confounded face', keywords: ['stress', 'frustrated'] },
  { emoji: '😣', name: 'persevering face', keywords: ['struggle', 'try hard'] },
  { emoji: '😞', name: 'disappointed face', keywords: ['sad', 'regret', 'down'] },
  { emoji: '😓', name: 'downcast face with sweat', keywords: ['hard work', 'exhausted'] },
  { emoji: '😩', name: 'weary face', keywords: ['tired', 'fed up'] },
  { emoji: '😫', name: 'tired face', keywords: ['exhausted', 'sleepy'] },
  { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'bored', 'sleepy'] },
  { emoji: '😤', name: 'face with steam from nose', keywords: ['determined', 'proud', 'angry'] },
  { emoji: '😡', name: 'enraged face', keywords: ['angry', 'mad', 'furious'] },
  { emoji: '😠', name: 'angry face', keywords: ['mad', 'annoyed'] },
  { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['cursing', 'mad'] },
  { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'mischief'] },
  { emoji: '👿', name: 'angry face with horns', keywords: ['evil', 'demon'] },
  { emoji: '💀', name: 'skull', keywords: ['dead', 'skeleton', 'died laughing'] },
  { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'funny'] },
  { emoji: '🤡', name: 'clown face', keywords: ['clown', 'silly', 'joke'] },
  { emoji: '👻', name: 'ghost', keywords: ['spooky', 'halloween', 'boo'] },
  { emoji: '👽', name: 'alien', keywords: ['ufo', 'space'] },
  { emoji: '🤖', name: 'robot', keywords: ['bot', 'tech', 'ai'] },
  { emoji: '😺', name: 'grinning cat', keywords: ['cat', 'smile'] },
  { emoji: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat', 'laugh'] },
  { emoji: '😹', name: 'cat with tears of joy', keywords: ['cat', 'tears', 'lol'] },
  { emoji: '😻', name: 'smiling cat with heart-eyes', keywords: ['cat', 'love'] },
  { emoji: '😼', name: 'cat with wry smile', keywords: ['cat', 'smirk'] },
  { emoji: '😽', name: 'kissing cat', keywords: ['cat', 'kiss'] },
  { emoji: '🙀', name: 'weary cat', keywords: ['cat', 'shocked'] },
  { emoji: '😿', name: 'crying cat', keywords: ['cat', 'sad'] },
  { emoji: '😾', name: 'pouting cat', keywords: ['cat', 'mad'] },
  { emoji: '🤲', name: 'palms up together', keywords: ['prayer', 'dua', 'hope', 'bless'] },
  { emoji: '👐', name: 'open hands', keywords: ['hands', 'open'] },
  { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray', 'praise'] },
  { emoji: '👏', name: 'clapping hands', keywords: ['applause', 'bravo', 'well done', 'good job'] },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'welcome', 'partnership'] },
  { emoji: '👍', name: 'thumbs up', keywords: ['yes', 'agree', 'good', 'approved', 'like', 'ok'] },
  { emoji: '👎', name: 'thumbs down', keywords: ['no', 'disagree', 'bad', 'dislike'] },
  { emoji: '👊', name: 'oncoming fist', keywords: ['fist bump', 'punch'] },
  { emoji: '✊', name: 'raised fist', keywords: ['power', 'solidarity'] },
  { emoji: '🤛', name: 'left-facing fist', keywords: ['fist bump'] },
  { emoji: '🤜', name: 'right-facing fist', keywords: ['fist bump'] },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope', 'exam luck'] },
  { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'victory', 'two'] },
  { emoji: '🤟', name: 'love-you gesture', keywords: ['love you'] },
  { emoji: '🤘', name: 'sign of the horns', keywords: ['rock on'] },
  { emoji: '👌', name: 'OK hand', keywords: ['perfect', 'okay', 'fine', 'understood'] },
  { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'what do you mean'] },
  { emoji: '🤏', name: 'pinching hand', keywords: ['little bit', 'tiny', 'small'] },
  { emoji: '👈', name: 'backhand index pointing left', keywords: ['point left'] },
  { emoji: '👉', name: 'backhand index pointing right', keywords: ['point right'] },
  { emoji: '👆', name: 'backhand index pointing up', keywords: ['point up', 'look above'] },
  { emoji: '👇', name: 'backhand index pointing down', keywords: ['point down', 'below'] },
  { emoji: '☝️', name: 'index pointing up', keywords: ['one', 'attention', 'first'] },
  { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five', 'hand'] },
  { emoji: '🤚', name: 'raised back of hand', keywords: ['backhand'] },
  { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['five', 'hand'] },
  { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'peace'] },
  { emoji: '👋', name: 'waving hand', keywords: ['hello', 'hi', 'bye', 'wave'] },
  { emoji: '🤙', name: 'call me hand', keywords: ['shaka', 'call'] },
  { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'strength', 'power', 'motivation', 'study hard'] },
  { emoji: '🙏', name: 'folded hands', keywords: ['please', 'thank you', 'pray', 'namaste', 'respect'] },
  { emoji: '👶', name: 'baby', keywords: ['child', 'infant'] },
  { emoji: '👧', name: 'girl', keywords: ['female', 'student'] },
  { emoji: '👦', name: 'boy', keywords: ['male', 'student'] },
  { emoji: '👩', name: 'woman', keywords: ['female', 'adult'] },
  { emoji: '👨', name: 'man', keywords: ['male', 'adult'] },
  { emoji: '🧑‍🎓', name: 'student', keywords: ['learner', 'pupil', 'graduate'] },
  { emoji: '👨‍🎓', name: 'man student', keywords: ['male student', 'graduate'] },
  { emoji: '👩‍🎓', name: 'woman student', keywords: ['female student', 'graduate'] },
  { emoji: '🧑‍💻', name: 'technologist', keywords: ['coder', 'programmer', 'computer'] },
];

export const ANIMALS_NATURE_EMOJIS: EmojiItem[] = [
  { emoji: '🐶', name: 'dog face', keywords: ['puppy', 'pet'] },
  { emoji: '🐱', name: 'cat face', keywords: ['kitten', 'pet'] },
  { emoji: '🐭', name: 'mouse face', keywords: ['rodent'] },
  { emoji: '🐹', name: 'hamster face', keywords: ['pet'] },
  { emoji: '🐰', name: 'rabbit face', keywords: ['bunny'] },
  { emoji: '🦊', name: 'fox face', keywords: ['clever'] },
  { emoji: '🐻', name: 'bear face', keywords: ['wild'] },
  { emoji: '🐼', name: 'panda face', keywords: ['bamboo'] },
  { emoji: '🐨', name: 'koala', keywords: ['australia'] },
  { emoji: '🐯', name: 'tiger face', keywords: ['stripes', 'fierce'] },
  { emoji: '🦁', name: 'lion', keywords: ['king', 'brave'] },
  { emoji: '🐮', name: 'cow face', keywords: ['milk'] },
  { emoji: '🐷', name: 'pig face', keywords: ['oink'] },
  { emoji: '🐸', name: 'frog face', keywords: ['amphibian'] },
  { emoji: '🐵', name: 'monkey face', keywords: ['jungle'] },
  { emoji: '🐔', name: 'chicken', keywords: ['bird', 'poultry'] },
  { emoji: '🐧', name: 'penguin', keywords: ['antarctica', 'cold'] },
  { emoji: '🐦', name: 'bird', keywords: ['fly', 'nature'] },
  { emoji: '🐤', name: 'baby chick', keywords: ['yellow', 'cute'] },
  { emoji: '🦆', name: 'duck', keywords: ['water'] },
  { emoji: '🦅', name: 'eagle', keywords: ['predator', 'usa'] },
  { emoji: '🦉', name: 'owl', keywords: ['wise', 'night', 'wisdom', 'study'] },
  { emoji: '🦇', name: 'bat', keywords: ['night', 'vampire'] },
  { emoji: '🐺', name: 'wolf', keywords: ['pack', 'howl'] },
  { emoji: '🐴', name: 'horse face', keywords: ['equine'] },
  { emoji: '🦄', name: 'unicorn', keywords: ['magic', 'fantasy'] },
  { emoji: '🐝', name: 'honeybee', keywords: ['busy', 'honey', 'study'] },
  { emoji: '🐛', name: 'bug', keywords: ['caterpillar', 'insect'] },
  { emoji: '🦋', name: 'butterfly', keywords: ['pretty', 'wings', 'nature'] },
  { emoji: '🐌', name: 'snail', keywords: ['slow'] },
  { emoji: '🐞', name: 'lady beetle', keywords: ['ladybug', 'luck'] },
  { emoji: '🐜', name: 'ant', keywords: ['hard worker', 'colony'] },
  { emoji: '🐢', name: 'turtle', keywords: ['slow and steady', 'tortoise'] },
  { emoji: '🐍', name: 'snake', keywords: ['reptile'] },
  { emoji: '🐙', name: 'octopus', keywords: ['tentacles', 'sea'] },
  { emoji: '🐬', name: 'dolphin', keywords: ['smart', 'ocean'] },
  { emoji: '🐳', name: 'spouting whale', keywords: ['whale', 'ocean'] },
  { emoji: '🦈', name: 'shark', keywords: ['ocean', 'teeth'] },
  { emoji: '🌲', name: 'evergreen tree', keywords: ['pine', 'nature', 'forest'] },
  { emoji: '🌳', name: 'deciduous tree', keywords: ['nature', 'wood'] },
  { emoji: '🌴', name: 'palm tree', keywords: ['beach', 'summer'] },
  { emoji: '🌵', name: 'cactus', keywords: ['desert', 'spikes'] },
  { emoji: '🌾', name: 'sheaf of rice', keywords: ['grain', 'agriculture'] },
  { emoji: '🌿', name: 'herb', keywords: ['plant', 'leaf', 'green'] },
  { emoji: '☘️', name: 'shamrock', keywords: ['clover', 'ireland'] },
  { emoji: '🍀', name: 'four leaf clover', keywords: ['luck', 'good luck', 'fortune'] },
  { emoji: '🍁', name: 'maple leaf', keywords: ['autumn', 'fall', 'canada'] },
  { emoji: '🍂', name: 'fallen leaf', keywords: ['autumn', 'leaves'] },
  { emoji: '🍃', name: 'leaf fluttering in wind', keywords: ['breeze', 'leaf'] },
  { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring', 'sakura'] },
  { emoji: '🌹', name: 'rose', keywords: ['red', 'flower', 'romance'] },
  { emoji: '🌻', name: 'sunflower', keywords: ['sun', 'yellow', 'bright'] },
  { emoji: '🌼', name: 'blossom', keywords: ['flower'] },
  { emoji: '🌷', name: 'tulip', keywords: ['spring', 'flower'] },
  { emoji: '🌱', name: 'seedling', keywords: ['growth', 'learning', 'plant', 'fresh'] },
  { emoji: '☀️', name: 'sun', keywords: ['sunny', 'weather', 'warm'] },
  { emoji: '🌤️', name: 'sun behind small cloud', keywords: ['partly sunny'] },
  { emoji: '⛅', name: 'sun behind cloud', keywords: ['cloudy'] },
  { emoji: '☁️', name: 'cloud', keywords: ['sky', 'weather'] },
  { emoji: '🌧️', name: 'cloud with rain', keywords: ['rain', 'monsoon'] },
  { emoji: '⛈️', name: 'cloud with lightning and rain', keywords: ['storm', 'thunder'] },
  { emoji: '❄️', name: 'snowflake', keywords: ['snow', 'cold', 'winter'] },
  { emoji: '⚡', name: 'high voltage', keywords: ['zap', 'lightning', 'energy', 'electricity'] },
  { emoji: '🌈', name: 'rainbow', keywords: ['colors', 'hope', 'sky'] },
  { emoji: '💧', name: 'droplet', keywords: ['water', 'drop', 'sweat'] },
  { emoji: '🌊', name: 'water wave', keywords: ['ocean', 'sea', 'surf'] },
];

export const FOOD_DRINK_EMOJIS: EmojiItem[] = [
  { emoji: '🍏', name: 'green apple', keywords: ['fruit', 'healthy'] },
  { emoji: '🍎', name: 'red apple', keywords: ['fruit', 'teacher gift', 'school'] },
  { emoji: '🍐', name: 'pear', keywords: ['fruit'] },
  { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'citrus'] },
  { emoji: '🍋', name: 'lemon', keywords: ['sour', 'citrus'] },
  { emoji: '🍌', name: 'banana', keywords: ['fruit', 'potassium'] },
  { emoji: '🍉', name: 'watermelon', keywords: ['summer', 'fruit'] },
  { emoji: '🍇', name: 'grapes', keywords: ['wine', 'fruit'] },
  { emoji: '🍓', name: 'strawberry', keywords: ['berry', 'sweet'] },
  { emoji: '🫐', name: 'blueberries', keywords: ['berry'] },
  { emoji: '🍒', name: 'cherries', keywords: ['red', 'fruit'] },
  { emoji: '🍑', name: 'peach', keywords: ['fruit'] },
  { emoji: '🥭', name: 'mango', keywords: ['tropical', 'fruit'] },
  { emoji: '🍍', name: 'pineapple', keywords: ['tropical'] },
  { emoji: '🥥', name: 'coconut', keywords: ['nut', 'tropical'] },
  { emoji: '🥝', name: 'kiwi fruit', keywords: ['fruit'] },
  { emoji: '🥑', name: 'avocado', keywords: ['healthy', 'green'] },
  { emoji: '🍞', name: 'bread', keywords: ['toast', 'bakery'] },
  { emoji: '🥐', name: 'croissant', keywords: ['french', 'pastry'] },
  { emoji: '🍕', name: 'pizza', keywords: ['slice', 'cheese', 'party'] },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food'] },
  { emoji: '🍟', name: 'french fries', keywords: ['fries', 'snack'] },
  { emoji: '🌭', name: 'hot dog', keywords: ['sausage'] },
  { emoji: '🥪', name: 'sandwich', keywords: ['lunch', 'snack', 'school lunch'] },
  { emoji: '🌮', name: 'taco', keywords: ['mexican'] },
  { emoji: '🌯', name: 'burrito', keywords: ['wrap'] },
  { emoji: '🥗', name: 'green salad', keywords: ['healthy', 'veggies'] },
  { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'italian'] },
  { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup'] },
  { emoji: '🍲', name: 'pot of food', keywords: ['stew', 'curry', 'soup'] },
  { emoji: '🍛', name: 'curry rice', keywords: ['curry', 'spicy'] },
  { emoji: '🍣', name: 'sushi', keywords: ['japanese', 'fish'] },
  { emoji: '🍱', name: 'bento box', keywords: ['lunchbox', 'japanese'] },
  { emoji: '🍙', name: 'rice ball', keywords: ['onigiri'] },
  { emoji: '🍚', name: 'cooked rice', keywords: ['rice', 'grain'] },
  { emoji: '🍦', name: 'soft ice cream', keywords: ['icecream', 'dessert'] },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'sweet'] },
  { emoji: '🍪', name: 'cookie', keywords: ['biscuit', 'chocolate chip'] },
  { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'celebration', 'party'] },
  { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'slice'] },
  { emoji: '🧁', name: 'cupcake', keywords: ['sweet', 'bakery'] },
  { emoji: '🍫', name: 'chocolate bar', keywords: ['candy', 'sweet'] },
  { emoji: '🍿', name: 'popcorn', keywords: ['movie', 'snack'] },
  { emoji: '🥛', name: 'glass of milk', keywords: ['dairy', 'calcium'] },
  { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'study fuel', 'morning'] },
  { emoji: '🫖', name: 'teapot', keywords: ['tea', 'chai'] },
  { emoji: '🍵', name: 'teacup without handle', keywords: ['green tea', 'matcha'] },
  { emoji: '🧃', name: 'beverage box', keywords: ['juice box', 'school'] },
  { emoji: '🥤', name: 'cup with straw', keywords: ['soda', 'drink'] },
  { emoji: '🧋', name: 'bubble tea', keywords: ['boba', 'tea'] },
];

export const ACTIVITIES_EMOJIS: EmojiItem[] = [
  { emoji: '⚽', name: 'soccer ball', keywords: ['football', 'sports', 'game'] },
  { emoji: '🏀', name: 'basketball', keywords: ['hoops', 'sports'] },
  { emoji: '🏈', name: 'american football', keywords: ['nfl', 'sports'] },
  { emoji: '⚾', name: 'baseball', keywords: ['sports', 'game'] },
  { emoji: '🎾', name: 'tennis', keywords: ['racket', 'sports'] },
  { emoji: '🏐', name: 'volleyball', keywords: ['sports'] },
  { emoji: '🏉', name: 'rugby football', keywords: ['sports'] },
  { emoji: '🥏', name: 'flying disc', keywords: ['frisbee'] },
  { emoji: '🏓', name: 'ping pong', keywords: ['table tennis'] },
  { emoji: '🏸', name: 'badminton', keywords: ['shuttlecock'] },
  { emoji: '🏒', name: 'ice hockey', keywords: ['sports'] },
  { emoji: '🏏', name: 'cricket game', keywords: ['bat', 'wicket', 'pakistan cricket'] },
  { emoji: '🎯', name: 'bullseye', keywords: ['target', 'darts', 'focus'] },
  { emoji: '⛳', name: 'flag in hole', keywords: ['golf'] },
  { emoji: '🥊', name: 'boxing glove', keywords: ['fight'] },
  { emoji: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo'] },
  { emoji: '🛹', name: 'skateboard', keywords: ['skating'] },
  { emoji: '🚴', name: 'person biking', keywords: ['bicycle', 'cycling'] },
  { emoji: '🏊', name: 'person swimming', keywords: ['pool', 'swim'] },
  { emoji: '🏋️', name: 'person lifting weights', keywords: ['gym', 'workout', 'fitness'] },
  { emoji: '🧗', name: 'person climbing', keywords: ['climb', 'rock'] },
  { emoji: '🧘', name: 'person in lotus position', keywords: ['meditation', 'yoga', 'calm'] },
  { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'creativity', 'drawing'] },
  { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'cinema'] },
  { emoji: '🎤', name: 'microphone', keywords: ['sing', 'karaoke', 'speech'] },
  { emoji: '🎧', name: 'headphone', keywords: ['music', 'audio', 'listen'] },
  { emoji: '🎼', name: 'musical score', keywords: ['music', 'notes'] },
  { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'music'] },
  { emoji: '🥁', name: 'drum', keywords: ['music', 'beat'] },
  { emoji: '🎷', name: 'saxophone', keywords: ['jazz', 'music'] },
  { emoji: '🎺', name: 'trumpet', keywords: ['brass', 'music'] },
  { emoji: '🎸', name: 'guitar', keywords: ['rock', 'strings'] },
  { emoji: '🎻', name: 'violin', keywords: ['classical', 'strings'] },
  { emoji: '🎲', name: 'game die', keywords: ['dice', 'board game', 'chance'] },
  { emoji: '♟️', name: 'chess pawn', keywords: ['chess', 'strategy', 'game'] },
  { emoji: '🎳', name: 'bowling', keywords: ['pins', 'strike'] },
  { emoji: '🎮', name: 'video game', keywords: ['controller', 'gaming', 'play'] },
  { emoji: '🧩', name: 'puzzle piece', keywords: ['jigsaw', 'problem solving'] },
];

export const TRAVEL_PLACES_EMOJIS: EmojiItem[] = [
  { emoji: '🚗', name: 'automobile', keywords: ['car', 'drive'] },
  { emoji: '🚕', name: 'taxi', keywords: ['cab'] },
  { emoji: '🚙', name: 'sport utility vehicle', keywords: ['suv'] },
  { emoji: '🚌', name: 'bus', keywords: ['school bus', 'transit'] },
  { emoji: '🚎', name: 'trolleybus', keywords: ['transit'] },
  { emoji: '🏎️', name: 'racing car', keywords: ['fast'] },
  { emoji: '🚓', name: 'police car', keywords: ['emergency'] },
  { emoji: '🚑', name: 'ambulance', keywords: ['hospital', 'emergency'] },
  { emoji: '🚒', name: 'fire engine', keywords: ['fire'] },
  { emoji: '🚐', name: 'minibus', keywords: ['van'] },
  { emoji: '🚚', name: 'delivery truck', keywords: ['shipping'] },
  { emoji: '🚛', name: 'articulated lorry', keywords: ['truck'] },
  { emoji: '🚲', name: 'bicycle', keywords: ['bike'] },
  { emoji: '🛴', name: 'kick scooter', keywords: ['scooter'] },
  { emoji: '🛵', name: 'motor scooter', keywords: ['vespa'] },
  { emoji: '🏍️', name: 'motorcycle', keywords: ['bike'] },
  { emoji: '🚨', name: 'police car light', keywords: ['alarm', 'alert', 'urgent'] },
  { emoji: '🚏', name: 'bus stop', keywords: ['stop'] },
  { emoji: '⛽', name: 'fuel pump', keywords: ['gas', 'petrol'] },
  { emoji: '🚦', name: 'vertical traffic light', keywords: ['signal', 'lights'] },
  { emoji: '🛑', name: 'stop sign', keywords: ['stop', 'halt'] },
  { emoji: '✈️', name: 'airplane', keywords: ['flight', 'travel'] },
  { emoji: '🛫', name: 'airplane departure', keywords: ['takeoff'] },
  { emoji: '🛬', name: 'airplane arrival', keywords: ['landing'] },
  { emoji: '🚀', name: 'rocket', keywords: ['space', 'launch', 'fast', 'success'] },
  { emoji: '🛸', name: 'flying saucer', keywords: ['ufo'] },
  { emoji: '🚁', name: 'helicopter', keywords: ['flight'] },
  { emoji: '⛵', name: 'sailboat', keywords: ['boat', 'sea'] },
  { emoji: '🚢', name: 'ship', keywords: ['cruise'] },
  { emoji: '⚓', name: 'anchor', keywords: ['ship', 'marine'] },
  { emoji: '🗺️', name: 'world map', keywords: ['geography', 'earth', 'travel', 'places'] },
  { emoji: '🗽', name: 'Statue of Liberty', keywords: ['new york', 'usa'] },
  { emoji: '🗼', name: 'Tokyo tower', keywords: ['japan'] },
  { emoji: '🏰', name: 'castle', keywords: ['palace'] },
  { emoji: '⛲', name: 'fountain', keywords: ['park'] },
  { emoji: '⛺', name: 'tent', keywords: ['camping'] },
  { emoji: '🏠', name: 'house', keywords: ['home'] },
  { emoji: '🏡', name: 'house with garden', keywords: ['home'] },
  { emoji: '🏢', name: 'office building', keywords: ['work'] },
  { emoji: '🏣', name: 'Japanese post office', keywords: ['post'] },
  { emoji: '🏥', name: 'hospital', keywords: ['doctor', 'clinic', 'medicine'] },
  { emoji: '🏦', name: 'bank', keywords: ['money', 'finance'] },
  { emoji: '🏛️', name: 'classical building', keywords: ['museum', 'government', 'monument'] },
  { emoji: '🕌', name: 'mosque', keywords: ['islam', 'prayer', 'masjid'] },
  { emoji: '⛪', name: 'church', keywords: ['religion'] },
  { emoji: '🕋', name: 'kaaba', keywords: ['makkah', 'hajj', 'islam'] },
  { emoji: '🌅', name: 'sunrise', keywords: ['morning', 'dawn'] },
  { emoji: '🌄', name: 'sunrise over mountains', keywords: ['scenic'] },
  { emoji: '🌇', name: 'sunset', keywords: ['evening'] },
  { emoji: '🌆', name: 'cityscape at dusk', keywords: ['city'] },
  { emoji: '🌉', name: 'bridge at night', keywords: ['bridge'] },
];

export const OBJECTS_EMOJIS: EmojiItem[] = [
  { emoji: '⌚', name: 'watch', keywords: ['time', 'wristwatch'] },
  { emoji: '📱', name: 'mobile phone', keywords: ['cell', 'smartphone'] },
  { emoji: '📲', name: 'mobile phone with arrow', keywords: ['call', 'incoming'] },
  { emoji: '☎️', name: 'telephone', keywords: ['landline', 'phone'] },
  { emoji: '📞', name: 'telephone receiver', keywords: ['call'] },
  { emoji: '🔋', name: 'battery', keywords: ['power', 'charge'] },
  { emoji: '🔌', name: 'electric plug', keywords: ['power', 'cable'] },
  { emoji: '🔦', name: 'flashlight', keywords: ['torch', 'light'] },
  { emoji: '🕯️', name: 'candle', keywords: ['light', 'wax'] },
  { emoji: '💵', name: 'dollar banknote', keywords: ['money', 'cash'] },
  { emoji: '🪙', name: 'coin', keywords: ['gold', 'money'] },
  { emoji: '💰', name: 'money bag', keywords: ['wealth', 'rich'] },
  { emoji: '💳', name: 'credit card', keywords: ['payment'] },
  { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'jewel'] },
  { emoji: '⚖️', name: 'balance scale', keywords: ['justice', 'law', 'balance', 'weight'] },
  { emoji: '🧰', name: 'toolbox', keywords: ['tools', 'fix'] },
  { emoji: '🔧', name: 'wrench', keywords: ['tool', 'settings', 'fix'] },
  { emoji: '🔨', name: 'hammer', keywords: ['tool', 'build'] },
  { emoji: '⚙️', name: 'gear', keywords: ['settings', 'options', 'mechanism'] },
  { emoji: '🧲', name: 'magnet', keywords: ['physics', 'attract'] },
  { emoji: '🧪', name: 'test tube', keywords: ['chemistry', 'experiment'] },
  { emoji: '🧫', name: 'petri dish', keywords: ['biology', 'bacteria'] },
  { emoji: '🧬', name: 'dna', keywords: ['genetics', 'biology', 'science'] },
  { emoji: '🔭', name: 'telescope', keywords: ['astronomy', 'stars', 'space'] },
  { emoji: '📡', name: 'satellite antenna', keywords: ['signal', 'wifi'] },
  { emoji: '💉', name: 'syringe', keywords: ['injection', 'medicine'] },
  { emoji: '💊', name: 'pill', keywords: ['medicine', 'pharmacy'] },
  { emoji: '🩹', name: 'adhesive bandage', keywords: ['bandaid', 'first aid'] },
  { emoji: '🩺', name: 'stethoscope', keywords: ['doctor', 'medical'] },
  { emoji: '🚪', name: 'door', keywords: ['entry', 'exit'] },
  { emoji: '🔑', name: 'key', keywords: ['password', 'secret', 'access'] },
  { emoji: '🗝️', name: 'old key', keywords: ['antique'] },
  { emoji: '🛋️', name: 'couch and lamp', keywords: ['sofa', 'relax'] },
  { emoji: '🛏️', name: 'bed', keywords: ['sleep', 'hotel'] },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['present', 'birthday'] },
  { emoji: '🎈', name: 'balloon', keywords: ['celebrate', 'party'] },
  { emoji: '🎉', name: 'party popper', keywords: ['tada', 'congrats', 'celebration', 'passed'] },
  { emoji: '🎊', name: 'confetti ball', keywords: ['party'] },
  { emoji: '✉️', name: 'envelope', keywords: ['mail', 'letter', 'message'] },
  { emoji: '📩', name: 'envelope with arrow', keywords: ['incoming email'] },
  { emoji: '📨', name: 'incoming envelope', keywords: ['mail'] },
  { emoji: '📧', name: 'e-mail', keywords: ['communication', 'inbox'] },
  { emoji: '📦', name: 'package', keywords: ['parcel', 'delivery'] },
  { emoji: '🏷️', name: 'label', keywords: ['tag'] },
  { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete'] },
  { emoji: '🔒', name: 'locked', keywords: ['secure', 'privacy', 'secret'] },
  { emoji: '🔓', name: 'unlocked', keywords: ['open'] },
];

export const SYMBOLS_EMOJIS: EmojiItem[] = [
  { emoji: '❤️', name: 'red heart', keywords: ['love', 'like', 'heart'] },
  { emoji: '🧡', name: 'orange heart', keywords: ['heart'] },
  { emoji: '💛', name: 'yellow heart', keywords: ['heart', 'friendship'] },
  { emoji: '💚', name: 'green heart', keywords: ['heart', 'nature'] },
  { emoji: '💙', name: 'blue heart', keywords: ['heart', 'scholario'] },
  { emoji: '💜', name: 'purple heart', keywords: ['heart'] },
  { emoji: '🖤', name: 'black heart', keywords: ['heart'] },
  { emoji: '🤍', name: 'white heart', keywords: ['heart', 'pure'] },
  { emoji: '💔', name: 'broken heart', keywords: ['sad', 'break'] },
  { emoji: '❣️', name: 'heart exclamation', keywords: ['heart'] },
  { emoji: '💕', name: 'two hearts', keywords: ['love'] },
  { emoji: '💖', name: 'sparkling heart', keywords: ['love', 'glitter'] },
  { emoji: '💗', name: 'growing heart', keywords: ['love'] },
  { emoji: '🔥', name: 'fire', keywords: ['hot', 'lit', 'streak', 'flame', 'awesome'] },
  { emoji: '⭐', name: 'star', keywords: ['favorite', 'rating', 'top', 'achievement'] },
  { emoji: '🌟', name: 'glowing star', keywords: ['star', 'brilliant', 'excellent'] },
  { emoji: '✨', name: 'sparkles', keywords: ['magic', 'shine', 'special', 'ai', 'clean'] },
  { emoji: '⚡', name: 'high voltage', keywords: ['power', 'fast'] },
  { emoji: '💥', name: 'collision', keywords: ['boom', 'blast'] },
  { emoji: '💢', name: 'anger symbol', keywords: ['mad'] },
  { emoji: '💯', name: 'hundred points', keywords: ['perfect', 'score', '100'] },
  { emoji: '💤', name: 'zzz', keywords: ['sleep', 'bored'] },
  { emoji: '✔️', name: 'check mark', keywords: ['done', 'yes', 'verified'] },
  { emoji: '☑️', name: 'check box with check', keywords: ['completed', 'task'] },
  { emoji: '➕', name: 'plus', keywords: ['add', 'math'] },
  { emoji: '➖', name: 'minus', keywords: ['subtract', 'math'] },
  { emoji: '✖️', name: 'multiply', keywords: ['times', 'math'] },
  { emoji: '➗', name: 'divide', keywords: ['division', 'math'] },
  { emoji: '🟰', name: 'heavy equals sign', keywords: ['equal', 'math'] },
  { emoji: '♾️', name: 'infinity', keywords: ['forever', 'math', 'limit'] },
  { emoji: '❓', name: 'red question mark', keywords: ['question', 'help', 'ask'] },
  { emoji: '❔', name: 'white question mark', keywords: ['question'] },
  { emoji: '❗', name: 'red exclamation mark', keywords: ['urgent', 'important'] },
  { emoji: '❕', name: 'white exclamation mark', keywords: ['notice'] },
  { emoji: '‼️', name: 'double exclamation mark', keywords: ['very urgent'] },
  { emoji: '⁉️', name: 'exclamation question mark', keywords: ['surprise'] },
  { emoji: '⚠️', name: 'warning', keywords: ['alert', 'caution', 'notice'] },
  { emoji: '🚫', name: 'prohibited', keywords: ['no', 'forbidden'] },
  { emoji: '🛑', name: 'stop sign', keywords: ['stop', 'halt'] },
  { emoji: '🆗', name: 'OK button', keywords: ['ok', 'agreed'] },
  { emoji: '🆙', name: 'UP! button', keywords: ['up'] },
  { emoji: '🆒', name: 'COOL button', keywords: ['cool'] },
  { emoji: '🆕', name: 'NEW button', keywords: ['new', 'fresh'] },
  { emoji: '🆓', name: 'FREE button', keywords: ['free'] },
  { emoji: '🔟', name: 'keycap 10', keywords: ['ten', 'score'] },
  { emoji: '🟢', name: 'green circle', keywords: ['active', 'online', 'pass'] },
  { emoji: '🔴', name: 'red circle', keywords: ['offline', 'recording', 'fail'] },
  { emoji: '🟡', name: 'yellow circle', keywords: ['pending', 'warning'] },
  { emoji: '🔵', name: 'blue circle', keywords: ['dot'] },
  { emoji: '🟣', name: 'purple circle', keywords: ['dot'] },
  { emoji: '⚪', name: 'white circle', keywords: ['dot'] },
  { emoji: '⚫', name: 'black circle', keywords: ['dot'] },
];

export const FLAGS_EMOJIS: EmojiItem[] = [
  { emoji: '🇵🇰', name: 'Pakistan', keywords: ['pakistan', 'flag', 'pk'] },
  { emoji: '🇺🇸', name: 'United States', keywords: ['usa', 'america'] },
  { emoji: '🇬🇧', name: 'United Kingdom', keywords: ['uk', 'britain', 'england'] },
  { emoji: '🇨🇦', name: 'Canada', keywords: ['canada'] },
  { emoji: '🇦🇺', name: 'Australia', keywords: ['australia'] },
  { emoji: '🇸🇦', name: 'Saudi Arabia', keywords: ['saudi', 'arabia', 'ksa'] },
  { emoji: '🇦🇪', name: 'United Arab Emirates', keywords: ['uae', 'dubai'] },
  { emoji: '🇹🇷', name: 'Turkey', keywords: ['turkey', 'turkiye'] },
  { emoji: '🇩🇪', name: 'Germany', keywords: ['germany'] },
  { emoji: '🇫🇷', name: 'France', keywords: ['france'] },
  { emoji: '🇪🇸', name: 'Spain', keywords: ['spain'] },
  { emoji: '🇮🇹', name: 'Italy', keywords: ['italy'] },
  { emoji: '🇨🇳', name: 'China', keywords: ['china'] },
  { emoji: '🇯🇵', name: 'Japan', keywords: ['japan'] },
  { emoji: '🇰🇷', name: 'South Korea', keywords: ['korea'] },
  { emoji: '🇮🇳', name: 'India', keywords: ['india'] },
  { emoji: '🇧🇩', name: 'Bangladesh', keywords: ['bangladesh'] },
  { emoji: '🇲🇾', name: 'Malaysia', keywords: ['malaysia'] },
  { emoji: '🇮🇩', name: 'Indonesia', keywords: ['indonesia'] },
  { emoji: '🇪🇬', name: 'Egypt', keywords: ['egypt'] },
  { emoji: '🇳🇿', name: 'New Zealand', keywords: ['nz'] },
  { emoji: '🇸🇬', name: 'Singapore', keywords: ['singapore'] },
  { emoji: '🇧🇷', name: 'Brazil', keywords: ['brazil'] },
  { emoji: '🇲🇽', name: 'Mexico', keywords: ['mexico'] },
  { emoji: '🏁', name: 'chequered flag', keywords: ['finish line', 'race'] },
  { emoji: '🚩', name: 'triangular flag', keywords: ['red flag', 'milestone', 'target'] },
  { emoji: '🎌', name: 'crossed flags', keywords: ['celebration'] },
  { emoji: '🏴', name: 'black flag', keywords: ['flag'] },
  { emoji: '🏳️', name: 'white flag', keywords: ['peace', 'surrender'] },
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'education',
    name: 'Education & Academic',
    iconName: 'GraduationCap',
    emojis: EDUCATION_EMOJIS,
  },
  {
    id: 'smileys',
    name: 'Smileys & People',
    iconName: 'Smile',
    emojis: SMILEYS_PEOPLE_EMOJIS,
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    iconName: 'Leaf',
    emojis: ANIMALS_NATURE_EMOJIS,
  },
  {
    id: 'food',
    name: 'Food & Drink',
    iconName: 'Coffee',
    emojis: FOOD_DRINK_EMOJIS,
  },
  {
    id: 'activities',
    name: 'Activities',
    iconName: 'Trophy',
    emojis: ACTIVITIES_EMOJIS,
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    iconName: 'Car',
    emojis: TRAVEL_PLACES_EMOJIS,
  },
  {
    id: 'objects',
    name: 'Objects',
    iconName: 'Lightbulb',
    emojis: OBJECTS_EMOJIS,
  },
  {
    id: 'symbols',
    name: 'Symbols',
    iconName: 'Hash',
    emojis: SYMBOLS_EMOJIS,
  },
  {
    id: 'flags',
    name: 'Flags',
    iconName: 'Flag',
    emojis: FLAGS_EMOJIS,
  },
];
