import fs from 'fs';
import path from 'path';

export interface NewMCQ {
  id: string;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  chapter: string;
  topic?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const NEW_PHYSICS_MCQS_BY_CHAPTER: Record<string, NewMCQ[]> = {
  'Physical Quantities and Measurement': [
    {
      id: 'fbise9_phy_1_21',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'Which of the following standard SI prefixes represents the submultiple factor $10^{-9}$?',
      options: {
        A: 'Nano ($\\text{n}$)',
        B: 'Micro ($\\mu$)',
        C: 'Pico ($\\text{p}$)',
        D: 'Femto ($\\text{f}$)',
      },
      correctAnswer: 'A',
      explanation: 'In the International System of Units (SI), the prefix Nano (symbol $\\text{n}$) represents $10^{-9}$. Micro is $10^{-6}$, Pico is $10^{-12}$, and Femto is $10^{-15}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_22',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'Which base SI unit is defined and used for measuring the amount of a substance in physical sciences?',
      options: {
        A: 'Mole ($\\text{mol}$)',
        B: 'Kilogram ($\\text{kg}$)',
        C: 'Candela ($\\text{cd}$)',
        D: 'Ampere ($\\text{A}$)',
      },
      correctAnswer: 'A',
      explanation: 'The mole ($\\text{mol}$) is the fundamental SI base unit used to measure the amount of substance. Kilogram measures mass, candela measures luminous intensity, and ampere measures electric current.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_23',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'A student multiplies two measured lengths: $2.5\\text{ m} \\times 3.42\\text{ m}$. According to the rules of significant figures, the calculated area should be recorded as:',
      options: {
        A: '$8.6\\text{ m}^2$',
        B: '$8.55\\text{ m}^2$',
        C: '$8.550\\text{ m}^2$',
        D: '$9\\text{ m}^2$',
      },
      correctAnswer: 'A',
      explanation: '$2.5 \\times 3.42 = 8.55$. In multiplication, the final result must retain no more significant figures than the measurement with the fewest significant figures ($2.5\\text{ m}$ has 2 significant figures). Rounding $8.55$ to 2 significant figures gives $8.6\\text{ m}^2$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_24',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'An irregular solid stone is immersed into a graduated measuring cylinder filled with water up to the $40\\text{ cm}^3$ mark. The water level rises to $65\\text{ cm}^3$. What is the volume of the stone?',
      options: {
        A: '$25\\text{ cm}^3$',
        B: '$105\\text{ cm}^3$',
        C: '$65\\text{ cm}^3$',
        D: '$40\\text{ cm}^3$',
      },
      correctAnswer: 'A',
      explanation: 'By the displacement method, the volume of the irregular solid equals the volume of water displaced: $V = V_{\\text{final}} - V_{\\text{initial}} = 65\\text{ cm}^3 - 40\\text{ cm}^3 = 25\\text{ cm}^3$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_25',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'Pressure is measured in the derived SI unit Pascal ($\\text{Pa}$). Expressed strictly in fundamental SI base units, $1\\text{ Pa}$ is equivalent to:',
      options: {
        A: '$1\\text{ kg}\\cdot\\text{m}^{-1}\\cdot\\text{s}^{-2}$',
        B: '$1\\text{ kg}\\cdot\\text{m}\\cdot\\text{s}^{-2}$',
        C: '$1\\text{ kg}\\cdot\\text{m}^{2}\\cdot\\text{s}^{-2}$',
        D: '$1\\text{ kg}\\cdot\\text{m}^{-2}\\cdot\\text{s}^{-1}$',
      },
      correctAnswer: 'A',
      explanation: 'Pressure $P = \\frac{F}{A} = \\frac{\\text{Newton}}{\\text{m}^2} = \\frac{\\text{kg}\\cdot\\text{m}\\cdot\\text{s}^{-2}}{\\text{m}^2} = \\text{kg}\\cdot\\text{m}^{-1}\\cdot\\text{s}^{-2}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_1_26',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'How many micrometers ($\\mu\\text{m}$) are contained within a length of $1\\text{ kilometer}$ ($1\\text{ km}$)?',
      options: {
        A: '$10^9\\ \\mu\\text{m}$',
        B: '$10^6\\ \\mu\\text{m}$',
        C: '$10^3\\ \\mu\\text{m}$',
        D: '$10^{12}\\ \\mu\\text{m}$',
      },
      correctAnswer: 'A',
      explanation: '$1\\text{ km} = 10^3\\text{ m}$. Since $1\\ \\mu\\text{m} = 10^{-6}\\text{ m}$, the ratio is $\\frac{10^3\\text{ m}}{10^{-6}\\text{ m}} = 10^9\\ \\mu\\text{m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_27',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'When using a micrometer screw gauge with least count $0.01\\text{ mm}$, a positive zero error of $+0.04\\text{ mm}$ is observed. If the measured diameter reading is $2.85\\text{ mm}$, what is the true corrected diameter?',
      options: {
        A: '$2.81\\text{ mm}$',
        B: '$2.89\\text{ mm}$',
        C: '$2.85\\text{ mm}$',
        D: '$2.80\\text{ mm}$',
      },
      correctAnswer: 'A',
      explanation: 'Corrected Reading = Observed Reading $-$ (Zero Error) = $2.85\\text{ mm} - (+0.04\\text{ mm}) = 2.81\\text{ mm}$. A positive zero error must always be subtracted.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_28',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'Following standard rounding rules in physics, rounding the measurement $73.450\\text{ m}$ to three significant figures gives:',
      options: {
        A: '$73.4\\text{ m}$',
        B: '$73.5\\text{ m}$',
        C: '$73.45\\text{ m}$',
        D: '$73.0\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'When dropping 5 followed by zeros, if the preceding digit is even (here 4 is even), it remains unchanged ($73.4\\text{ m}$).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_29',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'The base SI unit specified for measuring luminous intensity is the:',
      options: {
        A: 'Candela ($\\text{cd}$)',
        B: 'Lumen ($\\text{lm}$)',
        C: 'Lux ($\\text{lx}$)',
        D: 'Watt ($\\text{W}$)',
      },
      correctAnswer: 'A',
      explanation: 'The candela ($\\text{cd}$) is the fundamental SI base unit of luminous intensity. Lumen and lux are derived photometric units.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_30',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      question: 'If a meter rule has a minimum scale graduation of $1\\text{ mm}$, the absolute measurement uncertainty associated with a single scale reading is:',
      options: {
        A: '$\\pm 0.5\\text{ mm}$ ($0.05\\text{ cm}$)',
        B: '$\\pm 1.0\\text{ mm}$',
        C: '$\\pm 0.1\\text{ mm}$',
        D: '$\\pm 0.01\\text{ mm}$',
      },
      correctAnswer: 'A',
      explanation: 'The absolute uncertainty of an analog measuring instrument is half of its smallest scale division (least count). For a $1\\text{ mm}$ division, the absolute uncertainty is $\\pm 0.5\\text{ mm} = 0.05\\text{ cm}$.',
      difficulty: 'medium',
    },
  ],

  'Kinematics': [
    {
      id: 'fbise9_phy_2_21',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'A car covers the first half of a total distance at a constant speed of $40\\text{ km/h}$ and the second half at $60\\text{ km/h}$. The average speed of the car for the entire journey is:',
      options: {
        A: '$48\\text{ km/h}$',
        B: '$50\\text{ km/h}$',
        C: '$52\\text{ km/h}$',
        D: '$45\\text{ km/h}$',
      },
      correctAnswer: 'A',
      explanation: 'When equal distances are covered at speeds $v_1$ and $v_2$, the harmonic mean formula gives average speed: $v_{\\text{avg}} = \\frac{2v_1 v_2}{v_1 + v_2} = \\frac{2(40)(60)}{40 + 60} = \\frac{4800}{100} = 48\\text{ km/h}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_2_22',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'A train moving at an initial velocity of $15\\text{ m/s}$ accelerates uniformly at $2\\text{ m/s}^2$ for a time duration of $10\\text{ s}$. The total distance covered by the train during this time is:',
      options: {
        A: '$250\\text{ m}$',
        B: '$200\\text{ m}$',
        C: '$150\\text{ m}$',
        D: '$300\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Using the 2nd equation of motion: $S = v_i t + \\frac{1}{2}at^2 = 15(10) + \\frac{1}{2}(2)(10)^2 = 150 + 100 = 250\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_23',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'A ball is thrown vertically upward with an initial velocity of $20\\text{ m/s}$ ($g = 10\\text{ m/s}^2$). What is the total time of flight before the ball returns to the thrower\'s hand?',
      options: {
        A: '$4\\text{ s}$',
        B: '$2\\text{ s}$',
        C: '$3\\text{ s}$',
        D: '$5\\text{ s}$',
      },
      correctAnswer: 'A',
      explanation: 'Time to reach top: $t_{\\text{up}} = \\frac{v_i}{g} = \\frac{20}{10} = 2\\text{ s}$. Total time of flight = $2 \\times t_{\\text{up}} = 4\\text{ s}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_24',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'The continuous spinning motion of the Earth around its own geographic axis is categorized as:',
      options: {
        A: 'Rotatory motion',
        B: 'Circular motion',
        C: 'Translatory motion',
        D: 'Vibratory motion',
      },
      correctAnswer: 'A',
      explanation: 'Rotatory motion occurs when a body spins about an internal axis passing through its body. In contrast, circular motion occurs when a body moves along a circular path around an external point.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_25',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'A curved line with increasing slope on a velocity-time graph represents an object undergoing:',
      options: {
        A: 'Non-uniform (increasing) acceleration',
        B: 'Uniform constant acceleration',
        C: 'Constant speed',
        D: 'Uniform deceleration',
      },
      correctAnswer: 'A',
      explanation: 'The slope of a velocity-time graph represents acceleration. A curved upward line indicates that the slope (and thus acceleration) is changing (non-uniform).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_26',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'When a stone is thrown straight upward into the air, at the exact instant it reaches its highest vertical altitude, its vertical velocity is:',
      options: {
        A: '$0\\text{ m/s}$',
        B: '$9.8\\text{ m/s}$',
        C: 'Maximum',
        D: 'Infinite',
      },
      correctAnswer: 'A',
      explanation: 'At maximum height, the body momentarily comes to rest before reversing its direction under gravity, so instantaneous vertical velocity is $0\\text{ m/s}$ (while downward acceleration remains $g$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_27',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'An athlete runs one full lap around a circular athletic track of radius $14\\text{ m}$. What are the total distance traveled and net displacement of the athlete?',
      options: {
        A: 'Distance $= 88\\text{ m}$, Displacement $= 0\\text{ m}$',
        B: 'Distance $= 88\\text{ m}$, Displacement $= 28\\text{ m}$',
        C: 'Distance $= 0\\text{ m}$, Displacement $= 88\\text{ m}$',
        D: 'Distance $= 44\\text{ m}$, Displacement $= 0\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Distance = Circumference $= 2\\pi r = 2 \\times \\frac{22}{7} \\times 14 = 88\\text{ m}$. Because the runner ends at the initial starting position, the net displacement is $0\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_28',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'A vehicle moving at $20\\text{ m/s}$ is brought to a stop by applying brakes that produce a constant deceleration of $4\\text{ m/s}^2$. The minimum stopping distance is:',
      options: {
        A: '$50\\text{ m}$',
        B: '$40\\text{ m}$',
        C: '$80\\text{ m}$',
        D: '$100\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Using the 3rd equation of motion: $2as = v_f^2 - v_i^2 \\Rightarrow 2(-4)s = 0 - (20)^2 \\Rightarrow -8s = -400 \\Rightarrow s = \\frac{400}{8} = 50\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_29',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'The rapid to-and-fro periodic motion of the prongs of a struck tuning fork about its mean equilibrium position is classified as:',
      options: {
        A: 'Vibratory (oscillatory) motion',
        B: 'Rotatory motion',
        C: 'Random motion',
        D: 'Translatory motion',
      },
      correctAnswer: 'A',
      explanation: 'Vibratory or oscillatory motion is the repetitive to-and-fro motion of a body about its mean resting position in equal intervals of time.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_30',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      question: 'In the International System of Units (SI), the unit for rate of change of velocity per unit time is:',
      options: {
        A: '$\\text{m/s}^2$ ($\\text{m}\\cdot\\text{s}^{-2}$)',
        B: '$\\text{m/s}$ ($\\text{m}\\cdot\\text{s}^{-1}$)',
        C: '$\\text{m}\\cdot\\text{s}$',
        D: '$\\text{kg}\\cdot\\text{m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'Acceleration is defined as rate of change of velocity ($a = \\frac{\\Delta v}{\\Delta t}$). Its SI unit is $\\frac{\\text{m/s}}{\\text{s}} = \\text{m/s}^2$ or $\\text{m}\\cdot\\text{s}^{-2}$.',
      difficulty: 'easy',
    },
  ],

  'Dynamics – I': [
    {
      id: 'fbise9_phy_3_21',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'Newton’s First Law of Motion is alternatively referred to as the:',
      options: {
        A: 'Law of Inertia',
        B: 'Law of Conservation of Momentum',
        C: 'Law of Gravitation',
        D: 'Law of Action and Reaction',
      },
      correctAnswer: 'A',
      explanation: 'Because Newton’s First Law describes the inherent property of matter to resist any change in its state of rest or uniform motion, it is known as the Law of Inertia.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_22',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'According to Newton’s Third Law of Motion, action and reaction forces do NOT cancel each other out because they:',
      options: {
        A: 'Act on two different interacting bodies',
        B: 'Act along different angles',
        C: 'Have unequal magnitudes',
        D: 'Act at different moments in time',
      },
      correctAnswer: 'A',
      explanation: 'Action and reaction are equal in magnitude and opposite in direction, but they act on two different interacting bodies simultaneously, so they never produce equilibrium on a single body.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_23',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'A person of mass $60\\text{ kg}$ stands on a spring balance inside an elevator that is accelerating upwards at $2\\text{ m/s}^2$ ($g = 10\\text{ m/s}^2$). The apparent weight registered by the scale is:',
      options: {
        A: '$720\\text{ N}$',
        B: '$600\\text{ N}$',
        C: '$480\\text{ N}$',
        D: '$800\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'For an upward accelerating elevator: Apparent Weight $R = m(g + a) = 60(10 + 2) = 60 \\times 12 = 720\\text{ N}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_3_24',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'If the elevator carrying the $60\\text{ kg}$ person accelerates downwards at $3\\text{ m/s}^2$ ($g = 10\\text{ m/s}^2$), what is the apparent weight reading?',
      options: {
        A: '$420\\text{ N}$',
        B: '$600\\text{ N}$',
        C: '$780\\text{ N}$',
        D: '$180\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'For a downward accelerating elevator: Apparent Weight $R = m(g - a) = 60(10 - 3) = 60 \\times 7 = 420\\text{ N}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_3_25',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'In an Atwood machine, two masses $m_1 = 6\\text{ kg}$ and $m_2 = 4\\text{ kg}$ hang vertically over a frictionless pulley ($g = 10\\text{ m/s}^2$). What is the tension ($T$) in the connecting string?',
      options: {
        A: '$48\\text{ N}$',
        B: '$24\\text{ N}$',
        C: '$50\\text{ N}$',
        D: '$100\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'Tension in Atwood machine when both move vertically: $T = \\frac{2m_1 m_2}{m_1 + m_2}g = \\frac{2(6)(4)}{6 + 4}(10) = \\frac{48}{10} \\times 10 = 48\\text{ N}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_3_26',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'When a horse pulls a heavy cart along a level road, the forward reaction force that propels the entire horse-cart system forward is exerted by:',
      options: {
        A: 'The ground pushing forward on the horse\'s hooves',
        B: 'The cart pulling back on the horse',
        C: 'The horse pulling on the cart reins',
        D: 'The weight of the horse pushing into the ground',
      },
      correctAnswer: 'A',
      explanation: 'By Newton\'s Third Law, the horse pushes backward on the ground; in reaction, the ground exerts an equal and opposite forward force on the horse\'s hooves, moving the system forward.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_27',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'A body has a mass of $10\\text{ kg}$. If its weight on the surface of Jupiter is measured to be $250\\text{ N}$, what is the gravitational acceleration ($g$) on Jupiter?',
      options: {
        A: '$25\\text{ N/kg}$ ($25\\text{ m/s}^2$)',
        B: '$2500\\text{ N/kg}$',
        C: '$2.5\\text{ N/kg}$',
        D: '$9.8\\text{ N/kg}$',
      },
      correctAnswer: 'A',
      explanation: 'Since $W = mg$, gravitational acceleration $g = \\frac{W}{m} = \\frac{250\\text{ N}}{10\\text{ kg}} = 25\\text{ N/kg} = 25\\text{ m/s}^2$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_28',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'When a dusty carpet is vigorously beaten with a stick, dust particles separate and fall off primarily due to:',
      options: {
        A: 'Inertia of rest of the dust particles',
        B: 'Gravitational repulsion',
        C: 'Inertia of motion of the dust particles',
        D: 'Centripetal forces acting on the carpet',
      },
      correctAnswer: 'A',
      explanation: 'When the carpet is struck, the carpet fibers move suddenly, but the dust particles tend to remain at rest due to inertia of rest, causing them to detach.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_29',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'When a car cruises along a straight horizontal highway at a constant velocity of $80\\text{ km/h}$, the resultant net unbalanced force acting on the car is:',
      options: {
        A: '$0\\text{ N}$',
        B: '$80\\text{ N}$',
        C: 'Equal to the driving force of the engine',
        D: 'Equal to the weight of the car',
      },
      correctAnswer: 'A',
      explanation: 'Constant velocity implies zero acceleration ($a = 0$). By Newton’s Second Law ($F_{\\text{net}} = ma$), the net resultant force acting on the car is exactly $0\\text{ N}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_30',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      question: 'A rifle recoils backward when fired with a significantly smaller velocity than that of the escaping forward bullet because:',
      options: {
        A: 'The rifle has a substantially greater mass than the bullet',
        B: 'The rifle experiences a smaller force than the bullet',
        C: 'The bullet has zero momentum',
        D: 'Friction completely stops the rifle',
      },
      correctAnswer: 'A',
      explanation: 'Both bullet and rifle experience equal and opposite momentum changes. Because $a = \\frac{F}{m}$ and $v = \\frac{p}{m}$, the much larger mass of the rifle results in a much smaller recoil velocity.',
      difficulty: 'medium',
    },
  ],

  'Dynamics – II': [
    {
      id: 'fbise9_phy_4_21',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'A constant force of $50\\text{ N}$ acts on a body for a time interval of $0.2\\text{ s}$. The impulse (change in momentum) imparted to the body is:',
      options: {
        A: '$10\\text{ N}\\cdot\\text{s}$ ($10\\text{ kg}\\cdot\\text{m/s}$)',
        B: '$250\\text{ N}\\cdot\\text{s}$',
        C: '$50.2\\text{ N}\\cdot\\text{s}$',
        D: '$5\\text{ N}\\cdot\\text{s}$',
      },
      correctAnswer: 'A',
      explanation: 'Impulse $I = \\Delta p = F \\times \\Delta t = 50\\text{ N} \\times 0.2\\text{ s} = 10\\text{ N}\\cdot\\text{s} = 10\\text{ kg}\\cdot\\text{m/s}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_22',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'In an isolated physical system consisting of two interacting bodies, the total linear momentum is strictly conserved provided that:',
      options: {
        A: 'No external unbalanced force acts on the system',
        B: 'Both bodies travel at supersonic speeds',
        C: 'Mechanical friction is infinitely large',
        D: 'The masses of both colliding bodies are strictly identical',
      },
      correctAnswer: 'A',
      explanation: 'The Law of Conservation of Momentum explicitly states that the total linear momentum of an isolated system remains constant provided no external net force acts upon it.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_23',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'The centripetal acceleration ($a_c$) of an object moving with uniform linear speed $v$ in a circle of radius $r$ is given by:',
      options: {
        A: '$a_c = \\frac{v^2}{r}$',
        B: '$a_c = \\frac{v}{r^2}$',
        C: '$a_c = v^2 r$',
        D: '$a_c = \\frac{r}{v^2}$',
      },
      correctAnswer: 'A',
      explanation: 'Centripetal acceleration is directed toward the center of the circular path and is mathematically given by $a_c = \\frac{v^2}{r}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_24',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'When an airplane banks into a coordinated turn during flight, the necessary centripetal force for the circular path is provided by the:',
      options: {
        A: 'Horizontal component of the wings\' aerodynamic lift force',
        B: 'Vertical gravitational weight of the aircraft fuselage',
        C: 'Rear propulsion thrust from the jet engines',
        D: 'Downward drag produced by the tail rudder',
      },
      correctAnswer: 'A',
      explanation: 'When an aircraft banks at an angle $\\theta$, the aerodynamic lift force tilts, and its horizontal component ($L\\sin\\theta$) supplies the centripetal force required to execute the turn.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_25',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'For any two contacting surfaces, the coefficient of kinetic friction ($\\mu_k$) is generally:',
      options: {
        A: 'Less than the coefficient of static friction ($\\mu_s$)',
        B: 'Greater than the coefficient of static friction ($\\mu_s$)',
        C: 'Equal to the coefficient of static friction ($\\mu_s$)',
        D: 'Always equal to zero',
      },
      correctAnswer: 'A',
      explanation: 'Once relative motion begins, the microscopic surface irregularities do not interlock as deeply, so $\\mu_k < \\mu_s$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_26',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'Why are the outer edges of curved railway tracks or expressway curves banked (tilted at an incline angle)?',
      options: {
        A: 'To provide the necessary centripetal force through the normal reaction component and prevent derailment or skidding',
        B: 'To reduce the total gravitational weight of the moving vehicle',
        C: 'To increase the air resistance acting on the vehicles',
        D: 'To allow rainwater drainage into the inner ditch only',
      },
      correctAnswer: 'A',
      explanation: 'Banking curves creates a horizontal component of the normal contact reaction force ($N\\sin\\theta$) that supplies centripetal force without relying solely on friction.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_27',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'In the spin dryer of a washing machine, water is spun out of wet clothes through wall perforations because:',
      options: {
        A: 'The adhesion force is insufficient to provide the necessary centripetal force to keep droplets in a circular path',
        B: 'The centrifugal force pushes the clothes inward',
        C: 'Gravity pulls water droplets radially outwards',
        D: 'Air pressure inside the drum drops to zero',
      },
      correctAnswer: 'A',
      explanation: 'At high rotational speeds, the adhesive force holding water to clothes cannot provide the large centripetal force required to maintain circular motion, so water flies off tangentially through holes.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_28',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'Which of the following mechanical methods is widely employed in machinery to substitute high sliding friction with much lower rolling friction?',
      options: {
        A: 'Installing ball bearings or roller bearings between rotating axles',
        B: 'Roughening the metal contact faces with coarse sandpaper',
        C: 'Applying chalk powder to the metal bearings',
        D: 'Tightening the clamp bolts to increase normal pressure',
      },
      correctAnswer: 'A',
      explanation: 'Ball bearings and roller bearings convert sliding friction into rolling friction, significantly reducing frictional energy dissipation and wear in rotating machine parts.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_29',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'If two identical balls of equal mass $m$ travel toward each other along a straight line with identical speeds $v$, the total linear momentum of the two-ball system is:',
      options: {
        A: '$0\\text{ kg}\\cdot\\text{m/s}$',
        B: '$2mv$',
        C: '$mv$',
        D: '$-2mv$',
      },
      correctAnswer: 'A',
      explanation: 'Momentum is a vector quantity: $\\vec{p}_{\\text{total}} = m v + m(-v) = 0\\text{ kg}\\cdot\\text{m/s}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_30',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      question: 'High-speed trains, sports cars, and airplanes are designed with tapered "streamlined" shapes primarily to:',
      options: {
        A: 'Minimize aerodynamic air resistance (fluid friction)',
        B: 'Increase the normal contact force with the ground',
        C: 'Prevent the engine from overheating',
        D: 'Increase rolling friction between wheels and track',
      },
      correctAnswer: 'A',
      explanation: 'Streamlining reduces turbulent airflow and eddy formation, thereby minimizing aerodynamic drag and fluid friction against the moving vehicle.',
      difficulty: 'easy',
    },
  ],

  'Pressure and Deformation in Solids': [
    {
      id: 'fbise9_phy_5_21',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'In a hydraulic garage lift, an effort force of $50\\text{ N}$ applied to a small piston of cross-sectional area $0.01\\text{ m}^2$ can support a load on a large piston of area $0.2\\text{ m}^2$ up to:',
      options: {
        A: '$1000\\text{ N}$',
        B: '$500\\text{ N}$',
        C: '$250\\text{ N}$',
        D: '$2000\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'By Pascal’s Principle: $\\frac{F_1}{A_1} = \\frac{F_2}{A_2} \\Rightarrow F_2 = F_1 \\times \\frac{A_2}{A_1} = 50 \\times \\frac{0.2}{0.01} = 50 \\times 20 = 1000\\text{ N}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_22',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'What is the liquid gauge pressure at a depth of $5\\text{ m}$ in a freshwater pool? (Density of water $= 1000\\text{ kg/m}^3$, $g = 10\\text{ m/s}^2$):',
      options: {
        A: '$50,000\\text{ Pa}$ ($50\\text{ kPa}$)',
        B: '$5,000\\text{ Pa}$',
        C: '$500\\text{ Pa}$',
        D: '$150,000\\text{ Pa}$',
      },
      correctAnswer: 'A',
      explanation: 'Liquid pressure $P = \\rho gh = 1000\\text{ kg/m}^3 \\times 10\\text{ m/s}^2 \\times 5\\text{ m} = 50,000\\text{ Pa} = 50\\text{ kPa}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_23',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'A helical spring extends by $0.04\\text{ m}$ when a $2\\text{ kg}$ weight is suspended from it ($g = 10\\text{ m/s}^2$). What is the spring constant ($k$)?',
      options: {
        A: '$500\\text{ N/m}$',
        B: '$50\\text{ N/m}$',
        C: '$200\\text{ N/m}$',
        D: '$800\\text{ N/m}$',
      },
      correctAnswer: 'A',
      explanation: 'By Hooke’s Law: $F = kx \\Rightarrow k = \\frac{F}{x} = \\frac{mg}{x} = \\frac{2 \\times 10}{0.04} = \\frac{20}{0.04} = 500\\text{ N/m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_24',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'If the cross-sectional tube diameter of a Torricellian mercury barometer is doubled, the equilibrium vertical height of the mercury column supporting standard atmospheric pressure will:',
      options: {
        A: 'Remain unchanged ($760\\text{ mm}$)',
        B: 'Be doubled ($1520\\text{ mm}$)',
        C: 'Be halved ($380\\text{ mm}$)',
        D: 'Drop to zero',
      },
      correctAnswer: 'A',
      explanation: 'Liquid pressure depends solely on vertical depth and density ($P = \\rho gh$), independent of cross-sectional area or tube diameter.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_25',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'Young’s modulus ($Y$) of a wire having initial length $L$, cross-sectional area $A$, stretched by an extension $\\Delta L$ under tensile load $F$, is defined as:',
      options: {
        A: '$Y = \\frac{F \\times L}{A \\times \\Delta L}$',
        B: '$Y = \\frac{F \\times \\Delta L}{A \\times L}$',
        C: '$Y = \\frac{A \\times \\Delta L}{F \\times L}$',
        D: '$Y = \\frac{F \\times A}{L \\times \\Delta L}$',
      },
      correctAnswer: 'A',
      explanation: '$Y = \\frac{\\text{Tensile Stress}}{\\text{Tensile Strain}} = \\frac{F/A}{\\Delta L / L} = \\frac{F \\times L}{A \\times \\Delta L}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_26',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'According to the Law of Flotation, a solid object of density $\\rho_{\\text{obj}}$ will sink when placed into a liquid of density $\\rho_{\\text{liq}}$ whenever:',
      options: {
        A: '$\\rho_{\\text{obj}} > \\rho_{\\text{liq}}$',
        B: '$\\rho_{\\text{obj}} < \\rho_{\\text{liq}}$',
        C: '$\\rho_{\\text{obj}} = \\rho_{\\text{liq}}$',
        D: '$\\rho_{\\text{obj}} = 0$',
      },
      correctAnswer: 'A',
      explanation: 'An object sinks if its weight exceeds the maximum buoyant upthrust force of the liquid, which occurs when its average density is greater than the density of the liquid.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_27',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'Drinking through a beverage straw works because sucking removes air from inside the straw, creating a low-pressure region so that:',
      options: {
        A: 'External atmospheric pressure pushes the liquid up into the straw',
        B: 'Surface tension pulls the liquid up',
        C: 'Gravity forces the drink upwards',
        D: 'The density of the liquid decreases to zero',
      },
      correctAnswer: 'A',
      explanation: 'Sucking reduces pressure inside the straw. The higher atmospheric pressure acting on the open surface of the liquid forces it up into the straw.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_28',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'When a deforming stretching force applied to a solid wire exceeds its elastic limit, the wire:',
      options: {
        A: 'Undergoes permanent (plastic) deformation and does not recover its original shape',
        B: 'Instantly snaps without any extension',
        C: 'Regains its original length perfectly',
        D: 'Becomes a liquid',
      },
      correctAnswer: 'A',
      explanation: 'Beyond the elastic limit, a material enters the plastic region where deforming forces produce permanent irreversible deformation.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_29',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'A hydrometer is a specialized scientific instrument whose working principle is directly based on the Law of Flotation, used specifically to determine:',
      options: {
        A: 'The relative density (specific gravity) of liquids',
        B: 'The atmospheric air pressure at high altitudes',
        C: 'The tensile breaking stress of solid steel wires',
        D: 'The rate of heat transfer through solid metals',
      },
      correctAnswer: 'A',
      explanation: 'A hydrometer floats deeper in less dense liquids and higher in denser liquids, measuring the specific gravity (relative density) of liquids based on the Law of Flotation.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_30',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      question: 'A sudden, steep drop in the atmospheric pressure reading on a laboratory barometer is a standard meteorological indication of:',
      options: {
        A: 'An approaching intense storm or gale',
        B: 'Prolonged dry and sunny weather',
        C: 'An immediate drop in Earth\'s gravity',
        D: 'Freezing snowfall at sea level',
      },
      correctAnswer: 'A',
      explanation: 'A rapid fall in atmospheric pressure indicates the rapid arrival of a low-pressure weather system, which typically brings storms, high winds, and precipitation.',
      difficulty: 'medium',
    },
  ],

  'Work and Energy': [
    {
      id: 'fbise9_phy_6_21',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'A porter carries a heavy bag of mass $20\\text{ kg}$ on his head while walking horizontally across a flat station platform for $50\\text{ m}$. The work done by the gravitational force on the bag is:',
      options: {
        A: '$0\\text{ J}$',
        B: '$10,000\\text{ J}$',
        C: '$1,000\\text{ J}$',
        D: '$500\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: 'Work $W = F s \\cos\\theta$. The force of gravity acts vertically downward while displacement is horizontal ($\\theta = 90^\\circ$). Since $\\cos 90^\\circ = 0$, $W = 0\\text{ J}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_22',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'Power is defined as the rate of doing work ($P = \\frac{W}{t}$). The SI derived unit Watt ($\\text{W}$) is equivalent to:',
      options: {
        A: '$1\\text{ Joule per second}$ ($1\\text{ J/s}$)',
        B: '$1\\text{ Joule per meter}$ ($1\\text{ J/m}$)',
        C: '$1\\text{ Newton per second}$ ($1\\text{ N/s}$)',
        D: '$1\\text{ Newton}\\cdot\\text{meter}$',
      },
      correctAnswer: 'A',
      explanation: '$1\\text{ Watt}$ is defined as the power consumed or work performed at the rate of $1\\text{ Joule per second}$ ($1\\text{ W} = 1\\text{ J/s}$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_23',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'A cricket ball of mass $0.2\\text{ kg}$ is bowled with a velocity of $30\\text{ m/s}$. The kinetic energy of the cricket ball is:',
      options: {
        A: '$90\\text{ J}$',
        B: '$180\\text{ J}$',
        C: '$6\\text{ J}$',
        D: '$60\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: '$E_k = \\frac{1}{2} m v^2 = \\frac{1}{2}(0.2)(30)^2 = 0.1 \\times 900 = 90\\text{ J}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_24',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'In a hydroelectric power station dam, the primary sequence of energy transformations that generates electricity is:',
      options: {
        A: 'Gravitational Potential Energy $\\rightarrow$ Kinetic Energy $\\rightarrow$ Electrical Energy',
        B: 'Thermal Energy $\\rightarrow$ Kinetic Energy $\\rightarrow$ Electrical Energy',
        C: 'Chemical Energy $\\rightarrow$ Potential Energy $\\rightarrow$ Electrical Energy',
        D: 'Nuclear Energy $\\rightarrow$ Thermal Energy $\\rightarrow$ Electrical Energy',
      },
      correctAnswer: 'A',
      explanation: 'Water stored at height in the dam possesses gravitational potential energy, which converts to kinetic energy as it flows through penstocks, driving turbines that turn electric generators.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_25',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'An electric water heater is rated at $2000\\text{ W}$ ($2\\text{ kW}$). How much electrical energy in kilowatt-hours ($\\text{kWh}$) does it consume when operated for $2\\text{ hours}$?',
      options: {
        A: '$4\\text{ kWh}$',
        B: '$2\\text{ kWh}$',
        C: '$1\\text{ kWh}$',
        D: '$4000\\text{ kWh}$',
      },
      correctAnswer: 'A',
      explanation: 'Energy ($\\text{kWh}$) = Power ($\\text{kW}$) $\\times$ Time ($\\text{hours}$) = $2\\text{ kW} \\times 2\\text{ h} = 4\\text{ kWh}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_26',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'The immense radiant heat and light energy continuously emitted by the Sun is produced primarily by the nuclear reaction of:',
      options: {
        A: 'Nuclear Fusion of hydrogen nuclei into helium',
        B: 'Nuclear Fission of heavy uranium nuclei',
        C: 'Chemical combustion of methane gas',
        D: 'Radioactive alpha decay of carbon isotopes',
      },
      correctAnswer: 'A',
      explanation: 'In the Sun\'s core, hydrogen nuclei fuse together under extreme temperature and pressure to form helium nuclei, releasing massive quantities of energy according to $E = \\Delta mc^2$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_27',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'Fossil fuels such as coal, crude oil, and natural gas are categorized as non-renewable energy resources because:',
      options: {
        A: 'They require millions of years to form and cannot be replaced once depleted',
        B: 'They cannot be burned for energy',
        C: 'They do not contain stored chemical energy',
        D: 'They produce zero carbon emissions',
      },
      correctAnswer: 'A',
      explanation: 'Non-renewable resources are finite geological deposits formed over millions of years and cannot be regenerated within a human lifespan.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_28',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'For an ideal oscillating simple pendulum in a vacuum (ignoring air friction), the total mechanical energy ($E_k + E_p$):',
      options: {
        A: 'Remains strictly constant at every point during the swing',
        B: 'Is zero at the extreme positions',
        C: 'Is maximum at the mean position and zero at extremes',
        D: 'Continually increases over time',
      },
      correctAnswer: 'A',
      explanation: 'By the Law of Conservation of Mechanical Energy, potential energy converts into kinetic energy and vice versa such that total mechanical energy ($E_k + E_p$) is conserved.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_29',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'Geothermal energy is a renewable energy resource that harnesses thermal heat extracted from:',
      options: {
        A: 'Hot rocks, steam, and magma deep within the Earth\'s crust',
        B: 'Ocean surface waves',
        C: 'Atmospheric winds near mountain ranges',
        D: 'Radioactive nuclear waste dumps',
      },
      correctAnswer: 'A',
      explanation: 'Geothermal energy utilizes natural heat from deep within the Earth\'s crust to produce steam and drive power turbines.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_30',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      question: 'If a car engine exerts a constant driving force $F$ propelling the vehicle at a steady velocity $v$, the instantaneous mechanical power output is given by:',
      options: {
        A: '$P = F \\times v$',
        B: '$P = \\frac{F}{v}$',
        C: '$P = \\frac{v}{F}$',
        D: '$P = F \\times v^2$',
      },
      correctAnswer: 'A',
      explanation: '$P = \\frac{W}{t} = \\frac{F \\times s}{t} = F \\times \\left(\\frac{s}{t}\\right) = F \\times v$.',
      difficulty: 'medium',
    },
  ],

  'Density and Temperature': [
    {
      id: 'fbise9_phy_7_21',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'Specific Latent Heat of Fusion ($L_f$) is defined as the heat energy required to change unit mass of a substance from solid to liquid without a change in temperature. Its SI unit is:',
      options: {
        A: '$\\text{J/kg}$ ($\\text{J}\\cdot\\text{kg}^{-1}$)',
        B: '$\\text{J}\\cdot\\text{kg}^{-1}\\cdot\\text{K}^{-1}$',
        C: '$\\text{J/K}$',
        D: '$\\text{Watt/kg}$',
      },
      correctAnswer: 'A',
      explanation: '$L_f = \\frac{Q_f}{m}$. Since heat is measured in Joules and mass in kilograms, its SI unit is $\\text{J/kg}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_22',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'Pure water reaches its maximum density of $1000\\text{ kg/m}^3$ at a temperature of:',
      options: {
        A: '$4^\\circ\\text{C}$ ($277\\text{ K}$)',
        B: '$0^\\circ\\text{C}$ ($273\\text{ K}$)',
        C: '$100^\\circ\\text{C}$ ($373\\text{ K}$)',
        D: '$-4^\\circ\\text{C}$',
      },
      correctAnswer: 'A',
      explanation: 'Due to anomalous expansion, water contracts when heated from $0^\\circ\\text{C}$ to $4^\\circ\\text{C}$, reaching its minimum volume and maximum density at $4^\\circ\\text{C}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_23',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'A clinical thermometer features a narrow constriction in the glass capillary tube just above the bulb in order to:',
      options: {
        A: 'Prevent the mercury thread from falling back into the bulb before reading',
        B: 'Increase the boiling point of mercury',
        C: 'Make the thermometer react slower',
        D: 'Allow the mercury to evaporate easily',
      },
      correctAnswer: 'A',
      explanation: 'The constriction allows expanding mercury to pass when heated, but when removed from the patient\'s body, the mercury breaks at the constriction, preserving the reading.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_24',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'The exact formula used to convert a temperature from the Celsius scale ($C$) to the Fahrenheit scale ($F$) is:',
      options: {
        A: '$F = 1.8 C + 32$',
        B: '$F = \\frac{5}{9}(C - 32)$',
        C: '$F = C + 273$',
        D: '$F = 1.8(C + 32)$',
      },
      correctAnswer: 'A',
      explanation: 'The conversion formula is $F = \\frac{9}{5}C + 32 = 1.8C + 32$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_25',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'On the standard Celsius scale, the lower fixed point ($0^\\circ\\text{C}$) and upper fixed point ($100^\\circ\\text{C}$) are defined respectively by the:',
      options: {
        A: 'Melting point of pure ice and boiling point of pure water at standard atmospheric pressure',
        B: 'Freezing point of mercury and boiling point of alcohol',
        C: 'Absolute zero and human body temperature',
        D: 'Triple point of nitrogen and boiling point of water',
      },
      correctAnswer: 'A',
      explanation: 'The Celsius scale is fixed between the melting point of pure ice ($0^\\circ\\text{C}$) and the boiling point of pure water ($100^\\circ\\text{C}$) at $1\\text{ atm}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_26',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'The change in volume ($\\Delta V$) of a solid or liquid of initial volume $V_0$ when heated through temperature change $\\Delta T$ is given by the formula:',
      options: {
        A: '$\\Delta V = \\beta V_0 \\Delta T$',
        B: '$\\Delta V = \\alpha V_0 \\Delta T$',
        C: '$\\Delta V = \\frac{V_0}{\\beta \\Delta T}$',
        D: '$\\Delta V = 3\\beta V_0 \\Delta T$',
      },
      correctAnswer: 'A',
      explanation: 'Volumetric thermal expansion is given by $\\Delta V = \\beta V_0 \\Delta T$, where $\\beta$ is the coefficient of volume expansion (and $\\beta = 3\\alpha$).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_27',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'The phase transformation in which a solid changes directly into gas without transitioning through an intermediate liquid state is called:',
      options: {
        A: 'Sublimation',
        B: 'Vaporization',
        C: 'Condensation',
        D: 'Fusion',
      },
      correctAnswer: 'A',
      explanation: 'Sublimation is the direct transition of a substance from solid phase to vapor phase (e.g., dry ice, camphor, iodine).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_28',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'How much heat energy ($Q$) is needed to raise the temperature of a $0.5\\text{ kg}$ iron block from $20^\\circ\\text{C}$ to $60^\\circ\\text{C}$? (Specific heat of iron $c = 450\\text{ J}\\cdot\\text{kg}^{-1}\\cdot\\text{K}^{-1}$):',
      options: {
        A: '$9,000\\text{ J}$',
        B: '$18,000\\text{ J}$',
        C: '$4,500\\text{ J}$',
        D: '$90,000\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: '$Q = mc\\Delta T = 0.5\\text{ kg} \\times 450\\text{ J}\\cdot\\text{kg}^{-1}\\cdot\\text{K}^{-1} \\times (60 - 20)^\\circ\\text{C} = 0.5 \\times 450 \\times 40 = 9000\\text{ J}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_29',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'Alcohol is preferred over mercury in thermometers designed for meteorological stations in polar arctic regions because:',
      options: {
        A: 'Alcohol has a much lower freezing point ($-114^\\circ\\text{C}$) than mercury ($-39^\\circ\\text{C}$)',
        B: 'Alcohol has a higher boiling point than mercury',
        C: 'Alcohol does not expand when heated',
        D: 'Alcohol is opaque and silvery',
      },
      correctAnswer: 'A',
      explanation: 'Mercury freezes at $-39^\\circ\\text{C}$, rendering it useless in severe arctic climates, whereas alcohol remains liquid down to $-114^\\circ\\text{C}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_30',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      question: 'Equal volumes ($100\\text{ cm}^3$ each) of two miscible liquids with densities $0.8\\text{ g/cm}^3$ and $1.2\\text{ g/cm}^3$ are mixed thoroughly. The density of the mixture is:',
      options: {
        A: '$1.0\\text{ g/cm}^3$',
        B: '$2.0\\text{ g/cm}^3$',
        C: '$0.96\\text{ g/cm}^3$',
        D: '$1.1\\text{ g/cm}^3$',
      },
      correctAnswer: 'A',
      explanation: 'Mass $m_1 = 0.8 \\times 100 = 80\\text{ g}$, $m_2 = 1.2 \\times 100 = 120\\text{ g}$. Total volume = $200\\text{ cm}^3$. Density = $\\frac{80 + 120}{200} = \\frac{200}{200} = 1.0\\text{ g/cm}^3$.',
      difficulty: 'medium',
    },
  ],

  'Magnetism': [
    {
      id: 'fbise9_phy_8_21',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'The fundamental law of magnetic poles states that:',
      options: {
        A: 'Like magnetic poles repel each other, and unlike magnetic poles attract each other',
        B: 'Like magnetic poles attract each other',
        C: 'All magnetic poles attract unmagnetized aluminum',
        D: 'North poles attract North poles with double force',
      },
      correctAnswer: 'A',
      explanation: 'Fundamental law of magnetism: Like poles (N-N, S-S) repel, whereas unlike poles (N-S) attract.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_22',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'The only definitive and sure experimental test to verify whether a metallic bar is permanently magnetized is:',
      options: {
        A: 'Repulsion by a known magnetic pole of a compass needle',
        B: 'Attraction to an iron nail',
        C: 'Attraction to a steel rod',
        D: 'Conducting electricity through the bar',
      },
      correctAnswer: 'A',
      explanation: 'Unmagnetized magnetic materials (like soft iron) are attracted by both poles of a magnet. Only a magnetized body will experience repulsion when presented with a like pole.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_23',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'Geographically, near the Earth’s northern geographic pole lies the Earth’s:',
      options: {
        A: 'Magnetic South Pole',
        B: 'Magnetic North Pole',
        C: 'Magnetic Equator',
        D: 'Zero-field axis',
      },
      correctAnswer: 'A',
      explanation: 'Because unlike poles attract, the North-seeking pole of a compass points north towards the Earth’s geographic North pole, meaning a magnetic South pole is situated there.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_24',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'The vertical angle that the total Earth\'s magnetic field vector makes with the horizontal plane at any location on Earth is termed the:',
      options: {
        A: 'Angle of Dip (Magnetic Inclination)',
        B: 'Angle of Declination',
        C: 'Magnetic Latitude',
        D: 'Critical Angle',
      },
      correctAnswer: 'A',
      explanation: 'The Angle of Dip (or Magnetic Inclination) is the angle between the Earth’s magnetic field lines and the horizontal surface.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_25',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'Steel is chosen over soft iron for manufacturing permanent bar magnets because steel exhibits:',
      options: {
        A: 'High coercivity (strong resistance to demagnetization)',
        B: 'Zero magnetic retentivity',
        C: 'Ease of demagnetization with gentle tapping',
        D: 'Higher electrical conductivity',
      },
      correctAnswer: 'A',
      explanation: 'Steel has high magnetic retentivity and high coercivity, making it difficult to magnetize but once magnetized, it retains its magnetism permanently.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_26',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'At the exact geometric center of a flat circular current-carrying coil, the magnetic field lines are:',
      options: {
        A: 'Straight and perpendicular to the plane of the coil',
        B: 'Concentric circles parallel to the coil plane',
        C: 'Zero in magnitude',
        D: 'Spiral curves pointing outward',
      },
      correctAnswer: 'A',
      explanation: 'At the center of a circular current loop, the magnetic field contributions from all wire segments combine into straight, parallel field lines perpendicular to the loop’s plane.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_27',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'The critical temperature above which a ferromagnetic substance loses its permanent ferromagnetism and behaves as a paramagnetic material is called the:',
      options: {
        A: 'Curie Temperature',
        B: 'Absolute Zero',
        C: 'Inversion Temperature',
        D: 'Kelvin Point',
      },
      correctAnswer: 'A',
      explanation: 'At the Curie temperature, thermal kinetic agitation destroys the alignment of magnetic domains in ferromagnetic substances (e.g., $770^\\circ\\text{C}$ for iron).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_28',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'When using the Right-Hand Grip Rule for a solenoid, if the curled fingers point in the direction of conventional electric current, the extended thumb points towards the:',
      options: {
        A: 'Magnetic North Pole of the solenoid',
        B: 'Magnetic South Pole of the solenoid',
        C: 'Direction of electron flow',
        D: 'Center of the battery',
      },
      correctAnswer: 'A',
      explanation: 'By the Right-Hand Grip Rule for coils and solenoids, the thumb points in the direction of the internal magnetic field, which is toward the magnetic North pole.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_29',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'The lifting force of an industrial electromagnet used in scrapyards can be effectively increased by:',
      options: {
        A: 'Increasing the electric current and the number of turns in the coil',
        B: 'Decreasing the number of turns of wire',
        C: 'Replacing the soft iron core with a plastic core',
        D: 'Reversing the polarity every second',
      },
      correctAnswer: 'A',
      explanation: 'Magnetic field strength $B \\propto n I$. Increasing the number of turns per unit length ($n$) and current ($I$) directly strengthens the electromagnet.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_30',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      question: 'Materials like copper, bismuth, and water that are feebly repelled by strong magnetic fields are classified as:',
      options: {
        A: 'Diamagnetic materials',
        B: 'Paramagnetic materials',
        C: 'Ferromagnetic materials',
        D: 'Electromagnetic conductors',
      },
      correctAnswer: 'A',
      explanation: 'Diamagnetic substances are weakly repelled by magnets because an applied magnetic field induces a weak opposing magnetic moment in their atomic orbitals.',
      difficulty: 'medium',
    },
  ],

  'Nature of Science and Physics': [
    {
      id: 'fbise9_phy_9_21',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'The renowned 9th-century Muslim polymath Yaqub ibn Ishaq al-Kindi made foundational scientific contributions to the physics of:',
      options: {
        A: 'Geometric optics, acoustics, and the theory of light reflection',
        B: 'Nuclear fission reactors',
        C: 'Quantum electrodynamics',
        D: 'Digital telecommunications',
      },
      correctAnswer: 'A',
      explanation: 'Al-Kindi authored seminal treatises on geometric optics, the rectilinear propagation of light, optical reflections from curved mirrors, and musical acoustics.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_22',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'The specialized branch of physics that investigates the physical properties, evolution, mechanics, and structure of celestial bodies, stars, and galaxies is:',
      options: {
        A: 'Astrophysics',
        B: 'Geophysics',
        C: 'Biophysics',
        D: 'Plasma Physics',
      },
      correctAnswer: 'A',
      explanation: 'Astrophysics applies physical laws to understand celestial objects and phenomena across the cosmos.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_23',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'The branch of physics that investigates the physical, crystalline, electrical, and magnetic properties of solid matter is termed:',
      options: {
        A: 'Solid State Physics (Condensed Matter Physics)',
        B: 'Nuclear Physics',
        C: 'Acoustics',
        D: 'Relativistic Mechanics',
      },
      correctAnswer: 'A',
      explanation: 'Solid State Physics deals with the structural, electronic, and magnetic properties of crystalline solids, which is essential for semiconductor microchips.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_24',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'In the empirical scientific method, a "Scientific Theory" is fundamentally characterized as:',
      options: {
        A: 'A comprehensive, experimentally verified explanation of natural phenomena supported by a vast body of empirical evidence',
        B: 'An unverified wild guess by a researcher',
        C: 'A single isolated measurement reading',
        D: 'A mathematical formula that never requires testing',
      },
      correctAnswer: 'A',
      explanation: 'In science, a theory is a rigorous, widely tested, and verified explanatory framework that unifies and explains a broad range of natural phenomena.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_25',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'In experimental physical measurements, the term "Precision" specifically describes:',
      options: {
        A: 'The closeness of agreement between several repeated measurements of the same quantity under identical conditions',
        B: 'The agreement between a measured value and the true theoretical standard',
        C: 'The total cost of the measuring apparatus',
        D: 'The weight of the measuring scale',
      },
      correctAnswer: 'A',
      explanation: 'Precision refers to repeatability and consistency among repeated measurements, whereas accuracy refers to closeness to the true accepted value.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_26',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'An experimental error arising from careless handling, incorrect technique, or biased visual alignment by the human experimenter is classified as a:',
      options: {
        A: 'Personal error',
        B: 'Systematic zero error of the tool',
        C: 'Unavoidable quantum fluctuation',
        D: 'Environmental cosmic error',
      },
      correctAnswer: 'A',
      explanation: 'Personal errors occur due to human mistakes, inexperience, poor parallax alignment, or improper technique by the individual conducting the experiment.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_27',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'The branch of physics that studies the production, propagation, properties, and technological reception of sound waves and ultrasound is:',
      options: {
        A: 'Acoustics',
        B: 'Optics',
        C: 'Thermodynamics',
        D: 'Fluid Dynamics',
      },
      correctAnswer: 'A',
      explanation: 'Acoustics is the branch of physics focused on the study of all mechanical waves in gases, liquids, and solids, including vibration, sound, ultrasound, and infrasound.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_28',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'When performing experiments in a physics laboratory involving laser beams, what is the most critical personal safety protocol?',
      options: {
        A: 'Wear specialized wavelength-filtered protective laser goggles and never look directly into the beam',
        B: 'Keep the room completely dark without ventilation',
        C: 'Touch the laser aperture with bare hands',
        D: 'Place reflective glass mirrors directly in the beam path',
      },
      correctAnswer: 'A',
      explanation: 'Laser radiation can cause permanent retinal burns; certified wavelength-protective eyewear is required and looking directly into the beam is strictly prohibited.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_29',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'The fundamental branch of classical physics dedicated to the study of light generation, reflection, refraction, lenses, and optical instruments is:',
      options: {
        A: 'Optics',
        B: 'Electrodynamics',
        C: 'Thermodynamics',
        D: 'Cryogenics',
      },
      correctAnswer: 'A',
      explanation: 'Optics is the branch of physics that studies the behavior and properties of light, including its interactions with matter and the construction of optical instruments.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_30',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      question: 'The development of Medical Imaging technologies such as X-ray Radiography, CT Scanners, and MRI demonstrate that:',
      options: {
        A: 'Fundamental physics discoveries provide the foundational principles for advanced healthcare and diagnostic equipment',
        B: 'Physics has no relevance to biological sciences',
        C: 'Modern medicine operates without physical laws',
        D: 'Diagnostic machines are purely chemical devices',
      },
      correctAnswer: 'A',
      explanation: 'Major diagnostic tools (X-rays, CT scanners, MRI, ultrasound, radiotherapy) were directly born from discoveries in electromagnetism, nuclear physics, and acoustics.',
      difficulty: 'easy',
    },
  ],
};
