import fs from 'fs';
import path from 'path';
import { NEW_TEN_MCQS_PER_CHAPTER } from './appendPhysicsTenMore';
import { FBISE_9_QUESTION_BANK } from '../src/lib/fbise9QuestionsBank';
import { validateMCQQuestion, checkQuestionDuplicate, calculateQuestionSimilarity } from '../src/lib/mcqValidator';
import type { StoredMCQ } from '../src/types/questionBank';

export interface NewMCQDefinition {
  id: string;
  chapter: string;
  topic: string;
  chapterNumber: number;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

// 10 Additional MCQs per chapter (Questions 41 to 50 for all 9 chapters = 90 MCQs)
export const NEW_TEN_MCQS_PART2: Record<string, NewMCQDefinition[]> = {
  'Physical Quantities and Measurement': [
    {
      id: 'fbise9_phy_1_41',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'Which component of a micrometer screw gauge ensures that uniform pressure is exerted on the specimen without over-tightening?',
      options: {
        A: 'Ratchet',
        B: 'Thimble',
        C: 'Main sleeve',
        D: 'Anvil lock',
      },
      correctAnswer: 'A',
      explanation: 'The ratchet mechanism slips with a distinct clicking sound when the spindle makes firm contact with the object, ensuring consistent measuring pressure and preventing overtightening or thread damage.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_42',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'When the jaws of a Vernier caliper are brought into contact, the zero mark of the vernier scale lies to the left of the main scale zero mark. The zero error is:',
      options: {
        A: 'Negative, and zero correction must be added to the observed reading',
        B: 'Positive, and zero correction must be added to the observed reading',
        C: 'Negative, and zero correction must be subtracted from the observed reading',
        D: 'Positive, and zero correction must be subtracted from the observed reading',
      },
      correctAnswer: 'A',
      explanation: 'When the vernier zero lies to the left of the main scale zero, the instrument under-reads (negative zero error). The zero correction is therefore positive and must be added to obtain the correct measurement.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_43',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'A student uses a graduated measuring cylinder to determine the volume of an irregular stone. Initial water volume is $36\\text{ cm}^3$, and after immersing the stone, the level rises to $49\\text{ cm}^3$. What is the volume of the stone?',
      options: {
        A: '$13\\text{ cm}^3$',
        B: '$85\\text{ cm}^3$',
        C: '$1764\\text{ cm}^3$',
        D: '$1.36\\text{ cm}^3$',
      },
      correctAnswer: 'A',
      explanation: 'By the liquid displacement method: $\\text{Volume of solid} = V_2 - V_1 = 49\\text{ cm}^3 - 36\\text{ cm}^3 = 13\\text{ cm}^3$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_44',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'A mass measurement is recorded as $45.0\\text{ g}$ (3 significant figures) and volume as $15.00\\text{ cm}^3$ (4 significant figures). The calculated density recorded to the correct number of significant figures is:',
      options: {
        A: '$3.00\\text{ g/cm}^3$',
        B: '$3.0\\text{ g/cm}^3$',
        C: '$3\\text{ g/cm}^3$',
        D: '$3.000\\text{ g/cm}^3$',
      },
      correctAnswer: 'A',
      explanation: 'In multiplication and division, the final answer must retain as many significant figures as the least precise measurement. Here, $45.0\\text{ g}$ has 3 significant figures, so the density $\\rho = 45.0 / 15.00 = 3.00\\text{ g/cm}^3$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_45',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'An electrical power transmission station produces $500\\text{ MW}$ of power. In terms of Gigawatts ($\\text{GW}$), this is equivalent to:',
      options: {
        A: '$0.5\\text{ GW}$',
        B: '$5.0\\text{ GW}$',
        C: '$0.05\\text{ GW}$',
        D: '$50\\text{ GW}$',
      },
      correctAnswer: 'A',
      explanation: '$1\\text{ MW} = 10^6\\text{ W}$ and $1\\text{ GW} = 10^9\\text{ W}$. Therefore, $500\\text{ MW} = 500 \\times 10^6\\text{ W} = 0.5 \\times 10^9\\text{ W} = 0.5\\text{ GW}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_46',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'Expressed strictly in terms of SI base units, the derived unit Joule ($\\text{J}$) is equal to:',
      options: {
        A: '$\\text{kg}\\cdot\\text{m}^2\\cdot\\text{s}^{-2}$',
        B: '$\\text{kg}\\cdot\\text{m}\\cdot\\text{s}^{-2}$',
        C: '$\\text{kg}\\cdot\\text{m}^2\\cdot\\text{s}^{-1}$',
        D: '$\\text{kg}\\cdot\\text{m}^{-1}\\cdot\\text{s}^{-2}$',
      },
      correctAnswer: 'A',
      explanation: '$\\text{Work} = \\text{Force} \\times \\text{Displacement} = (\\text{kg}\\cdot\\text{m}\\cdot\\text{s}^{-2}) \\times \\text{m} = \\text{kg}\\cdot\\text{m}^2\\cdot\\text{s}^{-2}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_1_47',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'Which of the following is exactly equivalent to one litre ($1\\text{ L}$) of volume in standard SI units?',
      options: {
        A: '$1\\text{ dm}^3 = 10^{-3}\\text{ m}^3$',
        B: '$1\\text{ m}^3$',
        C: '$100\\text{ cm}^3$',
        D: '$10^{-6}\\text{ m}^3$',
      },
      correctAnswer: 'A',
      explanation: 'One litre ($1\\text{ L}$) is defined as one cubic decimeter ($1\\text{ dm}^3$), which is equal to $1000\\text{ cm}^3 = 10^{-3}\\text{ m}^3$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_48',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'To avoid parallax error when reading the liquid volume in a graduated measuring cylinder, the observer\'s line of sight must be:',
      options: {
        A: 'Horizontally aligned with the lowest point of the concave meniscus',
        B: 'Tilted from above the liquid surface',
        C: 'Positioned looking upward from below the liquid level',
        D: 'Level with the highest edge of the meniscus boundary',
      },
      correctAnswer: 'A',
      explanation: 'For transparent liquids that wet glass (like water), the eye must be positioned horizontally level with the bottom of the curved concave meniscus to prevent parallax measurement errors.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_49',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'When rounding off a measurement to the correct number of significant figures, if the digit dropped is 5 followed by zeros, the preceding digit is:',
      options: {
        A: 'Increased by 1 if it is odd, and left unchanged if it is even',
        B: 'Always increased by 1 regardless of whether it is odd or even',
        C: 'Always kept unchanged',
        D: 'Decreased by 1 if it is an even integer',
      },
      correctAnswer: 'A',
      explanation: 'Under the standard round-half-to-even rule for significant figures, when the digit to drop is 5 followed by zeros, the preceding digit is rounded to the nearest even number (increased if odd, unchanged if already even).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_50',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'Which of the following pairs contains only derived physical quantities in SI?',
      options: {
        A: 'Pressure and Speed',
        B: 'Mass and Length',
        C: 'Time and Temperature',
        D: 'Electric current and Amount of substance',
      },
      correctAnswer: 'A',
      explanation: 'Pressure (Pascal) and Speed ($\\text{m/s}$) are derived from fundamental base quantities. Mass, length, time, temperature, current, and amount of substance are base quantities.',
      difficulty: 'easy',
    },
  ],
  'Kinematics': [
    {
      id: 'fbise9_phy_2_41',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A vehicle travelling at $25\\text{ m/s}$ applies brakes and comes uniformly to rest in $5\\text{ s}$. The stopping distance covered during braking is:',
      options: {
        A: '$62.5\\text{ m}$',
        B: '$125\\text{ m}$',
        C: '$50\\text{ m}$',
        D: '$31.25\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Using average velocity: $S = \\frac{v_i + v_f}{2} \\times t = \\frac{25 + 0}{2} \\times 5 = 12.5 \\times 5 = 62.5\\text{ m}$. Alternatively, $a = -5\\text{ m/s}^2$ and $S = v_i t + \\frac{1}{2}at^2 = 25(5) - 0.5(5)(25) = 62.5\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_42',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A pebble is dropped freely from the top of a bridge and strikes the water below after $3.0\\text{ s}$ ($g = 9.8\\text{ m/s}^2$). What is the height of the bridge?',
      options: {
        A: '$44.1\\text{ m}$',
        B: '$29.4\\text{ m}$',
        C: '$88.2\\text{ m}$',
        D: '$14.7\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Since initial velocity $v_i = 0$: $h = \\frac{1}{2}gt^2 = \\frac{1}{2}(9.8)(3^2) = 4.9 \\times 9 = 44.1\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_43',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A ball is released from rest from a tall tower and falls freely under gravity ($g = 9.8\\text{ m/s}^2$). What is its velocity after $4.0\\text{ seconds}$ of descent?',
      options: {
        A: '$39.2\\text{ m/s}$',
        B: '$19.6\\text{ m/s}$',
        C: '$78.4\\text{ m/s}$',
        D: '$9.8\\text{ m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'Since initial velocity $v_i = 0$, applying the first equation of motion under gravity: $v_f = v_i + gt = 0 + (9.8\\text{ m/s}^2 \\times 4.0\\text{ s}) = 39.2\\text{ m/s}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_44',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'The to-and-fro repetitive movement of a sewing machine needle about its mean position is an example of:',
      options: {
        A: 'Vibratory (oscillatory) motion',
        B: 'Rotatory motion',
        C: 'Linear translatory motion',
        D: 'Random motion',
      },
      correctAnswer: 'A',
      explanation: 'To-and-fro motion of a body about its fixed mean position is called vibratory or oscillatory motion, as seen in a sewing machine needle, pendulum bob, or tuning fork prong.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_45',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A cyclist travels at a uniform speed of $12\\text{ m/s}$ for $30\\text{ seconds}$, and then speeds up to $18\\text{ m/s}$ for the next $30\\text{ seconds}$. What is the average speed for the total duration?',
      options: {
        A: '$15\\text{ m/s}$',
        B: '$14.4\\text{ m/s}$',
        C: '$16\\text{ m/s}$',
        D: '$13.5\\text{ m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'When equal time intervals are spent at speeds $v_1$ and $v_2$, the average speed is the arithmetic mean: $v_{\\text{avg}} = \\frac{v_1 + v_2}{2} = \\frac{12 + 18}{2} = 15\\text{ m/s}$. Total distance $S = (12 \\times 30) + (18 \\times 30) = 900\\text{ m}$, so $v_{\\text{avg}} = \\frac{900}{60} = 15\\text{ m/s}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_46',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'What physical quantity is directly determined from the gradient (slope) of a distance-time graph?',
      options: {
        A: 'Speed',
        B: 'Acceleration',
        C: 'Force',
        D: 'Momentum',
      },
      correctAnswer: 'A',
      explanation: 'The gradient of a distance-time graph represents the rate of change of distance with respect to time ($\\frac{\\Delta S}{\\Delta t}$), which is defined as speed.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_47',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A projectile is launched vertically upwards with an initial speed $u$ and reaches maximum height $H$. If the launch speed is doubled to $2u$, the new maximum height attained will be:',
      options: {
        A: '$4H$',
        B: '$2H$',
        C: '$8H$',
        D: '$\\sqrt{2}H$',
      },
      correctAnswer: 'A',
      explanation: 'Maximum height $H = \\frac{u^2}{2g}$. Since $H \\propto u^2$, doubling the initial speed ($(2u)^2 = 4u^2$) quadruples the maximum height to $4H$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_48',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A runner completes two full laps around a circular running track of radius $70\\text{ m}$. What is the magnitude of the runner\'s net displacement?',
      options: {
        A: '$0\\text{ m}$',
        B: '$440\\text{ m}$',
        C: '$880\\text{ m}$',
        D: '$140\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Displacement is the shortest directed distance from the starting position to the final position. Since the runner returns to the exact starting point after complete laps, net displacement is $0\\text{ m}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_49',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'On a distance-time graph, a curved line bending upwards with progressively increasing slope indicates that the object is:',
      options: {
        A: 'Accelerating with increasing speed',
        B: 'Decelerating with decreasing speed',
        C: 'Moving at constant uniform velocity',
        D: 'At rest',
      },
      correctAnswer: 'A',
      explanation: 'The slope (gradient) of a distance-time graph equals speed. An upward-bending curve with increasing slope indicates that speed is increasing with time (positive acceleration).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_50',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A cart starts from rest and accelerates uniformly at $2.0\\text{ m/s}^2$. What distance does it cover during the 4th second alone?',
      options: {
        A: '$7.0\\text{ m}$',
        B: '$16.0\\text{ m}$',
        C: '$8.0\\text{ m}$',
        D: '$9.0\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Distance in the $n^{\\text{th}}$ second: $S_{n} = u + \\frac{a}{2}(2n - 1) = 0 + \\frac{2.0}{2}(2(4) - 1) = 1 \\times 7 = 7.0\\text{ m}$. (Alternatively: $S_4 - S_3 = \\frac{1}{2}(2)(4^2) - \\frac{1}{2}(2)(3^2) = 16 - 9 = 7\\text{ m}$).',
      difficulty: 'hard',
    },
  ],
  'Dynamics – I': [
    {
      id: 'fbise9_phy_3_41',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'Two masses $m_1 = 6\\text{ kg}$ and $m_2 = 4\\text{ kg}$ hang vertically from the ends of a light inextensible string over a frictionless pulley (Atwood machine). Taking $g = 10\\text{ m/s}^2$, the acceleration of the system is:',
      options: {
        A: '$2\\text{ m/s}^2$',
        B: '$1\\text{ m/s}^2$',
        C: '$5\\text{ m/s}^2$',
        D: '$10\\text{ m/s}^2$',
      },
      correctAnswer: 'A',
      explanation: '$a = \\frac{m_1 - m_2}{m_1 + m_2}g = \\frac{6 - 4}{6 + 4}(10) = \\frac{2}{10}(10) = 2\\text{ m/s}^2$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_42',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'When a rifle is fired, the backward recoil force experienced by the shooter is an illustration of:',
      options: {
        A: 'Newton\'s Third Law of Motion (Action and Reaction)',
        B: 'Newton\'s First Law of Motion (Law of Inertia)',
        C: 'Law of Universal Gravitation',
        D: 'Principle of uniform velocity',
      },
      correctAnswer: 'A',
      explanation: 'According to Newton\'s Third Law, for every action there is an equal and opposite reaction. The expanding gases exert a forward action force on the bullet, and the bullet exerts an equal and opposite reaction force pushing the rifle backward.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_43',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'A body of mass $5\\text{ kg}$ is suspended at rest by a vertical light string. Taking $g = 9.8\\text{ m/s}^2$, the tension in the string is:',
      options: {
        A: '$49\\text{ N}$',
        B: '$98\\text{ N}$',
        C: '$24.5\\text{ N}$',
        D: '$0\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'Since the body is at rest in vertical equilibrium (acceleration $a = 0$), the upward tension in the string balances the downward weight of the object: $T = W = mg = 5\\text{ kg} \\times 9.8\\text{ m/s}^2 = 49\\text{ N}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_44',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'Passengers sitting in a moving bus are jolted forward when the driver suddenly applies brakes. This phenomenon is explained by:',
      options: {
        A: 'Inertia of motion of the passengers\' upper bodies',
        B: 'Action-reaction pairs of gravitational forces',
        C: 'Centripetal force from the wheels',
        D: 'Conservation of mechanical energy',
      },
      correctAnswer: 'A',
      explanation: 'When the bus brakes suddenly, the lower part of the passengers\' bodies in contact with the seats comes to rest with the bus, while their upper bodies continue moving forward due to inertia of motion (Newton\'s 1st Law).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_45',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'An object weighs $98\\text{ N}$ on the surface of Earth ($g = 9.8\\text{ m/s}^2$). What is its mass on the Moon where $g = 1.6\\text{ m/s}^2$?',
      options: {
        A: '$10\\text{ kg}$',
        B: '$16\\text{ kg}$',
        C: '$61.25\\text{ kg}$',
        D: '$1.6\\text{ kg}$',
      },
      correctAnswer: 'A',
      explanation: 'Mass is the quantity of matter and remains constant everywhere: $m = \\frac{W}{g} = \\frac{98\\text{ N}}{9.8\\text{ m/s}^2} = 10\\text{ kg}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_46',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'What is the net resultant force acting on a $1500\\text{ kg}$ helicopter hovering stationary in mid-air at a fixed altitude?',
      options: {
        A: '$0\\text{ N}$ (Zero net force)',
        B: '$15000\\text{ N}$ directed upwards',
        C: '$14700\\text{ N}$ directed downwards',
        D: '$1500\\text{ N}$ horizontally',
      },
      correctAnswer: 'A',
      explanation: 'According to Newton\'s First Law, since the helicopter is stationary in static equilibrium ($a = 0$), the upward rotor lift exactly balances the downward gravitational weight, resulting in a net unbalanced force of zero ($F_{\\text{net}} = 0$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_47',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'A net force of $20\\text{ N}$ produces an acceleration of $4\\text{ m/s}^2$ in mass $m_1$ and $5\\text{ m/s}^2$ in mass $m_2$. If both masses are tied together, what acceleration will the same $20\\text{ N}$ force produce?',
      options: {
        A: '$2.22\\text{ m/s}^2$',
        B: '$4.5\\text{ m/s}^2$',
        C: '$9.0\\text{ m/s}^2$',
        D: '$1.0\\text{ m/s}^2$',
      },
      correctAnswer: 'A',
      explanation: '$m_1 = \\frac{F}{a_1} = \\frac{20}{4} = 5\\text{ kg}$; $m_2 = \\frac{F}{a_2} = \\frac{20}{5} = 4\\text{ kg}$. Combined mass $M = 5 + 4 = 9\\text{ kg}$. Acceleration $a = \\frac{F}{M} = \\frac{20}{9} \\approx 2.22\\text{ m/s}^2$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_3_48',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'An elevator of mass $600\\text{ kg}$ is ascending vertically upwards at a constant uniform velocity of $4\\text{ m/s}$. The net resultant force acting on the elevator is:',
      options: {
        A: '$0\\text{ N}$',
        B: '$2400\\text{ N}$',
        C: '$5880\\text{ N}$',
        D: '$8280\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'Since the elevator is moving at constant velocity, its acceleration is zero ($a = 0$). By Newton\'s Second Law, net resultant force $F_{net} = ma = 0\\text{ N}$. (Tension equals weight).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_49',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'A mass of $5\\text{ kg}$ is suspended at rest from the ceiling by a vertical cord. Taking $g = 9.8\\text{ m/s}^2$, what is the tension in the cord?',
      options: {
        A: '$49\\text{ N}$',
        B: '$5\\text{ N}$',
        C: '$0\\text{ N}$',
        D: '$98\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'At static equilibrium, upward tension balances downward gravitational force (weight): $T = mg = 5\\text{ kg} \\times 9.8\\text{ m/s}^2 = 49\\text{ N}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_50',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'What happens to the acceleration of a body when the net unbalanced force acting on it is tripled while its mass remains constant?',
      options: {
        A: 'The acceleration is tripled ($a \\to 3a$)',
        B: 'The acceleration is reduced to one-third',
        C: 'The acceleration increases by a factor of 9',
        D: 'The acceleration remains unchanged',
      },
      correctAnswer: 'A',
      explanation: 'By Newton\'s Second Law ($F = ma \\implies a = \\frac{F}{m}$), acceleration is directly proportional to net force ($a \\propto F$). When the net force is tripled with constant mass, the acceleration also triples.',
      difficulty: 'easy',
    },
  ],
  'Dynamics – II': [
    {
      id: 'fbise9_phy_4_41',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'A rifle of mass $4\\text{ kg}$ fires a bullet of mass $0.02\\text{ kg}$ ($20\\text{ g}$) with a muzzle velocity of $400\\text{ m/s}$. The recoil velocity of the rifle is:',
      options: {
        A: '$-2.0\\text{ m/s}$',
        B: '$-4.0\\text{ m/s}$',
        C: '$-0.5\\text{ m/s}$',
        D: '$-8.0\\text{ m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'By law of conservation of momentum: $M_r v_r + m_b v_b = 0 \\implies v_r = -\\frac{m_b v_b}{M_r} = -\\frac{0.02 \\times 400}{4} = -2.0\\text{ m/s}$ (negative sign indicates recoil in the opposite direction).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_42',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'A horizontal pulling force of $30\\text{ N}$ is just sufficient to initiate sliding of a $100\\text{ N}$ wooden block across a level floor. The coefficient of static friction $\\mu_s$ is:',
      options: {
        A: '$0.30$',
        B: '$3.33$',
        C: '$0.03$',
        D: '$0.70$',
      },
      correctAnswer: 'A',
      explanation: '$\\mu_s = \\frac{F_s}{R} = \\frac{30\\text{ N}}{100\\text{ N}} = 0.30$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_43',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'A car of mass $1000\\text{ kg}$ navigates a circular track of radius $50\\text{ m}$ at a constant speed of $10\\text{ m/s}$. What is the centripetal force required to keep it on the curve?',
      options: {
        A: '$2000\\text{ N}$',
        B: '$1000\\text{ N}$',
        C: '$5000\\text{ N}$',
        D: '$200\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: '$F_c = \\frac{mv^2}{r} = \\frac{1000 \\times 10^2}{50} = \\frac{1000 \\times 100}{50} = 2000\\text{ N}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_44',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'Why are highway turns and railway curves banked (outer edge built higher than the inner edge)?',
      options: {
        A: 'To provide the necessary centripetal force from the horizontal component of normal reaction',
        B: 'To increase the force of gravity on the vehicle',
        C: 'To eliminate rolling friction completely',
        D: 'To reduce the maximum permissible speed of vehicles',
      },
      correctAnswer: 'A',
      explanation: 'Banking tilts the normal reaction force so that its horizontal component ($R\\sin\\theta$) provides the required centripetal force, preventing dangerous sideways skidding without relying solely on tyre friction.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_45',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'In a centrifuge cream separator, why do less dense cream particles separate and collect near the central axis while denser skim milk is forced outwards?',
      options: {
        A: 'Denser milk requires larger centripetal force and is thrown outwards, leaving lighter cream at the center',
        B: 'Cream particles have greater mass and experience stronger centrifugal repulsion',
        C: 'Friction between cream and the bowl wall is higher',
        D: 'Cream particles carry negative electric charges',
      },
      correctAnswer: 'A',
      explanation: 'Centripetal force is directly proportional to mass ($F_c = m\\omega^2 r$). The denser skim milk needs and experiences larger inward forces, displacing the lighter cream particles toward the axis of rotation.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_4_46',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'On a curved circular road bend, why is the outer edge of the road banked higher than the inner edge?',
      options: {
        A: 'To provide a horizontal component of normal reaction that supplies the required centripetal force',
        B: 'To eliminate the downward gravitational force acting on the car',
        C: 'To increase the coefficient of kinetic friction between tires and asphalt',
        D: 'To reduce the rotational inertia of the car wheels',
      },
      correctAnswer: 'A',
      explanation: 'Banking the track at an angle $\\theta$ produces an inward horizontal component of the normal reaction force ($R\\sin\\theta = \\frac{mv^2}{r}$), providing the necessary centripetal force and preventing high-speed vehicles from skidding outward.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_47',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'Rolling friction is significantly smaller (often 100 to 1000 times less) than sliding friction primarily because:',
      options: {
        A: 'The microscopic area of contact is extremely small and there is no relative sliding/rubbing of surfaces',
        B: 'Rolling objects experience zero normal reaction force',
        C: 'Gravitational attraction vanishes during rolling motion',
        D: 'Rolling surfaces are always coated with lubricants',
      },
      correctAnswer: 'A',
      explanation: 'In rolling motion, contact points momentarily touch and lift without sliding over each other, minimizing the inter-locking and shearing of microscopic cold-welded surface irregularities.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_48',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'If the linear speed of a body traversing a circle of constant radius $r$ is tripled ($v \\to 3v$), its centripetal acceleration increases by a factor of:',
      options: {
        A: '$9$',
        B: '$3$',
        C: '$6$',
        D: '$27$',
      },
      correctAnswer: 'A',
      explanation: 'Centripetal acceleration is $a_c = \\frac{v^2}{r}$. Since $a_c \\propto v^2$, tripling the speed ($3^2 = 9$) increases the acceleration by a factor of 9.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_49',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'A $2.0\\text{ kg}$ trolley moving at $6.0\\text{ m/s}$ collides with and couples to a stationary $4.0\\text{ kg}$ trolley. What is their common velocity immediately after collision?',
      options: {
        A: '$2.0\\text{ m/s}$',
        B: '$3.0\\text{ m/s}$',
        C: '$1.5\\text{ m/s}$',
        D: '$4.0\\text{ m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'By conservation of momentum: $m_1 u_1 + m_2 u_2 = (m_1 + m_2)v \\implies 2(6.0) + 4(0) = (2 + 4)v \\implies 12 = 6v \\implies v = 2.0\\text{ m/s}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_50',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'Ball bearings and roller bearings are incorporated into wheels and machine axles to:',
      options: {
        A: 'Convert sliding friction into much lower rolling friction',
        B: 'Increase the static friction between shafts',
        C: 'Reduce the total rotational speed of wheels',
        D: 'Eliminate all mechanical contact with the axle',
      },
      correctAnswer: 'A',
      explanation: 'Ball bearings replace direct sliding contact with rolling spheres, dramatically reducing friction, heat generation, and mechanical wear.',
      difficulty: 'easy',
    },
  ],
  'Pressure and Deformation in Solids': [
    {
      id: 'fbise9_phy_5_41',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'In a hydraulic press, an input piston of area $0.02\\text{ m}^2$ is pushed down with a force of $100\\text{ N}$. What output lifting force is exerted by the larger piston of area $0.80\\text{ m}^2$?',
      options: {
        A: '$4000\\text{ N}$',
        B: '$800\\text{ N}$',
        C: '$2000\\text{ N}$',
        D: '$1600\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'By Pascal\'s principle: $\\frac{F_1}{A_1} = \\frac{F_2}{A_2} \\implies F_2 = F_1 \\times \\frac{A_2}{A_1} = 100 \\times \\frac{0.80}{0.02} = 100 \\times 40 = 4000\\text{ N}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_42',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'According to the Principle of Floatation, an ocean cargo ship floats stably on seawater when the weight of the water it displaces is equal to:',
      options: {
        A: 'The total weight of the ship and all its cargo',
        B: 'The total volume of the ship multiplied by atmospheric pressure',
        C: 'Half of the ship\'s deadweight tonnage',
        D: 'The maximum capacity weight of the ship',
      },
      correctAnswer: 'A',
      explanation: 'An object will float in a fluid when the upward buoyant force (weight of displaced fluid) equals the total downward gravitational force (total weight of the floating body).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_43',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'A steel wire of original length $2.0\\text{ m}$ and cross-sectional area $1.0 \\times 10^{-6}\\text{ m}^2$ extends by $2.0\\text{ mm}$ ($2.0 \\times 10^{-3}\\text{ m}$) under a load of $200\\text{ N}$. What is the Young\'s modulus of the steel?',
      options: {
        A: '$2.0 \\times 10^{11}\\text{ Pa}$',
        B: '$1.0 \\times 10^{11}\\text{ Pa}$',
        C: '$4.0 \\times 10^{10}\\text{ Pa}$',
        D: '$2.0 \\times 10^{9}\\text{ Pa}$',
      },
      correctAnswer: 'A',
      explanation: '$Y = \\frac{F L_0}{A \\Delta L} = \\frac{200 \\times 2.0}{1.0 \\times 10^{-6} \\times 2.0 \\times 10^{-3}} = \\frac{400}{2.0 \\times 10^{-9}} = 2.0 \\times 10^{11}\\text{ Pa}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_5_44',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'The standard sea-level atmospheric pressure of $1.013 \\times 10^5\\text{ Pa}$ supports a vertical column of mercury in a simple Torricellian barometer equal to:',
      options: {
        A: '$760\\text{ mm}$ ($76\\text{ cm}$)',
        B: '$1000\\text{ mm}$',
        C: '$76\\text{ mm}$',
        D: '$10.3\\text{ cm}$',
      },
      correctAnswer: 'A',
      explanation: 'Standard atmospheric pressure ($1\\text{ atm}$) supports a column of mercury of height $760\\text{ mm}$ ($76\\text{ cm} = 0.76\\text{ m}$ of Hg).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_45',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'Why does a massive steel ship float on water while a small solid steel needle sinks?',
      options: {
        A: 'The ship has a hollow design enclosing air, making its average density less than water',
        B: 'The buoyant force on the needle is directed downwards',
        C: 'Steel changes its chemical properties when forged into a ship',
        D: 'Surface tension supports the ship but not the needle',
      },
      correctAnswer: 'A',
      explanation: 'The large hollow structure of a ship encloses a huge volume of air, making the average density of the entire ship much lower than that of water. It therefore displaces a weight of water equal to its own weight.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_46',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'In a hydraulic lift operating on Pascal\'s principle, a small piston has a diameter of $2\\text{ cm}$ and a large load piston has a diameter of $20\\text{ cm}$. What is the ideal mechanical force multiplication factor?',
      options: {
        A: '$100$',
        B: '$10$',
        C: '$20$',
        D: '$1000$',
      },
      correctAnswer: 'A',
      explanation: 'In a hydraulic lift, transmitted pressure is equal ($P_1 = P_2$). The force multiplication factor equals the ratio of piston areas: $\\frac{A_2}{A_1} = \\frac{\\pi (d_2/2)^2}{\\pi (d_1/2)^2} = \\left(\\frac{d_2}{d_1}\\right)^2 = \\left(\\frac{20}{2}\\right)^2 = 10^2 = 100$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_47',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'When a metallic wire is stretched beyond its elastic limit, the resulting deformation is characterized as:',
      options: {
        A: 'Permanent plastic deformation',
        B: 'Fully reversible elastic strain',
        C: 'Hydrostatic expansion',
        D: 'Thermal annealing',
      },
      correctAnswer: 'A',
      explanation: 'Beyond the elastic limit, the internal crystal planes of atoms slip permanently. The material cannot restore its original length when the deforming force is removed, resulting in permanent plastic deformation.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_48',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'Why is mercury preferred over water in a standard liquid barometer for measuring atmospheric pressure?',
      options: {
        A: 'Its high density allows a convenient column height of about $76\\text{ cm}$ rather than over $10\\text{ m}$ for water',
        B: 'Mercury is less hazardous to handle in open laboratory conditions',
        C: 'Water does not exert any vapor pressure inside an evacuated glass tube',
        D: 'Mercury expands significantly more uniformly than water at all altitudes',
      },
      correctAnswer: 'A',
      explanation: 'Atmospheric pressure supports a column of liquid according to $P_0 = \\rho g h$. Because mercury has a high density ($13600\\text{ kg/m}^3$), the required column height is only $\\approx 0.76\\text{ m}$ ($76\\text{ cm}$), whereas water would require an impractical tube height of $10.3\\text{ m}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_49',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'What is the SI unit of tensile strain ($\\Delta L / L_0$)?',
      options: {
        A: 'Dimensionless (no unit)',
        B: 'Pascal ($\\text{Pa}$)',
        C: '$\\text{N/m}^2$',
        D: 'Meter ($\\text{m}$)',
      },
      correctAnswer: 'A',
      explanation: 'Tensile strain is the ratio of change in length to original length ($\\text{meters} / \\text{meters}$). Because the units cancel out, strain is a dimensionless ratio with no units.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_50',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'A U-tube manometer filled with liquid is connected to an enclosed gas chamber. The difference in liquid column levels is $\\Delta h$. The gauge pressure of the gas is calculated using:',
      options: {
        A: '$P_{\\text{gauge}} = \\rho g \\Delta h$',
        B: '$P_{\\text{gauge}} = \\frac{\\rho g}{\\Delta h}$',
        C: '$P_{\\text{gauge}} = \\frac{\\rho \\Delta h}{g}$',
        D: '$P_{\\text{gauge}} = P_0 + \\rho g \\Delta h$',
      },
      correctAnswer: 'A',
      explanation: 'Gauge pressure is the excess pressure above atmospheric pressure, given directly by the hydrostatic height difference: $P_{\\text{gauge}} = \\rho g \\Delta h$.',
      difficulty: 'medium',
    },
  ],
  'Work and Energy': [
    {
      id: 'fbise9_phy_6_41',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'How much energy in Megajoules ($\\text{MJ}$) is consumed when a $1000\\text{ W}$ electric heater operates continuously for $2.0\\text{ hours}$?',
      options: {
        A: '$7.2\\text{ MJ}$',
        B: '$2.0\\text{ MJ}$',
        C: '$3.6\\text{ MJ}$',
        D: '$14.4\\text{ MJ}$',
      },
      correctAnswer: 'A',
      explanation: '$E = P \\times t = 1000\\text{ W} \\times (2 \\times 3600\\text{ s}) = 1000 \\times 7200 = 7.2 \\times 10^6\\text{ J} = 7.2\\text{ MJ}$ (equal to $2\\text{ kWh}$).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_42',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'When a constant propelling force $F$ moves an object forward at an instantaneous velocity $v$, the mechanical power output is expressed as:',
      options: {
        A: '$P = F \\times v$',
        B: '$P = \\frac{F}{v}$',
        C: '$P = \\frac{v}{F}$',
        D: '$P = \\frac{1}{2} F v^2$',
      },
      correctAnswer: 'A',
      explanation: 'Power is the time rate of doing work: $P = \\frac{W}{t} = \\frac{F \\times S}{t} = F \\times \\left(\\frac{S}{t}\\right) = F \\times v$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_43',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'A machine is supplied with $500\\text{ J}$ of electrical energy and delivers $350\\text{ J}$ of useful mechanical work. What is its percentage efficiency?',
      options: {
        A: '$70\\%$',
        B: '$35\\%$',
        C: '$85\\%$',
        D: '$150\\%$',
      },
      correctAnswer: 'A',
      explanation: '$\\text{Efficiency} = \\frac{\\text{Useful Output Energy}}{\\text{Total Input Energy}} \\times 100\\% = \\frac{350}{500} \\times 100\\% = 70\\%$. (Wasted energy is $150\\text{ J}$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_44',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'If the linear momentum $p$ of a moving body of constant mass $m$ is doubled ($p \\to 2p$), its kinetic energy ($E_k = \\frac{p^2}{2m}$) will increase by a factor of:',
      options: {
        A: '$4$',
        B: '$2$',
        C: '$8$',
        D: '$\\sqrt{2}$',
      },
      correctAnswer: 'A',
      explanation: 'Kinetic energy in terms of momentum is $E_k = \\frac{p^2}{2m}$. Since $E_k \\propto p^2$, doubling the momentum ($(2p)^2 = 4p^2$) increases the kinetic energy by a factor of 4.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_45',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'A student carries a $20\\text{ kg}$ schoolbag on his back while walking horizontally across a flat classroom floor for $10\\text{ m}$. What is the work done against gravity by the upward supporting force?',
      options: {
        A: '$0\\text{ J}$',
        B: '$200\\text{ J}$',
        C: '$1960\\text{ J}$',
        D: '$98\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: '$W = F s \\cos\\theta$. The upward supporting force is perpendicular to the horizontal displacement ($\\theta = 90^\\circ$). Since $\\cos(90^\\circ) = 0$, the work done against gravity during horizontal motion is $0\\text{ J}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_46',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'A ball of mass $0.5\\text{ kg}$ is dropped freely from a height of $20\\text{ m}$ above the ground ($g = 10\\text{ m/s}^2$). Neglecting air resistance, its kinetic energy just before striking the ground is:',
      options: {
        A: '$100\\text{ J}$',
        B: '$50\\text{ J}$',
        C: '$200\\text{ J}$',
        D: '$10\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: 'By conservation of mechanical energy, loss in gravitational potential energy equals gain in kinetic energy: $E_k = mgh = 0.5\\text{ kg} \\times 10\\text{ m/s}^2 \\times 20\\text{ m} = 100\\text{ J}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_47',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'One standard imperial horsepower ($1\\text{ hp}$) is defined in electrical terms as equivalent to:',
      options: {
        A: '$746\\text{ W}$',
        B: '$1000\\text{ W}$',
        C: '$550\\text{ W}$',
        D: '$3600\\text{ W}$',
      },
      correctAnswer: 'A',
      explanation: '$1\\text{ horsepower (hp)} = 746\\text{ Watts}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_48',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'In a hydroelectric power station, what is the exact chronological sequence of primary energy transformations?',
      options: {
        A: 'Gravitational Potential Energy $\\to$ Kinetic Energy of water $\\to$ Mechanical Energy of turbine $\\to$ Electrical Energy',
        B: 'Thermal Energy $\\to$ Gravitational Energy $\\to$ Electrical Energy $\\to$ Chemical Energy',
        C: 'Electrical Energy $\\to$ Kinetic Energy $\\to$ Potential Energy $\\to$ Thermal Energy',
        D: 'Chemical Energy $\\to$ Kinetic Energy $\\to$ Turbine Energy $\\to$ Electrical Energy',
      },
      correctAnswer: 'A',
      explanation: 'Water stored high in a reservoir possesses gravitational potential energy, which transforms into kinetic energy as it rushes down penstocks, then into mechanical rotational energy of turbines, and finally into electrical energy in generators.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_49',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'A motorboat travels through water at a steady speed of $12\\text{ m/s}$ against a total hydrodynamic drag resistance of $500\\text{ N}$. What mechanical power is delivered by the boat engine?',
      options: {
        A: '$6000\\text{ W}$ ($6.0\\text{ kW}$)',
        B: '$41.6\\text{ W}$',
        C: '$3000\\text{ W}$',
        D: '$12000\\text{ W}$',
      },
      correctAnswer: 'A',
      explanation: '$P = \\text{Force} \\times \\text{Velocity} = F v = 500\\text{ N} \\times 12\\text{ m/s} = 6000\\text{ W} = 6.0\\text{ kW}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_50',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'Which of the following is classified as a renewable and clean energy source that does not release carbon greenhouse gases during operation?',
      options: {
        A: 'Geothermal energy',
        B: 'Anthracite coal',
        C: 'Petroleum diesel',
        D: 'Liquefied natural gas',
      },
      correctAnswer: 'A',
      explanation: 'Geothermal energy taps natural thermal heat from Earth\'s crust and is renewable and environmentally clean, unlike fossil fuels (coal, diesel, natural gas) which emit greenhouse gases.',
      difficulty: 'easy',
    },
  ],
  'Density and Temperature': [
    {
      id: 'fbise9_phy_7_41',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'At what temperature do the Celsius and Fahrenheit temperature scales display the exact same numerical reading?',
      options: {
        A: '$-40^\\circ$',
        B: '$0^\\circ$',
        C: '$100^\\circ$',
        D: '$32^\\circ$',
      },
      correctAnswer: 'A',
      explanation: 'Setting $F = C$: $C = \\frac{9}{5}C + 32 \\implies C - \\frac{9}{5}C = 32 \\implies -\\frac{4}{5}C = 32 \\implies C = -40^\\circ$. Thus, $-40^\\circ\\text{C} = -40^\\circ\\text{F}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_42',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Which thermometric property is utilized in a standard liquid-in-glass laboratory thermometer?',
      options: {
        A: 'Uniform thermal expansion of liquid volume with changing temperature',
        B: 'Variation of electrical resistance with temperature',
        C: 'Change in gas pressure at fixed volume',
        D: 'Thermal electromotive force generated at a thermocouple junction',
      },
      correctAnswer: 'A',
      explanation: 'A liquid-in-glass thermometer (containing mercury or alcohol) operates on the principle that the liquid column volume expands linearly and uniformly with an increase in temperature.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_43',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'How much thermal energy is needed to completely melt $0.5\\text{ kg}$ of ice at $0^\\circ\\text{C}$ into water at $0^\\circ\\text{C}$ ($L_f = 3.36 \\times 10^5\\text{ J/kg}$)?',
      options: {
        A: '$168,000\\text{ J}$ ($168\\text{ kJ}$)',
        B: '$336,000\\text{ J}$',
        C: '$672,000\\text{ J}$',
        D: '$84,000\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: '$Q = m L_f = 0.5\\text{ kg} \\times 3.36 \\times 10^5\\text{ J/kg} = 1.68 \\times 10^5\\text{ J} = 168\\text{ kJ}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_44',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A bimetallic strip made of brass (larger coefficient $\\alpha$) and iron (smaller coefficient $\\alpha$) is heated uniformly. The strip bends such that:',
      options: {
        A: 'Brass forms the outer convex curve and iron forms the inner concave curve',
        B: 'Iron forms the outer convex curve and brass forms the inner concave curve',
        C: 'The strip remains straight but increases in thickness',
        D: 'The strip twists spirally along its longitudinal axis',
      },
      correctAnswer: 'A',
      explanation: 'Since brass has a higher coefficient of linear expansion than iron, it expands more for the same temperature increase, forming the longer outer convex side while iron forms the inner concave side.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_45',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A $100\\text{ m}$ long copper pipe expands when its temperature rises by $50^\\circ\\text{C}$. If $\\alpha = 1.7 \\times 10^{-5}\\text{ K}^{-1}$, what is the increase in length $\\Delta L$?',
      options: {
        A: '$0.085\\text{ m}$ ($8.5\\text{ cm}$)',
        B: '$0.85\\text{ m}$',
        C: '$0.0085\\text{ m}$',
        D: '$0.17\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: '$\\Delta L = \\alpha L_0 \\Delta T = 1.7 \\times 10^{-5} \\times 100\\text{ m} \\times 50 = 0.085\\text{ m} = 8.5\\text{ cm}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_46',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Why does human perspiration cool the body less effectively on a humid, muggy day?',
      options: {
        A: 'High atmospheric humidity reduces the rate of water evaporation from the skin',
        B: 'Sweat contains fewer electrolytes on humid days',
        C: 'Humid air absorbs heat directly into the skin',
        D: 'The body stops sweating completely in high humidity',
      },
      correctAnswer: 'A',
      explanation: 'Evaporation is a cooling process because escaping high-energy molecules carry away latent heat. When surrounding air is already saturated with water vapor (high humidity), the net evaporation rate drops drastically.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_47',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Water is widely utilized as an effective industrial and automotive coolant because of its remarkably high:',
      options: {
        A: 'Specific heat capacity ($4200\\text{ J}/(\\text{kg}\\cdot\\text{K})$)',
        B: 'Thermal conductivity',
        C: 'Coefficient of linear expansion',
        D: 'Electrical resistivity',
      },
      correctAnswer: 'A',
      explanation: 'Water has an unusually high specific heat capacity ($4200\\text{ J}/(\\text{kg}\\cdot\\text{K})$), meaning it can absorb massive amounts of heat energy with only a modest rise in temperature.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_48',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Why is water widely utilized as the circulating coolant in automobile engine radiators?',
      options: {
        A: 'It possesses an exceptionally high specific heat capacity ($c = 4200\\text{ J}/(\\text{kg}\\cdot^\\circ\\text{C})$)',
        B: 'It has very low thermal expansion compared to other liquids',
        C: 'It freezes easily at low winter temperatures',
        D: 'It exhibits high electrical conductivity under pressure',
      },
      correctAnswer: 'A',
      explanation: 'Because of its unusually high specific heat capacity ($4200\\text{ J}/(\\text{kg}\\cdot^\\circ\\text{C})$), water can absorb a tremendous amount of thermal energy from the running engine with only a moderate rise in temperature.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_49',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'How is the rate of surface evaporation of a liquid affected by high atmospheric humidity?',
      options: {
        A: 'Evaporation decreases because the surrounding air is already near saturation with moisture',
        B: 'Evaporation increases because moist air absorbs more latent heat',
        C: 'Evaporation remains completely unchanged by humidity levels',
        D: 'Evaporation stops instantly and turns into boiling',
      },
      correctAnswer: 'A',
      explanation: 'When humidity is high, the surrounding air holds a high concentration of water vapor molecules, which reduces the net rate of escape of energetic liquid molecules into the vapor phase.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_50',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Why are small deliberate gaps left between consecutive steel rail tracks on railway lines?',
      options: {
        A: 'To allow free linear thermal expansion in hot summer weather and prevent track buckling',
        B: 'To increase the speed of moving trains',
        C: 'To save manufacturing material during track laying',
        D: 'To allow rainwater drainage from the track bed',
      },
      correctAnswer: 'A',
      explanation: 'Steel expands in hot summer weather. Expansion gaps accommodate this thermal elongation without building destructive compressive stresses that would buckle the tracks.',
      difficulty: 'easy',
    },
  ],
  'Magnetism': [
    {
      id: 'fbise9_phy_8_41',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Which of the following materials is a ferromagnetic substance strongly attracted by magnetic fields?',
      options: {
        A: 'Cobalt',
        B: 'Copper',
        C: 'Aluminum',
        D: 'Zinc',
      },
      correctAnswer: 'A',
      explanation: 'Cobalt, Iron, Nickel, and their alloys are ferromagnetic materials with high magnetic permeability that are strongly attracted by magnets.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_42',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Why is soft iron preferred over hard steel for the core of electromagnets and electric bells?',
      options: {
        A: 'Soft iron is easily magnetized and rapidly loses its magnetism when the current is switched off',
        B: 'Soft iron becomes a permanent magnet permanently',
        C: 'Soft iron has zero electrical conductivity',
        D: 'Soft iron is much harder than steel',
      },
      correctAnswer: 'A',
      explanation: 'Soft iron is a temporary magnetic material with high permeability and low retentivity/coercivity, allowing it to magnetize instantly when current flows and demagnetize immediately when current stops.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_43',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'What is the most effective method for completely demagnetizing a permanent steel bar magnet in the laboratory?',
      options: {
        A: 'Placing it inside an East-West aligned solenoid carrying AC current and slowly withdrawing it',
        B: 'Immersing it in cold ice water',
        C: 'Stroking it repeatedly in one direction with a copper rod',
        D: 'Connecting it to a direct current (DC) battery',
      },
      correctAnswer: 'A',
      explanation: 'Alternating current (AC) rapidly reverses magnetic domain orientation. Slowly withdrawing the magnet from an energized AC solenoid oriented East-West leaves magnetic domains randomized, neutralizing net magnetism.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_8_44',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'If a bar magnet is cut into two equal halves transversely through its middle, what is the result?',
      options: {
        A: 'Two complete smaller magnets, each possessing both a North and a South pole',
        B: 'One piece with only a North pole and one piece with only a South pole',
        C: 'Both pieces become completely unmagnetized',
        D: 'One piece remains magnetic while the other loses magnetism',
      },
      correctAnswer: 'A',
      explanation: 'Magnetic monopoles do not exist in nature. Cutting a bar magnet produces new opposite poles at the cut faces, creating two complete bipolar magnets.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_45',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'In the external region surrounding a permanent bar magnet, magnetic field lines are directed from:',
      options: {
        A: 'North pole to South pole',
        B: 'South pole to North pole',
        C: 'Center of magnet outwards radially in all directions',
        D: 'East to West only',
      },
      correctAnswer: 'A',
      explanation: 'By standard scientific convention, external magnetic field lines emerge from the North pole and curve around to enter the South pole, forming continuous closed loops.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_46',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'How can sensitive electronic circuits and mechanical watches be effectively shielded from external stray magnetic fields?',
      options: {
        A: 'Enclosing them in a soft iron magnetic screening casing',
        B: 'Wrapping them with thick copper foil',
        C: 'Surrounding them with permanent bar magnets',
        D: 'Placing them in an airtight plastic vacuum container',
      },
      correctAnswer: 'A',
      explanation: 'Soft iron has very high magnetic permeability. Magnetic field lines preferentially pass through the soft iron shield walls rather than entering the hollow interior (magnetic screening).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_47',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'The strength of the magnetic field produced inside a current-carrying solenoid can be enhanced by:',
      options: {
        A: 'Inserting a soft iron core and increasing the electric current',
        B: 'Decreasing the number of coil turns per unit length',
        C: 'Replacing the copper coil with an insulator',
        D: 'Increasing the diameter while keeping coil turns constant',
      },
      correctAnswer: 'A',
      explanation: 'The solenoid field strength is $B = \\mu n I$. It is increased by raising current $I$, increasing turn density $n$, and adding a high-permeability soft iron core.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_48',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Which magnetic interaction test is considered the ONLY sure, definitive proof that an unknown metallic specimen is magnetized?',
      options: {
        A: 'Magnetic repulsion with a known pole of a magnet',
        B: 'Magnetic attraction to a known pole of a magnet',
        C: 'Ability to conduct electric current',
        D: 'Spontaneous glow in the dark',
      },
      correctAnswer: 'A',
      explanation: 'An unmagnetized magnetic material (like soft iron) is attracted by both poles of a magnet. Repulsion occurs only between two like magnetic poles, making repulsion the only sure test of magnetization.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_49',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'What is the geometric shape of magnetic field lines in the plane perpendicular to a long straight current-carrying wire?',
      options: {
        A: 'Concentric circles centered on the wire',
        B: 'Straight parallel lines radiating outwards',
        C: 'Elliptical loops extending to infinity',
        D: 'Helical spirals along the wire',
      },
      correctAnswer: 'A',
      explanation: 'The magnetic field of a straight current-carrying conductor consists of concentric circular lines centered on the wire, whose direction is given by the Right-Hand Grip Rule.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_50',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Permanent magnets are manufactured primarily from hard steel or Alnico alloys because these materials possess:',
      options: {
        A: 'High magnetic retentivity and high coercivity',
        B: 'Low magnetic retentivity and zero resistance',
        C: 'High thermal expansion and low density',
        D: 'Zero electrical conductivity',
      },
      correctAnswer: 'A',
      explanation: 'High retentivity ensures strong residual magnetism, while high coercivity resists demagnetization from stray fields, shocks, and temperature variations.',
      difficulty: 'medium',
    },
  ],
  'Nature of Science and Physics': [
    {
      id: 'fbise9_phy_9_41',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Which renowned Muslim scientist is celebrated as the "Father of Modern Optics" for introducing rigorous experimental methodology and publishing *Kitab al-Manazir* (Book of Optics)?',
      options: {
        A: 'Ibn al-Haytham (Alhazen)',
        B: 'Al-Biruni',
        C: 'Ibn Sina (Avicenna)',
        D: 'Al-Khwarizmi',
      },
      correctAnswer: 'A',
      explanation: 'Ibn al-Haytham (965–1040 CE) revolutionized optics through experiments on light rays, reflection, refraction, and the pinhole camera (*Kitab al-Manazir*).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_42',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Which Muslim scientist authored *Kitab Mizan al-Hikma* (The Book of the Balance of Wisdom), determining the precise specific gravities of various metals and precious gems?',
      options: {
        A: 'Al-Khazini',
        B: 'Jabir ibn Hayyan',
        C: 'Al-Razi',
        D: 'Al-Kindi',
      },
      correctAnswer: 'A',
      explanation: 'Abd al-Rahman al-Khazini designed advanced hydrostatic balances to measure densities and specific gravities of liquids and metals with extraordinary accuracy in *Kitab Mizan al-Hikma*.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_43',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'How does a systematic error in measurement differ fundamentally from a random error?',
      options: {
        A: 'Systematic error consistently shifts readings in one fixed direction due to calibration or zero defects, whereas random error varies unpredictably',
        B: 'Systematic error cannot be corrected, while random error is always constant',
        C: 'Random error occurs only with digital instruments, while systematic error occurs only with analogue instruments',
        D: 'Systematic error is caused purely by environmental temperature swings',
      },
      correctAnswer: 'A',
      explanation: 'Systematic errors arise from known zero errors, incorrect calibration, or consistent bias and affect all readings equally in one direction. Random errors vary unpredictably in sign and magnitude due to minor fluctuating conditions.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_44',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Which Muslim scholar and physician formulated the precursor concept of momentum (*mayl* or inclination) in his physical treatises?',
      options: {
        A: 'Ibn Sina (Avicenna)',
        B: 'Jabir ibn Hayyan',
        C: 'Al-Farabi',
        D: 'Al-Khwarizmi',
      },
      correctAnswer: 'A',
      explanation: 'Ibn Sina proposed that a projectile in motion receives an impetus (*mayl*) that keeps it moving until air resistance exhausts it, anticipating the modern concepts of inertia and momentum.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_45',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'In the scientific method, what is the role and definition of a "hypothesis"?',
      options: {
        A: 'A tentative, testable proposed explanation for an observed physical phenomenon',
        B: 'An absolute, unchangeable scientific law verified for centuries',
        C: 'A mathematical calculation devoid of physical observations',
        D: 'A subjective philosophical belief that cannot be tested experimentally',
      },
      correctAnswer: 'A',
      explanation: 'A hypothesis is a provisional, testable proposition formulated to explain observations, which can be supported or refuted through controlled experimental verification.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_46',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Which branch of physics is devoted to the study of the production, properties, and confinement of ionized gases (the fourth state of matter)?',
      options: {
        A: 'Plasma Physics',
        B: 'Solid State Physics',
        C: 'Geophysics',
        D: 'Classical Mechanics',
      },
      correctAnswer: 'A',
      explanation: 'Plasma Physics investigates the ionic state of matter consisting of free electrons and positive ions at extremely high temperatures, which constitutes stars, lightning, and fusion devices.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_47',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Parallax error during physical measurements with an analogue ruler or meter rule is avoided by:',
      options: {
        A: 'Positioning the line of sight strictly perpendicular to the scale at the measurement mark',
        B: 'Looking at the scale from a $45^\\circ$ oblique angle',
        C: 'Using a magnifying glass while viewing from the left side',
        D: 'Averaging readings taken from extreme diagonal angles',
      },
      correctAnswer: 'A',
      explanation: 'Parallax error occurs when the eye is positioned obliquely relative to the pointer or scale mark. Keeping the eye perpendicularly above the scale line eliminates this optical displacement error.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_48',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'In scientific epistemology, how is a scientific law distinguished from a scientific theory?',
      options: {
        A: 'A law describes an observed regularity or relationship (often mathematically), while a theory provides a comprehensive explanatory framework for why it happens',
        B: 'A law is a temporary guess, while a theory is permanent fact',
        C: 'A theory can be expressed as a mathematical formula, but a law cannot',
        D: 'Laws apply only to astronomy, whereas theories apply to biology',
      },
      correctAnswer: 'A',
      explanation: 'A scientific law summarizes what happens under specified conditions (e.g. $F = ma$). A scientific theory explains why and how things occur based on extensive empirical evidence (e.g. Kinetic Molecular Theory).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_49',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'The operational physics of modern silicon semiconductors, integrated microchips, and photovoltaic solar panels is grounded in:',
      options: {
        A: 'Solid State Physics',
        B: 'Classical Fluid Mechanics',
        C: 'Astrophysics',
        D: 'Geodesy',
      },
      correctAnswer: 'A',
      explanation: 'Solid State Physics (Condensed Matter Physics) studies the quantum electronic, crystalline, and band structures of solids, providing the foundation for semiconductor diodes, transistors, microprocessors, and solar cells.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_50',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'What is the mandatory primary laboratory safety measure when assembling or modifying an electrical experiment circuit?',
      options: {
        A: 'Ensure the main power supply is turned off and disconnected before touching circuit components',
        B: 'Moisten hands with water to increase contact grip',
        C: 'Use bare uninsulated copper wires without fuse protection',
        D: 'Increase circuit voltage to maximum before testing',
      },
      correctAnswer: 'A',
      explanation: 'To prevent dangerous electrical shocks, accidental short-circuits, and component burnout, electrical power sources must always be switched off and isolated before making or changing circuit connections.',
      difficulty: 'easy',
    },
  ],
};
