import fs from 'fs';
import path from 'path';

export interface NewMCQDefinition {
  id: string;
  chapter: string;
  topic: string;
  chapterNumber: number;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const NEW_TEN_MCQS_PER_CHAPTER: Record<string, NewMCQDefinition[]> = {
  'Physical Quantities and Measurement': [
    {
      id: 'fbise9_phy_1_31',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'Which of the following is the fundamental SI base unit used to measure electric current?',
      options: {
        A: 'Ampere ($\\text{A}$)',
        B: 'Coulomb ($\\text{C}$)',
        C: 'Volt ($\\text{V}$)',
        D: 'Ohm ($\\Omega$)',
      },
      correctAnswer: 'A',
      explanation: 'The Ampere (symbol $\\text{A}$) is the fundamental SI base unit of electric current. Coulomb is the derived unit of electric charge ($\\text{C} = \\text{A}\\cdot\\text{s}$), Volt is electric potential, and Ohm is resistance.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_32',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'The diameter of a typical hydrogen atom is approximately $0.0000000001\\text{ m}$. In standard scientific notation, this length is correctly written as:',
      options: {
        A: '$1 \\times 10^{-10}\\text{ m}$',
        B: '$1 \\times 10^{-9}\\text{ m}$',
        C: '$1 \\times 10^{-11}\\text{ m}$',
        D: '$0.1 \\times 10^{-9}\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'In standard scientific notation, numbers are expressed with one non-zero digit before the decimal point: $0.0000000001\\text{ m} = 1 \\times 10^{-10}\\text{ m}$ ($0.1\\text{ nm}$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_33',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'How many picoseconds ($\\text{ps}$) are contained within a time interval of $1\\text{ millisecond}$ ($1\\text{ ms}$)?',
      options: {
        A: '$10^9\\;\\text{ps}$',
        B: '$10^6\\;\\text{ps}$',
        C: '$10^{12}\\;\\text{ps}$',
        D: '$10^3\\;\\text{ps}$',
      },
      correctAnswer: 'A',
      explanation: '$1\\text{ ms} = 10^{-3}\\text{ s}$ and $1\\text{ ps} = 10^{-12}\\text{ s}$. The ratio is $\\frac{10^{-3}\\text{ s}}{10^{-12}\\text{ s}} = 10^{-3 - (-12)} = 10^9\\;\\text{ps}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_34',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'When measuring the volume of mercury in a glass graduated measuring cylinder, parallax error is avoided by reading the scale at the:',
      options: {
        A: 'Highest point of the convex meniscus',
        B: 'Lowest point of the concave meniscus',
        C: 'Midpoint between the top and bottom curved edges',
        D: 'Upper rim of the glass cylinder wall',
      },
      correctAnswer: 'A',
      explanation: 'Mercury has cohesive forces stronger than adhesive forces with glass, forming a convex meniscus (curving upwards). Therefore, the correct reading is taken at the highest point of the convex curve.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_35',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'What is the typical least count (resolution) of a standard digital electronic laboratory stopwatch?',
      options: {
        A: '$0.01\\text{ s}$ ($1/100\\text{th of a second}$)',
        B: '$0.1\\text{ s}$',
        C: '$1.0\\text{ s}$',
        D: '$0.001\\text{ s}$',
      },
      correctAnswer: 'A',
      explanation: 'A standard digital electronic stopwatch can measure time intervals with a least count of $0.01\\text{ s}$ ($1/100\\text{ s}$), whereas mechanical stopwatches typically measure to $0.1\\text{ s}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_36',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'According to the standard rules of significant figures, subtracting a measured length of $4.2\\text{ cm}$ from $15.75\\text{ cm}$ yields what value?',
      options: {
        A: '$11.6\\text{ cm}$',
        B: '$11.55\\text{ cm}$',
        C: '$11.5\\text{ cm}$',
        D: '$12\\text{ cm}$',
      },
      correctAnswer: 'A',
      explanation: 'In significant figures addition and subtraction rules, the result must be rounded to the same number of decimal places as the measurement with the fewest decimal places ($4.2\\text{ cm}$ has 1 decimal place), so $11.55\\text{ cm}$ rounds to $11.6\\text{ cm}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_37',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'In the International System of Units (SI), the base unit assigned to quantify the amount of substance is the:',
      options: {
        A: 'Mole ($\\text{mol}$)',
        B: 'Kilogram ($\\text{kg}$)',
        C: 'Gram ($\\text{g}$)',
        D: 'Candela ($\\text{cd}$)',
      },
      correctAnswer: 'A',
      explanation: 'The mole (symbol $\\text{mol}$) is one of the seven fundamental SI base units, defined to measure the amount of substance containing exactly $6.022 \\times 10^{23}$ elementary entities.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_38',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'When the jaws of a vernier calipers are fully closed, the zero mark of the vernier scale is situated to the left of the main scale zero by 3 divisions (least count $= 0.01\\text{ cm}$). The zero correction ($Z_c$) to apply is:',
      options: {
        A: '$+0.03\\text{ cm}$ (to be added)',
        B: '$-0.03\\text{ cm}$ (to be subtracted)',
        C: '$+0.30\\text{ cm}$',
        D: '$0.00\\text{ cm}$',
      },
      correctAnswer: 'A',
      explanation: 'When the vernier zero lies to the left of the main scale zero, the instrument under-reads, so the zero error is negative ($-0.03\\text{ cm}$). The zero correction is always opposite in sign: $Z_c = +0.03\\text{ cm}$ (added to observed readings).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_1_39',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'In the International System of Units, the standard decimal multiplier prefix "Giga" (symbol $\\text{G}$) represents:',
      options: {
        A: '$10^9$ ($1,000,000,000$)',
        B: '$10^6$',
        C: '$10^{12}$',
        D: '$10^{15}$',
      },
      correctAnswer: 'A',
      explanation: 'The SI prefix Giga ($\\text{G}$) represents a factor of $10^9$ (one billion). Mega ($\\text{M}$) is $10^6$, Tera ($\\text{T}$) is $10^{12}$, and Peta ($\\text{P}$) is $10^{15}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_1_40',
      chapter: 'Physical Quantities and Measurement',
      topic: 'Physical Quantities and Measurement',
      chapterNumber: 1,
      question: 'What is the primary operational function of the ratchet mechanism located at the end of the thimble on a micrometer screw gauge?',
      options: {
        A: 'To apply a uniform, constant pressure on the measured object and avoid over-tightening',
        B: 'To lock the spindle firmly in place after measurement',
        C: 'To zero out the main scale graduations',
        D: 'To magnify the circular scale reading',
      },
      correctAnswer: 'A',
      explanation: 'The ratchet mechanism slips with a clicking sound once the spindle makes contact with the object, ensuring that uniform measuring force is applied and the screw threads or object are not deformed by excessive tightening.',
      difficulty: 'easy',
    },
  ],

  'Kinematics': [
    {
      id: 'fbise9_phy_2_31',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'On a velocity-time graph for a moving body, the geometric area enclosed under the curve represents the:',
      options: {
        A: 'Total displacement (or distance) traveled by the body',
        B: 'Instantaneous acceleration of the body',
        C: 'Total mechanical force applied',
        D: 'Average rate of momentum change',
      },
      correctAnswer: 'A',
      explanation: 'Since velocity $v = \\frac{\\Delta s}{\\Delta t}$, the area under a velocity-time graph equals the product of velocity and time ($v \\times t$), which gives the total displacement or distance traveled.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_32',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'The continuous spinning motion of the blades of a rotating ceiling fan about their fixed central pivot axle is classified as:',
      options: {
        A: 'Rotatory motion',
        B: 'Translatory linear motion',
        C: 'Random motion',
        D: 'Vibratory oscillatory motion',
      },
      correctAnswer: 'A',
      explanation: 'Rotatory motion is defined as the spinning motion of a body about a fixed axis passing through it, such as a ceiling fan, a spinning top, or a steering wheel.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_33',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A flat horizontal line parallel to the time axis on a distance-time graph indicates that the object is:',
      options: {
        A: 'At rest (speed is zero)',
        B: 'Moving with constant high velocity',
        C: 'Accelerating uniformly',
        D: 'Decelerating uniformly',
      },
      correctAnswer: 'A',
      explanation: 'On a distance-time graph, the slope represents speed ($\\text{speed} = \\frac{\\Delta s}{\\Delta t}$). A horizontal line has a slope of zero, meaning the distance does not change over time and the object is at rest.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_34',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A stone is dropped from rest ($v_i = 0$) from the top of a tall bridge into a river. If air resistance is negligible ($g = 10\\text{ m/s}^2$), what vertical distance does it fall in $3\\text{ seconds}$?',
      options: {
        A: '$45\\text{ m}$',
        B: '$30\\text{ m}$',
        C: '$90\\text{ m}$',
        D: '$15\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Using the 2nd equation of motion under gravity: $h = v_i t + \\frac{1}{2}gt^2 = (0)(3) + \\frac{1}{2}(10)(3)^2 = 5 \\times 9 = 45\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_35',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'The continuous, irregular, and zigzag motion of airborne smoke particles or gas molecules is classified as:',
      options: {
        A: 'Random motion',
        B: 'Linear motion',
        C: 'Rotatory motion',
        D: 'Uniform circular motion',
      },
      correctAnswer: 'A',
      explanation: 'Random motion is defined as the disordered, irregular, or zigzag motion of particles in all directions, as exhibited by gas molecules or smoke particles (Brownian motion).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_36',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A sports car travels on a highway at a uniform speed of $72\\text{ km/h}$. Expressed in standard SI units ($\\text{m/s}$), its speed is:',
      options: {
        A: '$20\\text{ m/s}$',
        B: '$25\\text{ m/s}$',
        C: '$15\\text{ m/s}$',
        D: '$30\\text{ m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'To convert $\\text{km/h}$ to $\\text{m/s}$, multiply by $\\frac{1000\\text{ m}}{3600\\text{ s}} = \\frac{5}{18}$. Thus, $72 \\times \\frac{5}{18} = 4 \\times 5 = 20\\text{ m/s}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_37',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'A ball is thrown straight up with an initial speed of $30\\text{ m/s}$ ($g = 10\\text{ m/s}^2$). What maximum height above the release point does the ball reach?',
      options: {
        A: '$45\\text{ m}$',
        B: '$90\\text{ m}$',
        C: '$30\\text{ m}$',
        D: '$60\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'At maximum height, $v_f = 0$. Using $2gh = v_f^2 - v_i^2 \\Rightarrow 2(-10)h = 0 - (30)^2 \\Rightarrow -20h = -900 \\Rightarrow h = \\frac{900}{20} = 45\\text{ m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_2_38',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'Among the following physical quantities in kinematics, which one is a vector quantity?',
      options: {
        A: 'Displacement',
        B: 'Distance',
        C: 'Speed',
        D: 'Time interval',
      },
      correctAnswer: 'A',
      explanation: 'Displacement is the shortest distance between two points in a specified direction, making it a vector quantity. Distance, speed, and time are scalar quantities specified completely by magnitude alone.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_39',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'When the velocity of a moving object decreases steadily with time, the acceleration produced is called:',
      options: {
        A: 'Deceleration (or negative acceleration / retardation)',
        B: 'Positive uniform acceleration',
        C: 'Centripetal acceleration',
        D: 'Zero acceleration',
      },
      correctAnswer: 'A',
      explanation: 'Negative acceleration occurs when velocity decreases with time, acting in the direction opposite to the motion of the body; it is also termed deceleration or retardation.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_2_40',
      chapter: 'Kinematics',
      topic: 'Kinematics',
      chapterNumber: 2,
      question: 'An object travels $30\\text{ m}$ due East in $4\\text{ s}$ and then $40\\text{ m}$ due North in $6\\text{ s}$. The magnitude of the net displacement of the object is:',
      options: {
        A: '$50\\text{ m}$',
        B: '$70\\text{ m}$',
        C: '$10\\text{ m}$',
        D: '$35\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'Because East and North are perpendicular ($90^\\circ$), by the Pythagorean theorem the net displacement is $s = \\sqrt{(30\\text{ m})^2 + (40\\text{ m})^2} = \\sqrt{900 + 1600} = \\sqrt{2500} = 50\\text{ m}$.',
      difficulty: 'medium',
    },
  ],

  'Dynamics – I': [
    {
      id: 'fbise9_phy_3_31',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'According to Newton’s Second Law of Motion ($F = ma$), what net unbalanced force is required to produce an acceleration of $4\\text{ m/s}^2$ in a cart of mass $5\\text{ kg}$?',
      options: {
        A: '$20\\text{ N}$',
        B: '$1.25\\text{ N}$',
        C: '$9\\text{ N}$',
        D: '$40\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'By Newton\'s Second Law: $F = ma = 5\\text{ kg} \\times 4\\text{ m/s}^2 = 20\\text{ N}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_32',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'A physical body continues in its state of rest or of uniform motion in a straight line unless acted upon by an external net force. This fundamental law is known as:',
      options: {
        A: 'Newton’s First Law of Motion (Law of Inertia)',
        B: 'Newton’s Second Law of Motion',
        C: 'Newton’s Third Law of Motion',
        D: 'The Law of Gravitation',
      },
      correctAnswer: 'A',
      explanation: 'Newton’s First Law of Motion states that an object remains at rest or in uniform straight motion unless compelled to change that state by an external unbalanced force. It is also called the Law of Inertia.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_33',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'If the cable supporting an elevator snaps and the cabin falls freely under Earth\'s gravity ($a = g$), what apparent weight will a passenger of mass $70\\text{ kg}$ experience?',
      options: {
        A: '$0\\text{ N}$ (state of apparent weightlessness)',
        B: '$700\\text{ N}$',
        C: '$1400\\text{ N}$',
        D: '$350\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'In free fall, the downward acceleration of the elevator is $a = g$. The scale reaction / apparent weight is $R = m(g - a) = m(g - g) = 0\\text{ N}$, producing a condition of apparent weightlessness.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_34',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'Mass of an object is measured using a beam balance, whereas the gravitational weight of an object is measured using a:',
      options: {
        A: 'Spring balance',
        B: 'Graduated cylinder',
        C: 'Mercury barometer',
        D: 'Measuring tape',
      },
      correctAnswer: 'A',
      explanation: 'A spring balance measures the gravitational force (weight) acting on an object based on spring extension ($F = kx$), whereas a physical beam balance compares unknown mass with standard masses independent of local gravity.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_35',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'If the net resultant force applied to an object is doubled ($F \\rightarrow 2F$) while its mass is halved ($m \\rightarrow m/2$), the resulting acceleration will:',
      options: {
        A: 'Increase by a factor of $4$ (quadruple)',
        B: 'Double (factor of $2$)',
        C: 'Remain unchanged',
        D: 'Be halved',
      },
      correctAnswer: 'A',
      explanation: 'From Newton\'s second law, $a = \\frac{F}{m}$. When force is $2F$ and mass is $m/2$, $a\' = \\frac{2F}{m/2} = 4\\left(\\frac{F}{m}\\right) = 4a$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_36',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'The inertia of a physical body (its resistance to changes in its state of rest or uniform motion) depends solely on its:',
      options: {
        A: 'Mass',
        B: 'Volume',
        C: 'Velocity',
        D: 'Surface area',
      },
      correctAnswer: 'A',
      explanation: 'Mass is the quantitative measure of a body\'s inertia. A more massive body requires a greater force to change its state of motion or rest.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_37',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'A rocket propels itself forward in space according to Newton’s Third Law of Motion because:',
      options: {
        A: 'The high-speed backward expulsion of exhaust gases exerts an equal and opposite forward reaction force on the rocket',
        B: 'The rocket pushes against atmospheric air particles',
        C: 'Gravitational attraction pulls the rocket into orbit',
        D: 'The exhaust gases become lighter than space vacuum',
      },
      correctAnswer: 'A',
      explanation: 'By Newton’s Third Law, when rocket engines exert a backward force expelling hot combustion gases, the escaping gases exert an equal and opposite forward reaction force on the combustion chamber.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_38',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'When a stone of mass $12\\text{ kg}$ is transported from the surface of Earth to the Moon ($g_{\\text{Moon}} = \\frac{1}{6}g_{\\text{Earth}}$), which of its fundamental physical properties remains completely invariant and unchanged?',
      options: {
        A: 'Its mass ($12\\text{ kg}$)',
        B: 'Its gravitational weight ($120\\text{ N}$)',
        C: 'Its surface contact pressure',
        D: 'Its escape velocity from the surface',
      },
      correctAnswer: 'A',
      explanation: 'Mass is an intrinsic quantitative property of matter representing its inertia and remains strictly constant everywhere ($12\\text{ kg}$), whereas weight depends on local gravitational field strength ($W = mg$) and is reduced by six-fold on the Moon.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_3_39',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'When a passenger steps out of a moving bus onto the ground, he tends to fall forward in the direction of motion primarily because:',
      options: {
        A: 'His feet come to rest upon touching the ground while his upper body continues moving forward due to inertia',
        B: 'Gravity pulls him forward',
        C: 'Friction pushes his entire body forward',
        D: 'Air drag pulls his shoulders forward',
      },
      correctAnswer: 'A',
      explanation: 'When feet contact the stationary ground, they are brought to rest by friction, but the upper body continues in forward motion due to inertia of motion, causing the passenger to stumble forward.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_3_40',
      chapter: 'Dynamics – I',
      topic: 'Dynamics – I',
      chapterNumber: 3,
      question: 'A mass $m$ is suspended at rest by a vertical light rope. The tension force ($T$) developed in the rope is:',
      options: {
        A: 'Equal in magnitude and opposite in direction to the gravitational weight ($T = mg$)',
        B: 'Twice the gravitational weight ($T = 2mg$)',
        C: 'Half the gravitational weight ($T = 0.5mg$)',
        D: 'Zero ($T = 0\\text{ N}$)',
      },
      correctAnswer: 'A',
      explanation: 'For a body at rest in equilibrium, net vertical force is zero ($\\Sigma F_y = 0 \\Rightarrow T - W = 0 \\Rightarrow T = W = mg$). Tension balances the gravitational weight.',
      difficulty: 'easy',
    },
  ],

  'Dynamics – II': [
    {
      id: 'fbise9_phy_4_31',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'Why are the outer tracks of railways and sharp curves of modern high-speed highways banked (elevated):',
      options: {
        A: 'To provide a component of the normal reaction force towards the center, supplying the necessary centripetal force',
        B: 'To decrease the mass of the turning vehicles',
        C: 'To increase rolling friction to maximum',
        D: 'To stop the vehicle automatically',
      },
      correctAnswer: 'A',
      explanation: 'Banking of roads tilts the normal reaction force so that its horizontal component ($R\\sin\\theta$) provides the required centripetal force ($F_c = \\frac{mv^2}{r}$), preventing vehicles from skidding without relying exclusively on tire friction.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_32',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'An athlete of mass $70\\text{ kg}$ sprints along a straight track at a velocity of $8\\text{ m/s}$. What is the magnitude of the athlete’s linear momentum?',
      options: {
        A: '$560\\text{ kg}\\cdot\\text{m/s}$ (or $560\\text{ N}\\cdot\\text{s}$)',
        B: '$280\\text{ kg}\\cdot\\text{m/s}$',
        C: '$78\\text{ kg}\\cdot\\text{m/s}$',
        D: '$1120\\text{ kg}\\cdot\\text{m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'Momentum $p = mv = 70\\text{ kg} \\times 8\\text{ m/s} = 560\\text{ kg}\\cdot\\text{m/s} = 560\\text{ N}\\cdot\\text{s}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_33',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'In SI units, the coefficient of friction ($\\mu = F_s / R$) between two solid surfaces is expressed in:',
      options: {
        A: 'No units (it is a dimensionless ratio)',
        B: 'Newtons ($\\text{N}$)',
        C: '$\\text{N/m}$',
        D: '$\\text{kg}\\cdot\\text{m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'The coefficient of friction is the ratio of limiting frictional force to the normal reaction force ($\\mu = F_s / R$). Since it is a ratio of two forces, it has no units and is dimensionless.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_34',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'A cricket fielder pulls his hands backward while catching a fast-moving ball in order to:',
      options: {
        A: 'Increase the collision time interval, thereby decreasing the impact force exerted on his hands',
        B: 'Increase the momentum of the ball',
        C: 'Decrease the total time of the catch',
        D: 'Increase the reaction force on the ball',
      },
      correctAnswer: 'A',
      explanation: 'From $F = \\frac{\\Delta p}{\\Delta t}$, increasing the time interval $\\Delta t$ during which the ball is brought to rest decreases the rate of change of momentum, significantly reducing the impact force on the hands.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_35',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'In a medical laboratory centrifuge or cream separator, denser components separate to the outer perimeter of the spinning bowl because:',
      options: {
        A: 'Denser particles have greater inertia and require a larger centripetal force than the surrounding fluid can provide',
        B: 'Denser particles have zero mass in circular motion',
        C: 'The centrifuge eliminates Earth\'s gravity',
        D: 'Lighter particles experience greater gravitational pull',
      },
      correctAnswer: 'A',
      explanation: 'Denser particles have greater mass, thus requiring a larger centripetal force ($F_c = \\frac{mv^2}{r}$). Because the fluid cannot supply this force, they move outward to the bottom and perimeter of the spinning tubes.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_36',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'The physical quantity defined as the product of an applied force ($F$) and the brief time duration ($\\Delta t$) for which it acts ($J = F \\times \\Delta t$) is the:',
      options: {
        A: 'Impulse of the force',
        B: 'Inertia',
        C: 'Centripetal acceleration',
        D: 'Friction coefficient',
      },
      correctAnswer: 'A',
      explanation: 'Impulse is defined as $J = F \\times \\Delta t$. By the impulse-momentum theorem, impulse equals the total change in linear momentum ($\\Delta p$) produced in the body.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_37',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'The relationship connecting the kinetic energy ($E_k$) of a moving body of mass $m$ with its linear momentum ($p$) is:',
      options: {
        A: '$E_k = \\frac{p^2}{2m}$',
        B: '$E_k = \\frac{2m}{p^2}$',
        C: '$E_k = \\frac{p}{2m}$',
        D: '$E_k = 2m p^2$',
      },
      correctAnswer: 'A',
      explanation: 'Since $p = mv \\Rightarrow v = \\frac{p}{m}$, substituting into kinetic energy gives $E_k = \\frac{1}{2}mv^2 = \\frac{1}{2}m\\left(\\frac{p}{m}\\right)^2 = \\frac{p^2}{2m}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_4_38',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'When a car navigates a level, unbanked curved road, what physical force supplies the necessary centripetal force to keep it in the turn?',
      options: {
        A: 'Static friction between the car tires and the road surface',
        B: 'The forward driving force of the engine',
        C: 'The aerodynamic downward lift of the chassis',
        D: 'The gravitational weight of the vehicle',
      },
      correctAnswer: 'A',
      explanation: 'On a flat, horizontal circular curve, the centripetal force ($F_c = \\frac{mv^2}{r}$) is supplied entirely by the lateral static friction force between the road surface and the tires.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_4_39',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'A bullet of mass $0.02\\text{ kg}$ is fired horizontally at $300\\text{ m/s}$ from a rifle of mass $3\\text{ kg}$. What is the recoil velocity of the rifle?',
      options: {
        A: '$-2\\text{ m/s}$ ($2\\text{ m/s}$ in the backward direction)',
        B: '$-6\\text{ m/s}$',
        C: '$-0.2\\text{ m/s}$',
        D: '$-3\\text{ m/s}$',
      },
      correctAnswer: 'A',
      explanation: 'By the Law of Conservation of Momentum: $m_b v_b + m_g v_g = 0 \\Rightarrow (0.02)(300) + (3)v_g = 0 \\Rightarrow 6 + 3v_g = 0 \\Rightarrow v_g = -\\frac{6}{3} = -2\\text{ m/s}$.',
      difficulty: 'hard',
    },
    {
      id: 'fbise9_phy_4_40',
      chapter: 'Dynamics – II',
      topic: 'Dynamics – II',
      chapterNumber: 4,
      question: 'Rolling friction is significantly smaller than sliding friction primarily because:',
      options: {
        A: 'The microscopic contact points between a rolling wheel and the surface experience negligible sliding or abrasive rubbing',
        B: 'Rolling objects experience zero gravitational pull',
        C: 'The normal reaction force vanishes during rolling',
        D: 'The coefficient of rolling friction is always negative',
      },
      correctAnswer: 'A',
      explanation: 'In rolling motion, contact with the ground occurs instantaneously along a small contact patch without relative sliding, so microscopic surface interlocks do not rupture abrasively.',
      difficulty: 'easy',
    },
  ],

  'Pressure and Deformation in Solids': [
    {
      id: 'fbise9_phy_5_31',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'A solid metal block of volume $0.002\\text{ m}^3$ is completely submerged in water (density $= 1000\\text{ kg/m}^3$, $g = 10\\text{ m/s}^2$). According to Archimedes’ Principle, what buoyant upthrust force acts on the block?',
      options: {
        A: '$20\\text{ N}$',
        B: '$2\\text{ N}$',
        C: '$200\\text{ N}$',
        D: '$5\\text{ N}$',
      },
      correctAnswer: 'A',
      explanation: 'By Archimedes’ Principle, Upthrust $F_B = \\rho V g = 1000\\text{ kg/m}^3 \\times 0.002\\text{ m}^3 \\times 10\\text{ m/s}^2 = 20\\text{ N}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_32',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'A person of weight $600\\text{ N}$ stands on one stiletto heel having a tip area of $1\\text{ cm}^2$ ($10^{-4}\\text{ m}^2$). What pressure is exerted on the floor beneath the heel?',
      options: {
        A: '$6,000,000\\text{ Pa}$ ($6\\text{ MPa}$)',
        B: '$60,000\\text{ Pa}$',
        C: '$600\\text{ Pa}$',
        D: '$600,000\\text{ Pa}$',
      },
      correctAnswer: 'A',
      explanation: 'Pressure $P = \\frac{F}{A} = \\frac{600\\text{ N}}{10^{-4}\\text{ m}^2} = 600 \\times 10^4\\text{ Pa} = 6 \\times 10^6\\text{ Pa} = 6\\text{ MPa}$. Small surface area concentrates force into huge pressure.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_33',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'The hydraulic brake system of an automobile operates based on which fundamental principle of fluid physics?',
      options: {
        A: 'Pascal’s Principle',
        B: 'Archimedes’ Principle',
        C: 'Hooke’s Law',
        D: 'Bernoulli’s Theorem',
      },
      correctAnswer: 'A',
      explanation: 'Pascal’s Principle states that pressure applied to an enclosed liquid is transmitted equally in all directions, allowing the master cylinder pressure to act uniformly on all wheel brake pads.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_34',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'In the study of elasticity, tensile stress is defined as:',
      options: {
        A: 'The deforming force applied per unit cross-sectional area ($\\sigma = F/A$)',
        B: 'The fractional change in length per unit original length',
        C: 'The product of force and extension',
        D: 'The spring constant divided by applied load',
      },
      correctAnswer: 'A',
      explanation: 'Tensile stress is the internal restoring/deforming force acting perpendicular per unit cross-sectional area ($\\sigma = \\frac{F}{A}$), measured in $\\text{N/m}^2$ or Pascals ($\\text{Pa}$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_35',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'Tensile strain ($\\Delta L / L_0$) is a physical quantity that has:',
      options: {
        A: 'No units (it is a pure dimensionless ratio)',
        B: 'Units of meters ($\\text{m}$)',
        C: 'Units of Pascals ($\\text{Pa}$)',
        D: 'Units of Newtons per meter ($\\text{N/m}$)',
      },
      correctAnswer: 'A',
      explanation: 'Tensile strain is the ratio of change in length ($\\Delta L$) to original length ($L_0$). Because both quantities are lengths measured in meters, the units cancel out, leaving strain dimensionless.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_36',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'Why does atmospheric pressure decrease steadily as altitude above sea level increases?',
      options: {
        A: 'The vertical column of air above decreases in height and atmospheric air density decreases with altitude',
        B: 'The temperature drops below absolute zero',
        C: 'Earth’s magnetic field shields high altitude air',
        D: 'Air speed at high altitude increases to infinity',
      },
      correctAnswer: 'A',
      explanation: 'Atmospheric pressure is caused by the weight of air above a given level. As altitude rises, the overlying column of air becomes shorter and the air becomes less dense, reducing pressure.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_37',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'In a standard Torricellian mercury barometer, the empty space above the mercury column inside the sealed glass tube is called:',
      options: {
        A: 'Torricellian vacuum',
        B: 'Compressed air chamber',
        C: 'Pascal pocket',
        D: 'Hydraulic chamber',
      },
      correctAnswer: 'A',
      explanation: 'The space above the mercury column contains no air, only a negligible trace of mercury vapor, and is known as the Torricellian vacuum.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_5_38',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'Within the elastic limit of a solid wire, the constant ratio of tensile stress to tensile strain is called:',
      options: {
        A: 'Young’s Modulus of elasticity ($Y = \\frac{\\text{Stress}}{\\text{Strain}}$)',
        B: 'Bulk modulus',
        C: 'Spring stiffness constant',
        D: 'Tensile yield strength',
      },
      correctAnswer: 'A',
      explanation: 'Young’s Modulus ($Y = \\frac{\\sigma}{\\epsilon} = \\frac{F \\cdot L_0}{A \\cdot \\Delta L}$) is the ratio of tensile stress to tensile strain within the elastic limit, measured in $\\text{N/m}^2$ or Pascals ($\\text{Pa}$).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_39',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'A large ocean liner made of dense steel floats on seawater because:',
      options: {
        A: 'Its hollow hull encloses a vast volume of air, making its overall average density less than that of seawater',
        B: 'Steel is naturally less dense than water',
        C: 'Atmospheric pressure pulls the ship upward',
        D: 'Surface tension of sea water repels steel',
      },
      correctAnswer: 'A',
      explanation: 'By the Law of Flotation, because of the ship’s hollow structure containing air, the ship’s total weight equals the weight of the water displaced by its submerged hull, keeping its average density below that of seawater.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_5_40',
      chapter: 'Pressure and Deformation in Solids',
      topic: 'Pressure and Deformation in Solids',
      chapterNumber: 5,
      question: 'Liquid pressure at a given depth $h$ in a stationary fluid depends only on depth, liquid density, and gravity ($P = \\rho gh$). This means liquid pressure is independent of the:',
      options: {
        A: 'Shape and cross-sectional area of the container (Hydrostatic paradox)',
        B: 'Density of the liquid',
        C: 'Vertical depth below the surface',
        D: 'Gravitational acceleration',
      },
      correctAnswer: 'A',
      explanation: 'Hydrostatic pressure depends solely on depth $h$, liquid density $\\rho$, and $g$. It does not depend on the shape, volume, or base area of the container.',
      difficulty: 'easy',
    },
  ],

  'Work and Energy': [
    {
      id: 'fbise9_phy_6_31',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'What is the work done by the centripetal force on an object moving with constant speed in a circular orbit?',
      options: {
        A: '$0\\text{ J}$ (zero Joules)',
        B: '$\\frac{1}{2}mv^2$',
        C: '$mgh$',
        D: '$F_c \\times 2\\pi r$',
      },
      correctAnswer: 'A',
      explanation: 'Work $W = F s \\cos\\theta$. The centripetal force acts towards the center while displacement is along the tangent, making $\\theta = 90^\\circ$. Since $\\cos 90^\\circ = 0$, work done is strictly $0\\text{ J}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_32',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'A mass of $4\\text{ kg}$ is lifted vertically through a height of $5\\text{ m}$ above the floor ($g = 10\\text{ m/s}^2$). What gravitational potential energy does it gain?',
      options: {
        A: '$200\\text{ J}$',
        B: '$20\\text{ J}$',
        C: '$100\\text{ J}$',
        D: '$400\\text{ J}$',
      },
      correctAnswer: 'A',
      explanation: 'Gravitational Potential Energy $E_p = mgh = 4\\text{ kg} \\times 10\\text{ m/s}^2 \\times 5\\text{ m} = 200\\text{ J}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_33',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'Geothermal energy is an important renewable energy resource derived from:',
      options: {
        A: 'Natural heat energy trapped deep within the Earth’s molten interior and rock strata',
        B: 'Tidal gravitational pull of the Moon on oceans',
        C: 'Nuclear decay in high-altitude clouds',
        D: 'Direct sunlight trapped in photovoltaic arrays',
      },
      correctAnswer: 'A',
      explanation: 'Geothermal energy is thermal energy generated and stored inside the Earth, originating from radioactive decay of minerals and heat from Earth\'s core, tapped as steam to generate electricity.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_34',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'In Albert Einstein’s mass-energy equivalence equation ($E = mc^2$), the symbol $c$ represents the:',
      options: {
        A: 'Speed of light in vacuum ($3 \\times 10^8\\text{ m/s}$)',
        B: 'Speed of sound in air',
        C: 'Specific heat capacity of matter',
        D: 'Centripetal acceleration constant',
      },
      correctAnswer: 'A',
      explanation: 'In $E = mc^2$, $c$ is the universal constant representing the speed of light in vacuum ($c \\approx 3 \\times 10^8\\text{ m/s}$).',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_35',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'If the velocity of a moving car is doubled ($v \\rightarrow 2v$), by what factor does its kinetic energy increase?',
      options: {
        A: 'Increases by a factor of $4$ (quadruples)',
        B: 'Doubles (factor of $2$)',
        C: 'Increases by a factor of $8$',
        D: 'Remains unchanged',
      },
      correctAnswer: 'A',
      explanation: 'Since $E_k = \\frac{1}{2}mv^2$, kinetic energy is proportional to the square of velocity ($E_k \\propto v^2$). Doubling velocity increases kinetic energy by $(2)^2 = 4$ times.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_36',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'In a hydroelectric power station or wind turbine, the electric generator operates by converting:',
      options: {
        A: 'Mechanical kinetic energy into electrical energy',
        B: 'Chemical energy into nuclear energy',
        C: 'Thermal heat into sound waves',
        D: 'Light energy into chemical bonds',
      },
      correctAnswer: 'A',
      explanation: 'In hydro and wind installations, moving water or wind turns turbine blades, providing mechanical shaft kinetic energy that spins generators to produce electrical energy.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_37',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'An electric crane lifts a heavy construction crate weighing $2000\\text{ N}$ to a height of $15\\text{ m}$ in $10\\text{ seconds}$. What is the average power output of the crane?',
      options: {
        A: '$3000\\text{ W}$ ($3\\text{ kW}$)',
        B: '$30,000\\text{ W}$',
        C: '$1500\\text{ W}$',
        D: '$750\\text{ W}$',
      },
      correctAnswer: 'A',
      explanation: 'Work done $W = F \\times s = 2000\\text{ N} \\times 15\\text{ m} = 30,000\\text{ J}$. Power $P = \\frac{W}{t} = \\frac{30,000\\text{ J}}{10\\text{ s}} = 3000\\text{ W} = 3\\text{ kW}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_6_38',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'Photovoltaic solar panels directly convert incoming solar radiant energy into:',
      options: {
        A: 'Electrical energy',
        B: 'Nuclear energy',
        C: 'Chemical potential energy',
        D: 'Gravitational potential energy',
      },
      correctAnswer: 'A',
      explanation: 'Solar photovoltaic cells utilize semiconductor materials (like silicon) to absorb sunlight photons and convert radiant light energy directly into electrical energy.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_39',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'The mechanical energy stored in a compressed or stretched spring of spring constant $k$ extended by $x$ is:',
      options: {
        A: 'Elastic potential energy ($E_p = \\frac{1}{2}kx^2$)',
        B: 'Gravitational potential energy ($E_p = mgh$)',
        C: 'Kinetic energy ($E_k = \\frac{1}{2}mv^2$)',
        D: 'Thermal internal energy ($Q = mc\\Delta T$)',
      },
      correctAnswer: 'A',
      explanation: 'The work done in deforming an elastic spring within its elastic limit is stored as elastic potential energy, given by $E_p = \\frac{1}{2}kx^2$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_6_40',
      chapter: 'Work and Energy',
      topic: 'Work and Energy',
      chapterNumber: 6,
      question: 'Biomass is a renewable energy resource obtained by utilizing:',
      options: {
        A: 'Organic plant material, agricultural crop waste, animal dung, and wood',
        B: 'Radioactive decay of enriched uranium rods',
        C: 'Geological crude oil deposits',
        D: 'Deep subterranean volcanic lava magma',
      },
      correctAnswer: 'A',
      explanation: 'Biomass refers to organic matter from plants, animals, agricultural residues, and wood waste that can be converted directly into heat, electricity, or biofuels (like biogas).',
      difficulty: 'easy',
    },
  ],

  'Density and Temperature': [
    {
      id: 'fbise9_phy_7_31',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Absolute zero ($0\\text{ K}$ on the Kelvin thermodynamic temperature scale) corresponds on the Celsius scale to:',
      options: {
        A: '$-273.15^\\circ\\text{C}$ (or $-273^\\circ\\text{C}$)',
        B: '$0^\\circ\\text{C}$',
        C: '$-100^\\circ\\text{C}$',
        D: '$-460^\\circ\\text{C}$',
      },
      correctAnswer: 'A',
      explanation: 'Kelvin temperature is related to Celsius by $T(\\text{K}) = T(^\\circ\\text{C}) + 273.15$. Setting $T(\\text{K}) = 0$ gives $T(^\\circ\\text{C}) = -273.15^\\circ\\text{C}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_32',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A section of steel railway track has an initial length of $100\\text{ m}$. When the ambient temperature rises by $20^\\circ\\text{C}$ (coefficient of linear expansion $\\alpha = 1.1 \\times 10^{-5}\\text{ K}^{-1}$), the thermal linear expansion $\\Delta L$ is:',
      options: {
        A: '$0.022\\text{ m}$ ($2.2\\text{ cm}$)',
        B: '$0.22\\text{ m}$',
        C: '$0.0022\\text{ m}$',
        D: '$2.2\\text{ m}$',
      },
      correctAnswer: 'A',
      explanation: 'By the linear expansion formula: $\\Delta L = \\alpha L_0 \\Delta T = (1.1 \\times 10^{-5}\\text{ K}^{-1})(100\\text{ m})(20\\text{ K}) = 0.022\\text{ m} = 2.2\\text{ cm}$.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_33',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A bimetallic strip used in thermostats and fire alarms bends when heated because:',
      options: {
        A: 'The two bonded metals have different coefficients of linear thermal expansion',
        B: 'One metal becomes magnetic while the other remains non-magnetic',
        C: 'One metal melts while the other freezes',
        D: 'Thermal insulation cools the inner strip surface',
      },
      correctAnswer: 'A',
      explanation: 'A bimetallic strip consists of two dissimilar metal strips (e.g. brass and iron) welded together. Because brass expands more than iron for the same temperature rise, the strip bends into an arc towards the metal with lower expansion.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_34',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'The specific latent heat of vaporization of water ($L_v \\approx 2.26 \\times 10^6\\text{ J/kg}$) is the thermal energy required to:',
      options: {
        A: 'Change $1\\text{ kg}$ of boiling water into steam at its boiling point ($100^\\circ\\text{C}$) without any change in temperature',
        B: 'Raise the temperature of $1\\text{ kg}$ of water by $1^\\circ\\text{C}$',
        C: 'Melt $1\\text{ kg}$ of solid ice into water at $0^\\circ\\text{C}$',
        D: 'Cool $1\\text{ kg}$ of steam to liquid water at room temperature',
      },
      correctAnswer: 'A',
      explanation: 'Specific latent heat of vaporization ($L_v$) is defined as the quantity of heat energy required to change unit mass ($1\\text{ kg}$) of a liquid into gas at its boiling point without any change in temperature.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_35',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Due to the anomalous thermal expansion of water, when water is cooled from $4^\\circ\\text{C}$ down to $0^\\circ\\text{C}$, its volume:',
      options: {
        A: 'Expands (and its density decreases)',
        B: 'Contracts (and its density increases)',
        C: 'Remains completely constant',
        D: 'Drops to zero',
      },
      correctAnswer: 'A',
      explanation: 'Unlike typical liquids, water expands when cooled from $4^\\circ\\text{C}$ to $0^\\circ\\text{C}$ (anomalous expansion), causing ice and cold water below $4^\\circ\\text{C}$ to be less dense and float on top of lakes.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_7_36',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A clinical mercury-in-glass thermometer is engineered with a sharp capillary constriction (kink) just above the bulb primarily in order to:',
      options: {
        A: 'Prevent the thermometric mercury column from contracting back into the bulb before the reading can be noted',
        B: 'Accelerate the heating of mercury in the bulb',
        C: 'Allow the thermometer to withstand boiling water',
        D: 'Magnify the glass stem diameter',
      },
      correctAnswer: 'A',
      explanation: 'The narrow constriction prevents the mercury thread from falling back when the thermometer is removed from the patient’s body, allowing accurate reading of maximum body temperature until shaken down.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_37',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'The heat capacity ($C$) of an entire physical body of mass $m$ and specific heat capacity $c$ is given by the formula:',
      options: {
        A: '$C = m \\times c$',
        B: '$C = \\frac{m}{c}$',
        C: '$C = \\frac{c}{m}$',
        D: '$C = m \\times c \\times \\Delta T$',
      },
      correctAnswer: 'A',
      explanation: 'Heat capacity is the thermal energy needed to raise the temperature of the entire body by $1\\text{ K}$ (or $1^\\circ\\text{C}$), defined as $C = \\frac{Q}{\\Delta T} = mc$, with SI unit $\\text{J/K}$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_38',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'Which of the following environmental factors will INCREASE the rate of evaporation of a liquid from an open container?',
      options: {
        A: 'Increasing the exposed liquid surface area and increasing temperature',
        B: 'Increasing ambient air humidity',
        C: 'Decreasing ambient wind speed',
        D: 'Covering the container with an airtight lid',
      },
      correctAnswer: 'A',
      explanation: 'Evaporation rate increases with larger surface area, higher liquid temperature, higher wind speed over the surface, and lower ambient humidity.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_39',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A solid copper sample has a measured density of $8.9\\text{ g/cm}^3$. Expressed in standard SI units ($\\text{kg/m}^3$), its density is:',
      options: {
        A: '$8,900\\text{ kg/m}^3$',
        B: '$890\\text{ kg/m}^3$',
        C: '$89,000\\text{ kg/m}^3$',
        D: '$0.0089\\text{ kg/m}^3$',
      },
      correctAnswer: 'A',
      explanation: 'Since $1\\text{ g/cm}^3 = \\frac{10^{-3}\\text{ kg}}{10^{-6}\\text{ m}^3} = 1000\\text{ kg/m}^3$, multiplying $8.9\\text{ g/cm}^3 \\times 1000 = 8900\\text{ kg/m}^3$.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_7_40',
      chapter: 'Density and Temperature',
      topic: 'Density and Temperature',
      chapterNumber: 7,
      question: 'A thermocouple thermometer measures rapid temperature changes based on what thermometric property?',
      options: {
        A: 'The thermoelectric electromotive force (voltage) produced across two junctions of dissimilar metals kept at different temperatures (Seebeck effect)',
        B: 'The volumetric expansion of liquid mercury in a glass bore',
        C: 'The change in electrical resistance of a copper wire',
        D: 'The pressure variation of an ideal gas at constant volume',
      },
      correctAnswer: 'A',
      explanation: 'A thermocouple consists of two dissimilar metallic wires joined at two junctions; when the junctions are at different temperatures, a temperature-dependent voltage (thermoelectric EMF) is generated (Seebeck effect).',
      difficulty: 'medium',
    },
  ],

  'Magnetism': [
    {
      id: 'fbise9_phy_8_31',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Hans Christian Oersted experimentally discovered that an electric current creates a magnetic field when he observed that:',
      options: {
        A: 'A nearby magnetic compass needle deflected whenever an electric current passed through a nearby wire',
        B: 'An electric charge was created on a dry glass rod',
        C: 'A bar magnet fell faster through an empty glass tube',
        D: 'Iron filings melted when touched with a wire',
      },
      correctAnswer: 'A',
      explanation: 'In 1820, Oersted discovered electromagnetism by noticing that a current-carrying wire deflected a nearby magnetic compass needle, proving that electric currents produce surrounding magnetic fields.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_32',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'The angle of dip (or magnetic inclination) made by the Earth’s total magnetic field vector with the horizontal plane at the Earth’s magnetic equator is:',
      options: {
        A: '$0^\\circ$',
        B: '$90^\\circ$',
        C: '$45^\\circ$',
        D: '$180^\\circ$',
      },
      correctAnswer: 'A',
      explanation: 'At the Earth\'s magnetic equator, the Earth’s magnetic field lines are parallel to the horizontal surface, so the angle of dip is $0^\\circ$. At the magnetic poles, the field lines are vertical (dip $= 90^\\circ$).',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_33',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'A permanent bar magnet can be demagnetized effectively using an electrical method by:',
      options: {
        A: 'Placing it inside a solenoid connected to an alternating current (AC) source oriented East-West and slowly withdrawing it',
        B: 'Connecting both ends of the magnet directly to a direct current (DC) battery',
        C: 'Submerging the magnet in ice-cold salt water',
        D: 'Wrapping the magnet in plastic insulation',
      },
      correctAnswer: 'A',
      explanation: 'Alternating current (AC) reverses magnetic field direction rapidly. Slowly withdrawing the magnet while the AC field decays leaves the magnetic domains randomly oriented, resulting in complete demagnetization.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_34',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'In the magnetic field mapping around a permanent bar magnet placed on a table, "Neutral Points" are specific points where:',
      options: {
        A: 'The magnetic field of the bar magnet is equal in magnitude and opposite in direction to the Earth’s horizontal magnetic field, resulting in a net magnetic field of zero',
        B: 'The magnetic field strength reaches its absolute maximum value',
        C: 'A compass needle spins continuously at high speed',
        D: 'Magnetic field lines cross and intersect each other',
      },
      correctAnswer: 'A',
      explanation: 'Neutral points are locations where the magnet’s magnetic field exactly cancels out the Earth’s horizontal magnetic field ($B_{\\text{magnet}} = B_{\\text{Earth}}$ in opposite directions), so the net magnetic field is zero.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_35',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'When the North pole of a permanent bar magnet is brought close to (without touching) one end of an unmagnetized soft iron bar, the nearer end of the iron bar acquires an:',
      options: {
        A: 'Induced South pole (and is attracted)',
        B: 'Induced North pole (and is repelled)',
        C: 'Permanent North pole',
        D: 'Electric positive charge',
      },
      correctAnswer: 'A',
      explanation: 'By magnetic induction, magnetic domains in the soft iron align so that an opposite pole (South pole) is induced at the nearer end, creating an attractive magnetic force.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_36',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Which of the following alloys is categorized as a "hard magnetic material" suitable for manufacturing strong, long-lasting permanent magnets?',
      options: {
        A: 'Alnico (alloy of aluminum, nickel, and cobalt)',
        B: 'Soft annealed iron',
        C: 'Pure electrolytic copper',
        D: 'Zinc-coated galvanized sheet',
      },
      correctAnswer: 'A',
      explanation: 'Alnico, steel, and neodymium alloys are magnetically hard materials with high retentivity and coercivity, retaining strong magnetization permanently.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_37',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'The pattern of magnetic field lines produced around a long, straight conductor carrying a steady electric current consists of:',
      options: {
        A: 'Concentric circles centered on the wire axis in planes perpendicular to the wire',
        B: 'Straight parallel lines radiating outwards away from the wire',
        C: 'Helical spirals traveling along the length of the wire',
        D: 'Elliptical loops parallel to the conductor',
      },
      correctAnswer: 'A',
      explanation: 'The magnetic field of a straight current-carrying wire forms concentric circular field lines centered on the wire, whose direction is determined by the Right-Hand Grip Rule.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_38',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'In a magnetic field diagram of a permanent bar magnet, as the distance from the magnetic pole increases, the field lines become wider apart, indicating that:',
      options: {
        A: 'The magnetic field strength decreases steadily with increasing distance',
        B: 'The magnetic field becomes uniform and constant',
        C: 'The polarity of the magnet reverses spontaneously',
        D: 'The field lines cross one another',
      },
      correctAnswer: 'A',
      explanation: 'The density/closeness of magnetic field lines is directly proportional to the magnetic field strength. Closer lines near poles represent strong magnetic field; widening lines indicate weakening field strength.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_8_39',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'In an electric bell mechanism, the continuous ringing action when the push-button switch is held down occurs because of the:',
      options: {
        A: 'Make-and-break contact screw that repeatedly completes and interrupts the electromagnet circuit',
        B: 'Permanent magnet that rotates continuously',
        C: 'Thermal expansion of the copper bell gong',
        D: 'Continuous chemical reaction inside the striker',
      },
      correctAnswer: 'A',
      explanation: 'When current energizes the electromagnet, it attracts the armature and strikes the gong; this pulls the spring away from the contact screw, breaking the circuit. The spring returns the armature, re-establishing contact in a rapid make-and-break cycle.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_8_40',
      chapter: 'Magnetism',
      topic: 'Magnetism',
      chapterNumber: 8,
      question: 'Earth’s Magnetic Declination at any geographical location is defined as the angle between the:',
      options: {
        A: 'True geographic meridian (True North) and the magnetic meridian (Magnetic North)',
        B: 'Horizontal magnetic field and the vertical magnetic field component',
        C: 'Magnetic equator and the geographic equator',
        D: 'Earth’s rotational axis and the plane of the Moon’s orbit',
      },
      correctAnswer: 'A',
      explanation: 'Magnetic Declination (or magnetic variation) is the horizontal angle between true geographic North (geographic meridian) and the direction indicated by a magnetic compass (magnetic meridian).',
      difficulty: 'medium',
    },
  ],

  'Nature of Science and Physics': [
    {
      id: 'fbise9_phy_9_31',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'The renowned 11th-century polymath Ibn al-Haytham revolutionized experimental physics primarily through his masterpiece book entitled:',
      options: {
        A: 'Kitab al-Manazir (The Book of Optics)',
        B: 'Al-Qanun fi al-Tibb (The Canon of Medicine)',
        C: 'Kitab al-Jabr wa al-Muqabala',
        D: 'Zij al-Sindhind',
      },
      correctAnswer: 'A',
      explanation: 'Ibn al-Haytham (Alhazen) authored the monumental seven-volume treatise *Kitab al-Manazir* (*Book of Optics*), establishing the intromission theory of light and the modern experimental scientific method.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_32',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Abu Rayhan Al-Biruni accurately measured the radius of the Earth during the 11th century at Nandana Fort using:',
      options: {
        A: 'Trigonometric calculations based on the angle of dip of the horizon measured from a mountain top',
        B: 'Measuring the distance between two cities on camelback',
        C: 'Shadow measurements in deep water wells at noon',
        D: 'Telescopic sightings of satellite orbits',
      },
      correctAnswer: 'A',
      explanation: 'Al-Biruni determined the height of a hill using trigonometric angle measurements from a level plain, then measured the angle of dip of the sea horizon from the summit to calculate Earth’s radius ($R \\approx 6335\\text{ km}$) with remarkable accuracy.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_33',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'In modern scientific inquiry, the formal process by which independent domain experts evaluate the validity, methodology, and ethics of a scientific paper before publication is:',
      options: {
        A: 'Peer review',
        B: 'Random sampling',
        C: 'Media broadcasting',
        D: 'Trial by jury',
      },
      correctAnswer: 'A',
      explanation: 'Peer review is an essential quality control mechanism in science where other qualified scientists in the same field critically scrutinize research findings, experimental procedures, and data analysis prior to journal publication.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_34',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Unlike random measurement errors, systematic laboratory errors (such as zero error or miscalibrated scale) can be eliminated or corrected by:',
      options: {
        A: 'Identifying the calibration offset and mathematically applying the appropriate zero correction',
        B: 'Taking the arithmetic mean of 100 repeated readings with the same faulty instrument',
        C: 'Increasing the brightness of the laboratory lights',
        D: 'Repeating the experiment on a different day of the week',
      },
      correctAnswer: 'A',
      explanation: 'Systematic errors shift all readings consistently in one direction. Averaging repeated readings cannot remove a systematic error; it can only be eliminated by calibrating the apparatus or applying a known zero correction.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_35',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Medical ultrasound diagnostic imaging (Sonography) utilizes which branch and principle of physics to create internal soft tissue images without ionizing radiation?',
      options: {
        A: 'Acoustics (high-frequency ultrasonic sound wave reflections from tissue boundaries)',
        B: 'Nuclear physics (radioactive decay gamma rays)',
        C: 'Thermodynamics (heat transfer through convection)',
        D: 'Quantum electrodynamics',
      },
      correctAnswer: 'A',
      explanation: 'Ultrasound machines emit high-frequency acoustic waves ($> 20\\text{ kHz}$) into the body and detect their reflections from internal organs and tissue interfaces to generate real-time anatomical images safely.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_36',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Plasma physics is the specialized branch of physics that studies:',
      options: {
        A: 'The fourth state of matter consisting of high-temperature ionized gas containing free electrons and positive ions',
        B: 'Liquid blood plasma and biological circulation',
        C: 'Crystalline structures of solid minerals',
        D: 'Sound waves traveling through liquid helium',
      },
      correctAnswer: 'A',
      explanation: 'Plasma physics is the branch of physics that investigates the properties and behavior of ionized matter (plasma), which makes up over 99% of visible matter in the universe, including stars and interstellar space.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_37',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Abu Ali Sina (Avicenna) and Abu Rayhan Al-Biruni made pioneer contributions to experimental physics in determining the:',
      options: {
        A: 'Precise specific gravities and densities of metals, liquids, and precious gemstones using hydrostatic balance methods',
        B: 'Speed of radio waves in space',
        C: 'Splitting of atomic nuclei in nuclear reactors',
        D: 'Semiconductor properties of silicon crystals',
      },
      correctAnswer: 'A',
      explanation: 'Al-Biruni and Ibn Sina designed sophisticated hydrostatic conical balances to determine the specific gravities and densities of various metals, precious gems, and liquids with remarkable precision.',
      difficulty: 'medium',
    },
    {
      id: 'fbise9_phy_9_38',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'When performing electrical circuit experiments in a physics laboratory, what essential safety precaution must always be observed to prevent electric shocks?',
      options: {
        A: 'Ensure hands and work surfaces are completely dry, switch off the power supply before modifying wiring, and verify equipment grounding',
        B: 'Touch live wires with wet fingers to check voltage',
        C: 'Keep power supplies running at maximum voltage while disconnecting cables',
        D: 'Remove all fuses and circuit breakers from the laboratory distribution box',
      },
      correctAnswer: 'A',
      explanation: 'Water significantly reduces human skin resistance, increasing electric shock hazard. Always keep hands dry, switch off circuit power supplies before adjusting components, and ensure proper grounding.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_39',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'In the scientific method, a tentative, testable statement formulated to explain an observed natural phenomenon before experimentation is called a:',
      options: {
        A: 'Hypothesis',
        B: 'Scientific Law',
        C: 'Scientific Theory',
        D: 'Universal Constant',
      },
      correctAnswer: 'A',
      explanation: 'A scientific hypothesis is an initial, educated, testable proposal or explanation based on preliminary observations, which is then subjected to rigorous experimental verification.',
      difficulty: 'easy',
    },
    {
      id: 'fbise9_phy_9_40',
      chapter: 'Nature of Science and Physics',
      topic: 'Nature of Science and Physics',
      chapterNumber: 9,
      question: 'Modern fiber optic telecommunication systems transmit high-speed data signals through optical glass fibers utilizing the fundamental optical principle of:',
      options: {
        A: 'Total Internal Reflection',
        B: 'Thermal radiation',
        C: 'Magnetic shielding',
        D: 'Nuclear resonance',
      },
      correctAnswer: 'A',
      explanation: 'Light pulses traveling down optical fibers strike the core-cladding boundary at angles greater than the critical angle, undergoing continuous Total Internal Reflection with minimal energy loss.',
      difficulty: 'easy',
    },
  ],
};
