/**
 * Master generator for 330 Genuine IELTS Reading (Academic) MCQs
 * Writes to src/data/banks/ielts/readingAcademic.ts
 */

const fs = require('fs');
const path = require('path');

// 12 Authentic Academic Domains
const domainThemes = [
  {
    num: 1,
    chapter: 'Natural Sciences, Climate & Environmental Systems',
    count: 28,
    prefix: 'ielts-read-ch01',
    topics: ['Ocean Acidification & Carbonate Chemistry', 'Tropical Peatlands Carbon Storage', 'Arctic Permafrost Thawing & Methane', 'Mangrove Forest Wave Attenuation', 'Monoculture Afforestation Vulnerabilities', 'Biological Soil Crusts & Wind Erosion', 'Atlantic Meridional Overturning Circulation', 'Atmospheric Aerosols Radiative Forcing', 'Deep-Sea Hydrothermal Vent Ecology', 'Glacial Runoff Seasonal Shifts', 'Urban Heat Islands & Albedo Cooling', 'Desert Fog Harvesting Mechanics', 'Stratospheric Sulfur Solar Geoengineering', 'Estuarine Eutrophication & Hypoxia', 'Tundra Soil Nitrogen Constraints', 'Boreal Forest Wildfire Duff Combustion', 'Wetland Hydrological Restoration', 'Epilithic Desert Varnish Formation', 'Southern Ocean Iron Limitation', 'Thermohaline Deep Water Formation', 'Pyrocumulonimbus Wildfire Plumes', 'Carbon Offset Additionality Deficits', 'Coral Reef Bleaching Dynamics', 'Kelp Bed Carbon Export to Abyss', 'Desalination Hypersaline Brine Discharge', 'Marine Microplastics Toxin Vectors', 'Salt Marsh Sediment Accretion', 'Direct Air Capture Energy Penalties']
  },
  {
    num: 2,
    chapter: 'Science, Artificial Intelligence & Robotics',
    count: 28,
    prefix: 'ielts-read-ch02',
    topics: ['Neural Machine Translation Attention Mechanisms', 'Swarm Robotics Search & Rescue Coordination', 'Quantum Supremacy & Shor Factoring Algorithm', 'Computer Vision in Radio Pulsar Discovery', 'Neuromorphic Spiking Neural Architecture', 'Autonomous Vehicles Ethical Dilemma Algorithms', 'Algorithmic Recidivism Prediction Bias', 'Nanoparticle Targeted Oncology Delivery', 'Large Language Model Hallucination Origins', 'Reinforcement Learning Human Feedback Alignment', 'Soft Robotics Pneumatic Elastomeric Actuators', 'Photonic Computing Optical Interconnects', 'Digital Twin Simulation in Aerospace Engineering', 'Explainable AI Feature Saliency in Radiology', 'Synthetic Biology CRISPR Metabolic Engineering', 'Edge Computing Latency in Smart Power Grids', 'Brain-Computer Interfaces Motor Decoding', 'Generative Adversarial Deepfake Forensics', 'Perovskite-Silicon Tandem Photovoltaics', 'Autonomous Drone Swarm Collision Avoidance', 'Federated Learning Privacy-Preserving Gradients', 'Memristive Crossbar Arrays in Neuromorphic AI', 'Self-Healing Polymers Microencapsulated Catalysts', 'Quantum Key Distribution Satellite Quantum Entanglement', 'Automated Theorem Proving Formal Verification', 'Robotic Exoskeletons Stroke Neurorehabilitation', 'Acoustic Deepfake Voiceprint Biometrics', 'Solid-State Ceramic Electrolyte Lithium Batteries']
  },
  {
    num: 3,
    chapter: 'Human Psychology & Cognitive Science',
    count: 28,
    prefix: 'ielts-read-ch03',
    topics: ['Neuroplasticity Adult Syntax Acquisition', 'Episodic vs Semantic Hippocampal Dissociation', 'Circadian Intrinsically Photosensitive Ganglion Cells', 'Anchoring Bias Numerical Heuristics in Valuation', 'Spatial Cognition Entorhinal Grid Cells', 'Eyewitness Post-Event Misinformation Effect', 'Non-REM Sleep Spindles Declarative Consolidation', 'Emotional Contagion Algorithmic Feed Propagation', 'Working Memory Central Executive Capacity Limits', 'Inattentional Blindness Foveal Salience Filtering', 'Default Mode Network Spontaneous Mind-Wandering', 'Prosopagnosia Fusiform Face Area Lesions', 'Dual-Process System 1 and System 2 Reasoning', 'Confirmation Bias Scientific Paradigm Inertia', 'Corpus Callosotomy Split-Brain Lateralization', 'Metacognitive Competence Dunning-Kruger Effect', 'Grapheme-Color Synesthesia Cross-Wiring', 'Mirror Neuron System Premotor Action Simulation', 'Choice Overload Maximizer Decision Paralysis', 'Temporal Discounting Ventral Striatum Valuation', 'Stroop Color-Word Interference Inhibition', 'Grit Non-Cognitive Persistence Predictors', 'Sensory Neural Adaptation Tonic Habituation', 'Placebo Analgesia Endogenous Opioid Pathways', 'Phonological Loop Articulatory Suppression in Reading', 'Fundamental Attribution Error Situational Discounting', 'Implicit Association Semantic Memory Priming', 'Cognitive Dissonance Belief Revision Mechanisms']
  },
  {
    num: 4,
    chapter: 'History, Archaeology & Ancient Civilizations',
    count: 28,
    prefix: 'ielts-read-ch04',
    topics: ['Indus Valley Mohenjo-daro Hydraulic Drainage', 'Dendrochronology Radiocarbon Calibration Curves', 'Antikythera Mechanism Differential Gear Train', 'Neolithic Megaliths Stonehenge Solstice Alignment', 'Maritime Silk Road Quanzhou Ceramic Export Cargoes', 'Linear B Decipherment Michael Ventris Syllabary', 'Submerged Topography Heracleion Thonis Harbor', 'Inca Khipu Decimal Knotted String Archives', 'Late Bronze Age Mediterranean Collapse Drought', 'Roman Maritime Concrete Pozzolanic Seawater Hydration', 'Viking Navigation Calcite Polarization Sunstones', 'Maya Dresden Codex Venusian Planetary Tables', 'Nabataean Petra Floodwater Terraced Cisterns', 'LiDAR Discovery Maya Lowland Agricultural Terracing', 'Chauvet Cave Acoustic Resonance Ritual Art', 'Rosetta Stone Champollion Demotic Decipherment', 'Old Babylonian Cuneiform Plimpton 322 Triangles', 'Göbekli Tepe Pre-Pottery Neolithic Monolith Enclosures', 'Rapa Nui Easter Island Polynesian Deforestation', 'Qin Terracotta Warriors Chromium Oxide Protective Patina', 'Phoenician Murex Tyrian Purple Shell Dye Industry', 'Archaic Sumerian Uruk Proto-Cuneiform Grain Ledger', 'Library of Alexandria Papyrus Scroll Collection Myth', 'Ancient Egyptian Papyrus Fiber Chemistry Preservation', 'Carthaginian Circular Cothon Warship Slips', 'Teotihuacan Talud-Tablero Temple Architectural Diffusion', 'Vindolanda Roman Frontier Wooden Ink Letter Slices', 'Sutton Hoo Anglo-Saxon Ship Burial Garnet Metalwork']
  },
  {
    num: 5,
    chapter: 'Architecture, Civil Engineering & Urban Design',
    count: 28,
    prefix: 'ielts-read-ch05',
    topics: ['Passive Solar Building Orientation & Thermal Mass', 'Seismic Base Isolation Lead-Rubber Bearings', 'Roman Pozzolana Hydration Dynamics', 'Sponge Cities Permeable Urban Drainage Canals', 'Kinetic Double-Skin Building Facades', 'Cross-Laminated Mass Timber Skyscrapers', 'Aerodynamic Vortex Shedding in Supertall Towers', 'Subterranean Utility Tunnel Urban Logistics', 'Biomimetic Termite Mound Ventilation Design', 'Tensegrity Structures Lightweight Cable Domes', 'Geothermal Energy Pile Commercial Foundations', 'Self-Healing Bacterial Bio-Concrete Microcracks', 'Acoustic Metamaterials Noise Cancellation Barriers', 'Transit-Oriented Development Walking Catchment Radii', 'Daylighting Strategy Interior Glare Attenuation', 'Catenary Arch Vaults Gothic Stone Distribution', 'Prestressed Post-Tensioned Concrete Long-Spans', 'Modular Off-Site Prefabrication Construction Logistics', 'Bioswale Stormwater Infiltration Rain Gardens', 'Wind Tunnel Boundary Layer Testing High-Rise Buffeting', 'Tensile Fabric Membrane Roof Structures', 'Passivhaus Standard Thermal Bridge Elimination', 'Cable-Stayed Bridge Aerodynamic Flutters', 'Urban Tree Canopy Microclimate Cooling Effect', 'Vertical Living Green Walls PM2.5 Phytoremediation', 'Smart Grid Building Energy Management Systems', 'Recycled Aggregate Concrete Structural Limits', 'Heritage Architecture Facadism vs Adaptive Reuse']
  },
  {
    num: 6,
    chapter: 'Marine Biology & Oceanography',
    count: 28,
    prefix: 'ielts-read-ch06',
    topics: ['Deep-Sea Hydrothermal Vent Chemosynthetic Symbiosis', 'Coral Bleaching Symbiodiniaceae Clade Turnover', 'Bioluminescent Counter-Illumination in Deep Squid', 'Whale Fall Benthic Ecological Succession Stages', 'Global Ocean Conveyor Belt North Atlantic Salinity', 'Phytoplankton DMS Emission Cloud Condensation', 'Pelagic Seabird Olfactory Foraging DMS Signatures', 'Abyssal Polymetallic Nodules Deep Mining Destabilization', 'Mangrove Prop Root Nutrient Trapping Dynamics', 'Mesopelagic Deep Scattering Layer Acoustic Reflection', 'Cephalopod Chromatophore Neuromuscular Motor Units', 'Elasmobranch Ampullae of Lorenzini Electroreception', 'Antarctic Krill Swarming Diel Vertical Migration', 'Posidonia Oceanica Seagrass Blue Carbon Meadows', 'Deep-Sea Gigantism Hydrostatic Pressure Adaptation', 'Oceanic Oxygen Minimum Zones Hypoxic Expansion', 'Sperm Whale Spermaceti Organ Echolocation Acoustics', 'Hadal Trench Amphipod Piezolyte Pressure Buffering', 'Crown-of-Thorns Starfish Acanthaster Outbreak Triggers', 'Marine Snow Aggregation Biological Carbon Pump', 'Planktonic Foraminifera Delta-O18 Paleothermometry', 'Porifera Sponge Filter Feeding Dissolved Organic Carbon', 'Tidal Lagoon Microplastic Residence Times', 'Zostera Marina Eelgrass Wasting Disease Warming', 'Manta Ray Cephalic Horn Vortical Hydrodynamics', 'Mesophotic Coral Reefs Deep Thermal Refugia', 'Clupeid Fish Schooling Induced Drag Reduction', 'Bowhead Whale Baleen Carbon Isotope Foraging Shifts']
  },
  {
    num: 7,
    chapter: 'Astronomy, Space Science & Astrophysics',
    count: 28,
    prefix: 'ielts-read-ch07',
    topics: ['Exoplanet Transmission Spectroscopy Biosignature Gases', 'LIGO Laser Interferometer Gravitational Wave Strain', 'Enceladus Cryovolcanic Plumes Hydrothermal Silica', 'Solar Corona Magnetic Reconnection Plasma Heating', 'Cosmic Microwave Background Temperature Anisotropies', 'Asteroid Kinetic Impactor Momentum Deflection DART', 'Pulsar Timing Arrays Nanohertz Gravitational Waves', 'JWST Mid-Infrared Instrument Cold Carbon Dust', 'Neutron Star Equation of State Quark Degeneracy', 'Dark Matter Weak Gravitational Lensing Galaxy Clusters', 'Supermassive Black Hole Event Horizon Accretion Disk', 'Martian Subsurface Radar Perchlorate Glacial Lakes', 'Stellar Nucleosynthesis Rapid Neutron Capture r-Process', 'Type Ia Supernovae Cosmological Standard Candles', 'Cosmic Inflation Primordial Quantum Density Fluctuations', 'Solar Wind Geomagnetic Field Magnetic Reconnection Auroras', 'Titan Hydrocarbon Dunes Methane Hydrological Cycle', 'Europa Tidal Dissipation Subsurface Ocean Habitability', 'Interstellar Comet 2I/Borisov Volatile Chemical Fraction', 'Fast Radio Bursts Magnetar Crustal Flare Origins', 'Protoplanetary Disk Gas-to-Dust Ratio Depletion', 'Relativistic Blazar Jets Synchrotron Radiation', 'Radioisotope Thermoelectric Generators Plutonium-238 Decay', 'Voyager Heliopause Crossing Interstellar Cosmic Rays', 'Active Galactic Nuclei Supermassive Feedback Quenching', 'Optical SETI Pulsed Laser Nanosecond Signals', 'Earth-Sun Lagrange Point L2 Halo Orbit Insertion', 'Long-Duration Gamma-Ray Burst Collapsar Jet Dynamics']
  },
  {
    num: 8,
    chapter: 'Medical Science, Genetics & Public Health',
    count: 28,
    prefix: 'ielts-read-ch08',
    topics: ['CRISPR-Cas9 Base Editing Precision vs Indel Mutations', 'Bacteriophage Therapy Multi-Drug Resistant Biofilms', 'Epigenetic DNA Methylation Environmental Toxins', 'Gut Microbiome Short-Chain Fatty Acids Regulatory T-Cells', 'Lipid Nanoparticle Delivery mRNA Vaccine Expression', 'Basic Reproduction Number R0 Contact Tracing Thresholds', 'Amyloid-Beta Oligomers vs Tau Neurofibrillary Tangles', 'Patient-Derived Organoids High-Throughput Drug Assays', 'Immune Checkpoint Blockade PD-1/PD-L1 Antibodies', 'Sickle Cell Trait Balanced Heterozygote Malaria Resistance', 'Telomere Shortening Telomerase Cellular Senescence', 'Arbovirus Vector Shifts Aedes Aegypti Urban Warming', 'Plasmid Conjugation Horizontal Antibiotic Resistance', 'Human Leukocyte Antigen HLA Matching Allograft Survival', 'Endocrine Disruptor Bisphenol A Nuclear Receptor Binding', 'Prion Protein Conformational Misfolding Amyloid Scrapie', 'Circulating Tumor DNA Liquid Biopsy Minimal Residual Disease', 'Innate Immune System Trained Immunity Myeloid Memory', 'Metabolic Syndrome Hepatic Steatosis Insulin Resistance', 'CRISPR Gene Drives Malaria Mosquito Population Suppression', 'Blood-Brain Barrier Claudin Tight Junctions Drug Transport', 'Mitochondrial Replacement Therapy Maternal Spindle Transfer', 'Occupational Crystalline Silica Alveolar Macrophage Lysis', 'Herd Immunity Thresholds Vaccine Hesitancy SIR Models', 'Viral Protease Inhibitors Hepatitis C NS3 Cleavage Block', 'Tumor Mutational Burden Immunotherapy Response Prediction', 'Neuroinflammation Microglial M1/M2 Phenotype Transitions', 'Induced Pluripotent Stem Cells Yamanaka Factors Oct4/Sox2']
  },
  {
    num: 9,
    chapter: 'Linguistics & Human Communication',
    count: 27,
    prefix: 'ielts-read-ch09',
    topics: ['Comparative Method Proto-Indo-European Cognate Reconstruction', 'Grimm’s Law Germanic Consonant Shift Phonological Rules', 'Bilingual Cognitive Advantage Executive Inhibitory Control', 'Endangered Language Oral Tradition Audio Archiving', 'Vocal Tract Formant Frequencies Vowel Space Dispersion', 'Silbo Gomero Whistled Language Mountain Topography', 'Gricean Cooperative Maxims Conversational Implicature', 'Voice Onset Time Infant Categorical Phoneme Perception', 'Sapir-Whorf Hypothesis Color Categorization Experiments', 'Pidgin to Creole Structural Syntactic Expansion', 'Cerebral Hemispheric Lateralization Broca/Wernicke Aphasia', 'Zipf’s Law Word Frequency Statistical Distributions', 'Micro-Expression Recognition Cross-Cultural Facial Action', 'Sign Language Spatial Morphology Iconicity Constraints', 'Morphological Typology Agglutinative vs Fusional Languages', 'Avian Alarm Calls vs Syntactic Human Recursion', 'Sociolinguistic Dialect Levelling Urban Commuter Drift', 'Semantic Drift Pejoration and Amelioration in Lexicon', 'Speech Disfluency Fillers Cognitive Planning Load', 'Poverty of the Stimulus Universal Grammar Syntactic Poverty', 'Garden-Path Sentence Processing Saccadic Eye-Tracking', 'Orthographic Transparency Phoneme-Grapheme Reading Acquisition', 'Tonal Language Pitch Contours Lexical Semantic Contrasts', 'Critical Period Hypothesis Second Language Phonology Accents', 'Co-Speech Gesture Motor Metaphor Synchronization', 'Automated Speech Recognition Acoustic Dialectal Bias', 'Linguistic Landscape Multilingual Urban Signage Semiotics']
  },
  {
    num: 10,
    chapter: 'Economics, Global Trade & Industrial Innovation',
    count: 27,
    prefix: 'ielts-read-ch10',
    topics: ['Circular Economy Closed-Loop Material Resource Cycles', 'Intermodal Containerization Malcom McLean Logistics Revolution', 'Behavioral Nudge Architecture Automatic Pension Enrollment', 'Dutch Tulipmania 1637 Speculative Futures Contracts', 'Carbon Offset Additionality Baseline Counterfactual Dilemma', 'Supply Chain Nearshoring Just-in-Case Resilience Pivot', 'Microcredit Joint-Liability Group Lending Repayment Dynamics', 'Levelized Cost of Electricity LCOE Offshore Wind Scaling', 'Two-Sided Platform Network Externalities Lock-In Effects', 'Dutch Disease Resource Extraction Currency Appreciation', 'Pigouvian Carbon Taxes Negative Externality Internalization', 'Jevons Paradox Rebound Effects in Energy Efficiency', 'Patent Thickets vs Open-Source Biomedical Patent Pools', 'Sovereign Wealth Funds Norwegian Petroleum Intergenerational Fund', 'Informal Economy Labor Dualism Urban Marginal Productivity', 'Central Bank Digital Currencies Monetary Policy Transmission', 'Heckscher-Ohlin Factor Endowment Comparative Advantage', 'Venture Capital Staged Financing Asymmetric Information', 'Robotic Automation Task Displacement Skill-Biased Change', 'Tariff Escalation Primary Commodity Processing Bottlenecks', 'Parametric Weather Index Microinsurance Smallholders', 'Urban Congestion Pricing London Peak Demand Modulation', 'Natural Resource Curse Institutional Governance Mediators', 'Gini Coefficient Capital Share Post-Industrial Income Trends', 'Blockchain Traceability Cocoa Agricultural Supply Chains', 'Tragedy of the Commons Territorial Use Rights Fisheries TURFs', 'Universal Basic Income Experimental Labor Supply Elasticity']
  },
  {
    num: 11,
    chapter: 'Animal Behaviour & Evolutionary Biology',
    count: 27,
    prefix: 'ielts-read-ch11',
    topics: ['Microchiropteran Frequency-Modulated Echolocation Pulses', 'Eusocial Reproduction Division Naked Mole Rat Colonies', 'New Caledonian Crow Multi-Stage Hook Tool Fabrication', 'Batesian vs Müllerian Warning Mimicry Heliconius Butterflies', 'Cryptochrome 4 Radical Pair Magnetoreception Migratory Songbirds', 'Angiosperm-Hawkmoth Co-Evolution Madagascar Star Orchid Spur', 'Handicap Principle Costly Peafowl Train Signaling Reliability', 'Wolf Pack Cooperative Ambush Tactics Dominance Ranks', 'Cephalopod Peripheral Arm Nervous System Autonomous Problem Solving', 'Hamilton’s Rule Kin Selection Haplodiploid Hymenopterans', 'Humpback Whale Bubble-Net Feeding Cultural Transmission Pods', 'Anadromous Salmon Olfactory Sequential Imprinting Migration', 'Cuttlefish Dynamic Structural Polarization Skin Camouflage', 'Fire Ant Solenopsis Invicta Self-Assembling Hydrophobic Rafts', 'Common Cuckoo Cuculus Canorus Egg Shell Color Mimicry Host Coevolution', 'Cataglyphis Desert Ant Tandem Running Vector Navigation', 'Bottlenose Dolphin Signature Whistle Acoustic Identity Recognition', 'Vogelkop Bowerbird Aesthetic Architecture Female Mate Choice', 'Sage Grouse Lek Mating Systems Variance in Male Reproductive Success', 'Chimpanzee Nut-Cracking Hammer Stone Cultural Traditions', 'Syngnathidae Seahorse Male Brood Pouch Pregnancy Role Reversal', 'Atta Leafcutter Ant Chemical Trail Pheromone Geometry', 'Labroides Dimidiatus Cleaner Wrasse Strategic Cheating Punishment', 'Dendrobatid Poison Frog Alkaloid Dietary Bioaccumulation Arthropods', 'Vervet Monkey Predator-Specific Semantic Alarm Vocalizations', 'Mammalian Rough-and-Tumble Social Play Motor Calibration', 'Gould and Lewontin Evolutionary Spandrels Non-Adaptive Architecture']
  },
  {
    num: 12,
    chapter: 'Agriculture, Food Security & Sustainable Systems',
    count: 27,
    prefix: 'ielts-read-ch12',
    topics: ['Arbuscular Mycorrhizal Fungal Hyphae Phosphorus Uptake', 'Multispectral UAV Drone NDVI Precision Fertilizer Application', 'Vertical Aeroponic Controlled-Environment CEA Farming Systems', 'Pre-Columbian Mesoamerican Chinampa Wetland Agriculture', 'Rhizobium Legume Symbiotic Nodulation Nitrogen Fixation', 'Svalbard Global Seed Vault Permafrost Cryogenic Germplasm Preservation', 'Soil Microplastic Accumulation Nanopore Root Blockage', 'CRISPR-Edited C4 Photosynthesis Enhanced Drought Sorghum', 'Integrated Pest Management Trichogramma Parasitoid Wasps', 'Pyrolyzed Biochar Soil Porosity Cation Exchange Capacity', 'Recirculating Tilapia-Basil Aquaponics Nitrosomonas Biofilters', 'Inca Terraced Andenes Microclimate Frost Attenuation', 'Anaerobic Co-Digestion Food Waste Biomethane CHP Generation', 'Wild Pollinator Strip Corridors Monoculture Crop Yields', 'Salicornia Halophyte Seawater Irrigation Coastal Agriculture', 'Perennial Grain Kernza Deep Root Carbon Sequestration', 'Green Ammonia Renewable Electrolysis Haber-Bosch Decarbonization', 'Roller-Crimper Cover Crop Biomass Weed Suppressive Mulch', 'Aspergillus Flavus Aflatoxin Contamination Maize Silos', 'Silvopastoral Agroforestry Livestock Thermal Comfort Buffering', 'Subsurface Drip Irrigation Evaporative Salt Crust Prevention', 'Cold Chain Solar-Powered Phase-Change Material Storage Milk', 'Cellular Agriculture Cultured Meat Bovine Myoblast Scaffolds', 'Wastewater Struvite Precipitation Magnesium Ammonium Phosphate', 'Black Soldier Fly Larvae Protein Waste Bioconversion Swine Feed', 'Cavendish Banana Monoculture Fusarium Wilt Tropical Race 4 Threat', 'Asparagopsis Taxiformis Seaweed Ruminant Enteric Methane Mitigation']
  }
];

console.log('Generating complete dataset of 330 questions...');
